### ISSUE TITLE
Dynamic Component content does not get rendered

### ISSUE THREAD

**Issue by sbsrouteur** [QuestPDF/QuestPDF#1003]
**Describe the bug**
Dynamic component is "empty" when using loop to build content as in dynamiccomponent sample

**To Reproduce**
```

    Public Function Compose(context As QuestPDF.Elements.DynamicContext) As DynamicComponentComposeResult Implements IDynamicComponent.Compose

        Dim BoxRows = ComposeBox(context, 0).ToList()
        Dim RetElement = context.CreateElement(
            Sub(container As IContainer)
                container.ShrinkVertical.
                    Column(Sub(c As ColumnDescriptor)
                               For Each row As IDynamicElement In BoxRows
                                   c.Item().Height(15).Text("tutu")

                                   'c.Item().Element(row)
                                   'Console.WriteLine("row " & row.Size.Height)
                               Next
                           End Sub)

            End Sub)
        Dim ret As New DynamicComponentComposeResult With {.Content = RetElement, .HasMoreContent = _MoreContentAvailable}
        Return ret
    End Function
```
This code produces : 
![image](https://github.com/user-attachments/assets/3e25c372-f3c5-4a61-8807-5c78d0db1e14)

**Expected behavior**

If I change the code to : 
```
Public Function Compose(context As QuestPDF.Elements.DynamicContext) As DynamicComponentComposeResult Implements IDynamicComponent.Compose

        Dim BoxRows = ComposeBox(context, 0).ToList()
        Dim RetElement = context.CreateElement(
            Sub(container As IContainer)
                container.ShrinkVertical.
                    Column(Sub(c As ColumnDescriptor)
                               c.Item().Height(15).Text("tutu")

                               For Each row As IDynamicElement In BoxRows

                                   'c.Item().Element(row)
                                   'Console.WriteLine("row " & row.Size.Height)
                               Next
                           End Sub)

            End Sub)
        Dim ret As New DynamicComponentComposeResult With {.Content = RetElement, .HasMoreContent = _MoreContentAvailable}
        Return ret
    End Function
```
I get :
![image](https://github.com/user-attachments/assets/4d817b5d-79af-4376-a155-50f8cccae0ba)

**Environment**
What version of the library do you use? 2014.10.2-rc
What operating system do you use? (OS type, x64 vs x86 vs arm64) Win10

**Additional context**
I must be doing something wrong, but I do not get why when running in a loop, the dynamic component shrinks to nothing.

**Comment by sbsrouteur** [comment]
Ok, 

I now understand why the report is not working, but I do not know how to fix it.

The dynamic host is called many more times than required. Since I am using a state variable to remember how many rows have already been rendered, once the dynamic has reached the end of its rows, all subsequent calls have an empty content.

I have changed the code to print the calls to the compose method and the current state, and I can see way too many calls.

So I have added a workaround in my iterator to reset the collection each time it is called passed the end, and content now displays. But performance is awful.
Which step did I miss that make my dynamic component being called so many times.

**Comment by sbsrouteur** [comment]
I have simplified my layout to only have a single occurrence of my dynamic component, only on the first page and it renders like this : 
![image](https://github.com/user-attachments/assets/097c5e13-a00d-464f-b4ab-dedd7228105e)

(render is good but 1 line is missing, there should be 4)
However, I have added a trace to see how many times, the compose gets called and with which available height , and forced the the "hasmorecontent" to false for limit output to what will fit on the first render:
```
 Public Function Compose(context As QuestPDF.Elements.DynamicContext) As DynamicComponentComposeResult Implements IDynamicComponent.Compose
        Static CallsCount = 0

        Dim BoxRows = ComposeBox(context, 0).ToList()
        CallsCount += 1
        Dim RetElement = context.CreateElement(
            Sub(container As IContainer)
                container.
                    Column(
                        Sub(col As ColumnDescriptor)
                            For Each row As IDynamicElement In BoxRows
                                col.Item().Element(row)
                                'Console.WriteLine("row " & row.Size.Height)
                            Next
                        End Sub)
            End Sub)

        Console.WriteLine(CallsCount & vbTab & "avail.height " & context.AvailableSize.Height & " skip rows " & _RowsSkipCount & " has more " & _MoreContentAvailable)
        Dim ret As New DynamicComponentComposeResult With {.Content = RetElement, .HasMoreContent = False}
        Return ret
    End Function
```

At run time this produces the following output:
```
1       avail.height 659,4043 skip rows 4 has more False
2       avail.height 659,4043 skip rows 4 has more False
3       avail.height 659,4043 skip rows 4 has more False
4       avail.height 659,4043 skip rows 4 has more False
5       avail.height 80,09473 skip rows 3 has more True
6       avail.height 659,4043 skip rows 4 has more False
7       avail.height 659,4043 skip rows 4 has more False
8       avail.height 659,4043 skip rows 4 has more False
9       avail.height 659,4043 skip rows 4 has more False
10      avail.height 80,09473 skip rows 3 has more True
```
And I can see that on the 5th and 10th call, the available space is shorter, allowing for only 3 lines. Any idea to fix this? If I render the additional dynamic component instances, the app takes so long to render, it seems dead for several minutes.

**Comment by sbsrouteur** [comment]
FWIW, I have made progress on my issue.
1/ I MUST use a dynamic<of TState> component type to get proper handling of the statefull render.
2/ I have to refrain from running in debug mode, since the runtime performance get too degraded when running with my report
3/ I have to cache elements created for the report, since the compose function gets called many more times than component actually appears in the report.

The report is 73  pages long with 3900 report lines using non dynamic components, ,and there are 3 dynamic statul components which can span over more than 1 page. It takes about 20s to render with the 3 dynamic components being each called ~200 times.

Is the amount of additional call normal? Or am I facing an issue that will get worse when reports have more and more pages?

**Comment by sbsrouteur** [comment]
Hi, 

Ok, here is what I currently have which is done as a stateful dynamic component, and is still not doing what I need. I achieved the component result quite quickly, ,but could not figure how to get the required result, so I switched to dynamic.

![image](https://github.com/user-attachments/assets/17397468-46c6-4321-a574-6a052093dc86)

We are print test results. A test is a long list of test names with test results. Each test can have an optional display for test events that occurred during the test sequence. (or there can be event before the test starts, as can be seen below header on 1st page).

The events can be short and fit on 1 line or longer and require 2 or more lines. I would like to have an extrapadding when the text is more than 1 line long. As far as I have seen there is no way of measuring the element in a regular component, so I tried with dynamic. 

It is not working yet because, as I understand it, I need to chain the settings as follows :
 container.column.paddingbottom(<I do not know yet how much will go there>)(col=> column render)

And I do not know how much bottom padding is needed before the text comes-in and get measured. I looked into the code, but but textblock constructors are sealed. I could have :
textblock( mytextvalue)
measureheight
bottompadding= (ismorethan1line)? bigpadding:smallpadding
Container.column.bottompadding(bottompadding)....

**Comment by girlpunk** [comment]
Hi, If I've understood what you're trying to achieve, something like this should be able to do what you want without using a dynamic component:

```csharp
page.Column(outerColumn =>
{
    outerColumn.Item()
        .Border(2)
        .Column(innerColumn =>
        {
            // Title for first table
            innerColumn.Item().Text("Journal de I'essai");
            innerColumn.Item().Table(table =>
            {
                table.table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn();
                    columns.ConstantColumn(10);
                    columns.ConstantColumn(5);
                    columns.ConstantColumn(20);
                });

                table.Header(header =>
                {
                    header.Cell();
                    header.Cell().Text("Date");
                    header.Cell().Text("Opérateur");
                    header.Cell().Text("Description");
                });

                foreach (var row in firstTableData)
                {
                    table.Cell().Image(row.Icon);
                    table.Cell().Text(row.Date.ToString());

                    // This could be optimised, but keeping simple as an example
                    var descriptionCell = table.Cell();

                    if(row.Description.Length() > 100)
                        descriptionCell = descriptionCell.PaddingBottom(15);
                    descriptionCell.Text(row.Description);
                }
            });
        });

    // Repeat above for second table, etc
});
```

**Comment by sbsrouteur** [comment]
:) back to square 1 with solution to add the additional padding. I will try that.

So I will ask before going the statefull dynamic component way. How can I insert a page break if the test component does not have at least 5cm at the bottom of the page, unless the test results fit in the page available space.
below example of test S22 is at the end of the page. I would look better with a page break before, since there are about 1.5 of results for this step.
![image](https://github.com/user-attachments/assets/7e3cf5f8-6e80-4c6f-b128-de791e2342c1)

**Comment by girlpunk** [comment]
`.EnsureSpace(150)` should do that, you can adjust the value as needed to adjust the amount of space required before the page break

**Comment by sbsrouteur** [comment]
I have just tried .ensurespace(150). but it seems this does not get honored if the component is more than 1 page long:
![image](https://github.com/user-attachments/assets/6bb42f49-dbb6-473c-997d-adfe180a9ab7)

Below the code, I have added a bordertop top have a visiblemark of the ensurespace action point and this looks wrong, the bar should be above S2:
```
Public Sub Compose(container As IContainer) Implements IComponent.Compose

        Dim Phases = _Data.GetPhasesInExecutionOrder()
        container.PaddingTop(1).PaddingVertical(4).
            Column(Sub(col As ColumnDescriptor)
                       col.Spacing(2)

                       If _ReportTemplateParams.ShowTestParameters AndAlso _Data.TestParametersList().Count > 0 Then
                           col.Item.Component(Of TestParametersBox)(New TestParametersBox(_Data))
                       End If

                       If _ReportTemplateParams.ShowTestLog AndAlso _Data.TestLog(Nothing).Count > 0 Then
                           col.Item.PaddingTop(1).Border(1).Component(Of LogMessageBox)(New LogMessageBox(_Data, Nothing))
                       End If

                       For Each Phase As TestPhaseModel In Phases.Values
                           col.Item().EnsureSpace(150).BorderTop(1).Padding(2).PaddingLeft(2).
                             Row(Sub(row As RowDescriptor)

                                     row.RelativeItem(1).Component(Of PhaseSection)(New PhaseSection(Phase, _Data, _ReportTemplateParams))

                                 End Sub)
                       Next
                   End Sub)
    End Sub
End Class

```
The PhaseSection component starts with S2 (the phasename) then list all result lines from the testphase.

**Comment by sbsrouteur** [comment]
Ok,

I was wrong again. I have been ensurespace works as expected. I missed the fact that I have to put it in each subsection of my phase to ensure proper rendering.
The line at the top of the page is just a repeat of the bordertop in the phase section. I guess that with a skiponce and showonce I should be able to fix this.

Thank you for your help. I guess I can close the comment, since all works as expected :)
