### ISSUE TITLE
Transparency of HEX ARGB Colors is not correct when A is 00

### ISSUE THREAD

**Issue by BeneHenke** [QuestPDF/QuestPDF#1014]
**Describe the bug**
The opacity of the Hex ARGB colors is 100 % when starting with 00 when its supposed to be 0 %. Only when using 00000000 it is 0%. 

**To Reproduce**
Color.FromHex("00FF0000"); is Red when it is supposed to have 0 % opacity.

**Environment**
What version of the library do you use? 
2024.7.3

**Comment by MarcinZiabek** [comment]
Thank you for reporting this issue :)

This behavior is intentional and related to how colors can be provided as uints. This way, developers do not need to include the alpha channel.

```c#
.BorderColor("#123456") // performance overhead of string parsing
.BorderColor(0x123456) // the faster way
.BorderColor(0xFF123456) // optional alpha channel in AARRGGBB
```

**Comment by BeneHenke** [comment]
But doesn't this approach lead to issues when the user wants to define the color black like this, because it would be read as transparent?
```
.BorderColor(0x000000)
```

**Comment by BeneHenke** [comment]
The issue also extends to using the ARGB method as a value of 0 for opacity will not set the color transparent unless you are also setting the other parameters 0.

**Comment by MarcinZiabek** [comment]
Fair point! I have implemented an improvement to mitigate this issue in the following commit: https://github.com/QuestPDF/QuestPDF/commit/66aa03183e797a665a84fd55fb45ac193b92a640

Thank you for pointing me in the right direction 😄

**Comment by BeneHenke** [comment]
Thank you!
