### ISSUE TITLE
Align (center, left, right) on table header makes background color small

### ISSUE THREAD

**Issue by DINH-iy** [QuestPDF/QuestPDF#1069]
**Describe the bug**
When you pass a background color to a table header everything looks correct, the box gets filled entirely. When you however want to center the text in the middle the background color is only around the text, the rest of the header is white.

**To Reproduce**

table.Header(header =>
                    {

                        header.Cell().Background("#32a852").Text("Normal header").SemiBold();
                        header.Cell().AlignCenter().Background("#32a852").Text("Wrong header").SemiBold();
                    });

**Expected behavior**
I expect the color to still fill the entire header, not just a small portion of the header

**Screenshots**

<img width="129" alt="image" src="https://github.com/user-attachments/assets/2e0e186f-94f9-4414-b205-6a967fa37baf">
<img width="838" alt="image" src="https://github.com/user-attachments/assets/63350d22-ff59-4bad-96f2-fda3547f8af9">

In the screenshot above the first column has the aligncenter and the color goes weird. I expect the color to fill the entire header

**Comment by DINH-iy** [comment]
Its fixed by settings the align in the text builder

**Comment by girlpunk** [comment]
This is expected behaviour, as operations are run in the order they are applied. Something like this may also achieve your desired result

```csharp
header.Cell().Background("#32a852").AlignCenter().Text("Wrong header").SemiBold();
```
