### ISSUE TITLE
How to layout a row of elements so that they are close together?

### ISSUE THREAD

**Issue by 107295472** [QuestPDF/QuestPDF#1071]
```
page.Content()
						//.PaddingVertical(1, Unit.Centimetre)
						.Column(x =>
						{
							x.Item()
								.Row(r =>
								{

									r.ConstantItem(50)
									.AlignRight()
										.Image(File.ReadAllBytes(@"logo.jpg"))
										.FitWidth();
									r.RelativeItem(2)
										.AlignCenter()
										.Text("test")
										.SemiBold()
										.FontSize(38);
									r.ConstantItem(70).AlignLeft().Text("( test )");
								});
						});
```
Let the two closest elements stick to the middle

**Comment by girlpunk** [comment]
Are you able to show an example of what you want to achieve? Doesn't have to be perfect, mspaint will suffice

**Comment by 107295472** [comment]
mspaint What is

**Comment by 107295472** [comment]
Is there a way to get coordinates?

**Comment by girlpunk** [comment]
> mspaint What is

https://en.wikipedia.org/wiki/Microsoft_Paint



> Is there a way to get coordinates?

Coordinates of what? The answer is likely no, as QuestPDF is a rules based layout engine, not a compositor.
