### ISSUE TITLE
Document previewer do not work 

### ISSUE THREAD

**Issue by IngoManthey** [QuestPDF/QuestPDF#1072]
I created a new .Net9 console app.
I have installed the previewer:
PM> dotnet tool install QuestPDF.Previewer --global
I copied the code from the page into my new console project.
I changed GeneratePdf("hello.pdf");
.ShowInCompanion();

Then I started the program in debug mode. I get follow exception
Cannot connect to the QuestPDF Companion tool. Please ensure that the tool is running and the port is correct.
I don't know which port I should enter?

Unhandled exception. System.Exception: Cannot connect to the QuestPDF Companion tool. Please ensure that the tool is running and the port is correct. Learn more: https://www.questpdf.com/companion/usage.html
at QuestPDF.Companion.CompanionService.CheckIfCompanionIsRunning()
at QuestPDF.Companion.CompanionService.Connect()
at QuestPDF.Companion.CompanionExtensions.ShowInCompanionAsync(IDocument document, Int32 port, CancellationToken cancellationToken)
at QuestPDF.Companion.CompanionExtensions.ShowInCompanion(IDocument document, Int32 port)
at Program.

$(String[] args) in C:\Users\ingo\source\repos\Test\Test\Program.cs:line 11
C:\Users\ingo\source\repos\Test\Test\bin\Debug\net9.0\Test.exe (Prozess "27432") wurde mit Code "-532462766"

What can I do?

**Comment by MarcinZiabek** [comment]
Starting from the 2024.10 version, the QuestPDF Previewer has been deprecated. 

Please use the newer and more feature-rich QuestPDF Companion App:
- Features: https://www.questpdf.com/companion/features.html
- Download: https://www.questpdf.com/companion/download.html
