### ISSUE TITLE
How to keep items "together" and not break them appart?

### ISSUE THREAD

**Issue by Oaktribe** [QuestPDF/QuestPDF#108]
Currently I have something like this which I append as the last content

```
private void ComposeSupport(IContainer container)
{
    container.PaddingTop(PADDING_TOP).Stack(stack =>
    {
        stack.Item().Text("Support Headline", _headerStyle);
        stack.Item().Text("Support text and other info");
    });
}
```

Which works fine, however, sometimes the content before is large enough to put the support headline on page 1 and the support text on page two.

Is there a way keep the container in the same page? Example, if everything won't fit on page 1, it will then instead be on page 2.

**Comment by MarcinZiabek** [comment]
Yes, it is possible by using the `ShowEntire` element, [take a look here](https://www.questpdf.com/documentation/api-reference.html#scale).

Naming stuff is difficult - if you have a better idea of how to name this element, please share! 😄

**Comment by Oaktribe** [comment]
That worked! Thank you!

Yeah, naming stuff is hard 😅
When I first read documentation of that I thought it meant everything will be shown as a single page, I.e. no pagination at all.
_(English is not my first language, so it could be I misunderstood it too)_

I think a example would improve it. Maybe something like this?
```
container.ShowEntire().Stack(stack =>
{
    stack.Item().Text("Headline");
    stack.Item().Text("This text and headline will be kept on the same page.");
});
```
