### ISSUE TITLE
Text w/ Action<TextDescriptor> Content

### ISSUE THREAD

**Issue by blazingcayenne** [QuestPDF/QuestPDF#1082]
**Describe the bug**
I would expect Text("abc") and Text(t => t.Line("abc")) to render the same output. However, the lambda version renders an extra line.

**To Reproduce**

1. Create a new DotNot console app.
2. Add the QuestPDF version 2024.12.1 library via NuGet.
3. Replace Program.cs with the following source code.
4. Run the console app.
5. Examine `test.pdf` in the bin directory.

```
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

QuestPDF.Settings.License = LicenseType.Community;

Document
    .Create(container =>
    {
        container.Page(page =>
        {
            page.Size(PageSizes.Letter);
            page.Margin(1, Unit.Inch);
            page.PageColor(Colors.White);
            page.Content()
                .Column(x =>
                {
                    x.Spacing(0);
                    x.Item().Text("Line 1");
                    x.Item().Text(t => t.Line("Line 2"));
                    x.Item().Text("Line 3");
                });
        });
    })
    .GeneratePdf("test.pdf");
```

**Expected behavior**
I expect the rendered output to be as follows.
```
Line 1
Line 2
Line 3
```

Instead I see the following.
```
Line 1
Line 2

Line 3
```

**Screenshots**
<img width="820" alt="image" src="https://github.com/user-attachments/assets/101462d7-9246-4033-8273-9a20d7dea1cd" />

**Environment**
What version of the library do you use?
QuestPDF version 2024.12.1 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2024.12.1" />
  </ItemGroup>

</Project>
```
What operating system do you use? (OS type, x64 vs x86 vs arm64)
* macOS 14.7 (23H124) - Sonoma
* dotnet version 8.0.403

**Comment by girlpunk** [comment]
`.Text("abc")` is equivilant to `.Text(t => t.Span("abc"))`, the only difference between `Line` and `Span` is the newline that gets added to the end.

**Comment by blazingcayenne** [comment]
If I understand you correctly, then newlines are added to **both** the `.Text(t => { ... })` method and the `t.Line(...)` methods in the lambda function. In other words, the behavior in my example is expected and correct.

Suppose I wanted to render several paragraphs using `.Text(t => {})` and `t.Line("...")`. If I did not want the extra newline at the end of the last paragraph, then would I need to use `t.Span("...")` to render the last paragraph? If so, this is inconvenient when looping through an `IEnumerable<string>`. I would have to write a special iterator to look ahead and return both the current string as well as a boolean whether it is the last item.

**Comment by deepchauhan2002** [comment]
Hi @girlpunk  I want to work on this if we want this behavior to be fixed?

**Comment by girlpunk** [comment]
@blazingcayenne In that scenario, something like this could be considered:
```csharp
IEnumerable<string> paragraphs = [...];
var text = string.join('\n', paragraphs);
x.Text(text);
```

**Comment by blazingcayenne** [comment]
I was using the lambda version because I want to set the paragraph spacing via `t => t.ParagraphSpacing(SomeConstant);` to be different than the column spacing set by `x => x.Space(AnotherConstant)`. Is there a way to achieve the same result by joining the paragraphs with a newline and using `x.Text(string.join('\n', paragraphs))`?

My work around was to create an inner Column within the outer Column and set their spacings accordingly.

**Comment by girlpunk** [comment]
Yes, something like this:
```csharp
IEnumerable<string> paragraphs = [...];
var text = string.join('\n', paragraphs);
x.Text(t => {
    t.ParagraphSpacing(SomeConstant);
    t.Span(text);
});
```

**Comment by blazingcayenne** [comment]
@girlpunk, thank you for engaging and answering my questions. I appreciate your time.
