### ISSUE TITLE
chinese language support?

### ISSUE THREAD

**Issue by HandsomeBoy01** [QuestPDF/QuestPDF#109]
Hello, author, how to set the Chinese text?  I export PDF if text is Chinese, it will be garbled

**Comment by HandsomeBoy01** [comment]
@Marcin Ziąbek  Is there a solution?

**Comment by HandsomeBoy01** [comment]
I solve

**Comment by blockhunts** [comment]
@HandsomeBoy01 How did you solve it?

**Comment by wossig** [comment]
> @HandsomeBoy01 How did you solve it?

Specify font family I think

**Comment by impPDX** [comment]
大佬，中文问题怎么解决的 怎么使用微软雅黑

**Comment by impPDX** [comment]
大佬中文问题怎么解决的啊？

**Comment by HandsomeBoy01** [comment]
> 

 FontManager.RegisterFontType("simsun", File.OpenRead($"{AppDomain.CurrentDomain.BaseDirectory}/simsun.ttc"));  后面的是字体的文件

**Comment by HandsomeBoy01** [comment]
@impPDX   看我的回复， 注册一下字体文件就行了

**Comment by HandsomeBoy01** [comment]
@blockhunts   看上面的回复

**Comment by impPDX** [comment]
![image](https://user-images.githubusercontent.com/50691694/164430092-e380511e-ebb3-4689-97c6-3966ce988757.png)
该方法已过时了

**Comment by HandsomeBoy01** [comment]
@impPDX   过时了，你替换一下不就行了， 归根结底就是 找到字体文件，转换成 stream 然后注册 ，就行了，你看下面不是提示你了， 让你用RegisterFont ， 其实都一样

**Comment by impPDX** [comment]
@HandsomeBoy01 好的谢谢

**Comment by impPDX** [comment]
@HandsomeBoy01   static void Main(string[] args)
        {





            FontManager.RegisterFont( File.OpenRead($@"C:\Windows\Fonts\simhei.ttf"));

            Document.Create(container =>
            {

                container.Page(page =>
                {
          
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
        
                    page.PageColor("#43a047");
                    page.DefaultTextStyle(x => x.FontSize(20));
                   
                    page.Header()
                        .Text("Hello PDF!")
                        
                        .SemiBold().FontSize(36).FontColor(Colors.Blue.Medium);

                    page.Content()
                    
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Spacing(20);

                            // x.Item().Text(Placeholders.LoremIpsum());
                            x.Item().Text(GetStringData());
                            x.Item().Image(GetPictureData());
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Page ");
                            x.CurrentPageNumber();
                        });
                })
                ;
            })
               
            .GeneratePdf("hello.pdf");
        }


        public static byte[] GetPictureData()
        {
            FileStream fs = new FileStream(@"D:\333.jpg", FileMode.Open);
            byte[] byteData = new byte[fs.Length];
            fs.Read(byteData, 0, byteData.Length);
            fs.Close();
            return byteData;
        }
        public static string GetStringData()
        {
            string s = null;
            string m = s ?? "1";
   
            string utf8String =   $@"{"123"}活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活
复活复活复活复活
复活复活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活
";
            return utf8String;
        }

        
    }


为什么我这样生成还是乱码？能加您一个联系方式吗？

**Comment by impPDX** [comment]
@HandsomeBoy01 您好，能加你一个联系方式吗？我这样写也不行的

      static void Main(string[] args)
        {





            FontManager.RegisterFont( File.OpenRead($@"C:\Windows\Fonts\simhei.ttf"));

            Document.Create(container =>
            {

                container.Page(page =>
                {
          
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
        
                    page.PageColor("#43a047");
                    page.DefaultTextStyle(x => x.FontSize(20));
                   
                    page.Header()
                        .Text("Hello PDF!")
                        
                        .SemiBold().FontSize(36).FontColor(Colors.Blue.Medium);

                    page.Content()
                    
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Spacing(20);

                            // x.Item().Text(Placeholders.LoremIpsum());
                            x.Item().Text(GetStringData());
                            x.Item().Image(GetPictureData());
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Page ");
                            x.CurrentPageNumber();
                        });
                })
                ;
            })
               
            .GeneratePdf("hello.pdf");
        }


        public static byte[] GetPictureData()
        {
            FileStream fs = new FileStream(@"D:\333.jpg", FileMode.Open);
            byte[] byteData = new byte[fs.Length];
            fs.Read(byteData, 0, byteData.Length);
            fs.Close();
            return byteData;
        }
        public static string GetStringData()
        {

   
            string utf8String =   $@"{"123"}活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活
复活复活复活复活
复活复活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活
复活复活复活复活复活复活复活复活复活复活复活复活复活
";
            return utf8String;
        }

        
    }

**Comment by wossig** [comment]
> ![image](https://user-images.githubusercontent.com/50691694/164430092-e380511e-ebb3-4689-97c6-3966ce988757.png) 该方法已过时了

Yeah, this method already be obsoleted,  but it still works for now,  I think here has an issue,  when we use new method signation which without font alias to register Chinese font,  it seems cannot get font name correctly. you can @ author for further infomation.

BWT, please use English if you can,  so that the auther can join the thread,  he's a good guy!

**Comment by HandsomeBoy01** [comment]
@impPDX   容易，你加我，我试试看 我的QQ 948645401

**Comment by impPDX** [comment]
@HandsomeBoy01 已添加

**Comment by wossig** [comment]
> @HandsomeBoy01 您好，能加你一个联系方式吗？我这样写也不行的
> 
> ```
>   static void Main(string[] args)
>     {
> 
> 
> 
> 
> 
>         FontManager.RegisterFont( File.OpenRead($@"C:\Windows\Fonts\simhei.ttf"));
> 
>         Document.Create(container =>
>         {
> 
>             container.Page(page =>
>             {
>       
>                 page.Size(PageSizes.A4);
>                 page.Margin(2, Unit.Centimetre);
>     
>                 page.PageColor("#43a047");
>                 page.DefaultTextStyle(x => x.FontSize(20));
>                
>                 page.Header()
>                     .Text("Hello PDF!")
>                     
>                     .SemiBold().FontSize(36).FontColor(Colors.Blue.Medium);
> 
>                 page.Content()
>                 
>                     .PaddingVertical(1, Unit.Centimetre)
>                     .Column(x =>
>                     {
>                         x.Spacing(20);
> 
>                         // x.Item().Text(Placeholders.LoremIpsum());
>                         x.Item().Text(GetStringData());
>                         x.Item().Image(GetPictureData());
>                     });
> 
>                 page.Footer()
>                     .AlignCenter()
>                     .Text(x =>
>                     {
>                         x.Span("Page ");
>                         x.CurrentPageNumber();
>                     });
>             })
>             ;
>         })
>            
>         .GeneratePdf("hello.pdf");
>     }
> 
> 
>     public static byte[] GetPictureData()
>     {
>         FileStream fs = new FileStream(@"D:\333.jpg", FileMode.Open);
>         byte[] byteData = new byte[fs.Length];
>         fs.Read(byteData, 0, byteData.Length);
>         fs.Close();
>         return byteData;
>     }
>     public static string GetStringData()
>     {
> 
> 
>         string utf8String =   $@"{"123"}活复活复活复活复活复活复活复活
> ```
> 
> 复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活 复活复活复活复活 复活复活复活复活复活复活复活复活复活 复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活 复活复活复活复活复活复活复活复活复活复活复活复活复活 复活复活复活复活复活复活复活复活复活复活复活复活复活复活复活 复活复活复活复活复活复活复活复活复活复活复活复活复活 "; return utf8String; }
> 
> ```
> }
> ```

You should specify font explicitly 

`
x.Item().Text(GetStringData()).FontFamiliy("<fontname>")
`

**Comment by impPDX** [comment]
Fontmanager Registerfonttype ("Microsoft YaHei", s); This method allows me to solve the problem of Chinese garbled code; But fontmanager RegisterFont(s); This method can not solve the problem of Chinese garbled code!

**Comment by impPDX** [comment]
@wossig  @HandsomeBoy01  I've solved it. Thank you

**Comment by huangjiaxiang** [comment]
Chinese font file is too big。 how do you solve？

**Comment by HandsomeBoy01** [comment]
@huangjiaxiang  ttc wrong font file，Replace font file

**Comment by HandsomeBoy01** [comment]
new version registration
 FontManager.RegisterFontWithCustomName("simsun", File.OpenRead($"{AppDomain.CurrentDomain.BaseDirectory}/simsun.ttc"));
 
use

table.Cell().Element(Block).Text(t =>
                    {
                        t.DefaultTextStyle(x => x.FontFamily("simsun"));
                    });

**Comment by huangjiaxiang** [comment]
> 
I can't find a smaller font file？

**Comment by HandsomeBoy01** [comment]
Hold on, I'll upload one

https://wwkd.lanzouw.com/ioyXO0uqhx1i

you can download and try it  @huangjiaxiang

**Comment by huangjiaxiang** [comment]
> Hold on, I'll upload one
> 
> https://wwkd.lanzouw.com/ioyXO0uqhx1i
> 
> you can download and try it @huangjiaxiang

it's also too big。 the PDF files size is 5M
