### ISSUE TITLE
Get maximum height of content space

### ISSUE THREAD

**Issue by JSR33** [QuestPDF/QuestPDF#110]
Hi. 
This is not a bug it's more an "how to do it".
I'm using complex grids where I need to give an height to some of the cells. Question: How do I know the maximum value of height that I can use? 
I can get the Pagesize (PageSizes.A4.Landscape().Height) but if I add an header and footer to the page this will not be my available content size.
Any tip to solve this?

**Comment by MarcinZiabek** [comment]
It is difficult to provide the available size because of the dynamic nature of documents. I am not sure what exactly you are trying to accomplish. As far as I understand, you may want to make a try with the `ExtendVerical` element 😀

**Comment by JSR33** [comment]
It doesn't solve my all problem. 
In a relative column it actually work pretty well but when have a grid inside of a relative column it doesn't divide the rows for all the space that I have in the column.
I'd love to attach an image but, don't know why, I'm not able to do it.

**Comment by JSR33** [comment]
Meanwhile I can do a workaround and set the header and footer heigh to a fixed size and that way I always know the free space that I have.

**Comment by JSR33** [comment]
> As far as I know, posting an image is simple: just copy the file and paste it into the text. It should be uploaded automatically and attached as markdown 😀

I know :D But is always returning an error when it try to upload the image.

> I expect that in the future, the DynamicComponent will help you with more complex/custom layouts. The development is discussed here. Unfortunately, this is still in the experimental phase as relies on other architectural concepts that are not stable enough to make them public.

Ok, no problem. You can close this issue and I'll be looking for future improvements on this.
Btw, congratulations. Excellent job with the library!

**Comment by MarcinZiabek** [comment]
> Ok, no problem. You can close this issue and I'll be looking for future improvements on this.

Or please describe your needs more precisely. So even I can understand 😁
