### ISSUE TITLE
Xamarin.Forms - FontFamily

### ISSUE THREAD

**Issue by marcosgerene** [QuestPDF/QuestPDF#111]
Hi everyone,

I am trying to use the library on a mobile application (Xamarin.Forms) to run on iOS and Android Plataform.

Using the library I faced this problem:

![image](https://user-images.githubusercontent.com/15945003/151441121-926b95f3-6134-44b1-ad59-39dfbddf6ff6.png)

So I tried this:

```
private static string _FontFamily = Xamarin.Forms.Device.RuntimePlatform == Xamarin.Forms.Device.iOS ? "Helvetica" :
                                            Xamarin.Forms.Device.RuntimePlatform == Xamarin.Forms.Device.Android ? "Droid Sans" :
                                            throw new NotImplementedException();

public void Compose(IDocumentContainer container)
{
	container
		.Page(page =>
		{
			page.Margin(50);
		   
			page.DefaultTextStyle(TextStyle.Default.FontType(_FontFamily));

			page.Header().Element(ComposeHeader);
			page.Content().Element(ComposeElement);
			page.Footer().Element(ComposeFooter);
		});
}
```

And I tried some fonts, but all I tried did not work, I got the same error: The typeface (font's name) could not be found...
Can someone please tell me any font that I can use?

**Comment by marcosgerene** [comment]
I changed to "sans-serif" on Android and I got another error, so I guess the font-family is okay now.

**Comment by MarcinZiabek** [comment]
Hello 😁 Loading a font by name assumes that the given font is available in the runtime environment. Sometimes, e.g. on the cloud services, there are no fonts preinstalled - hence the exception. You can attach a font file to your project and then load it in QuestPDF. [Please read this article and try it.](https://www.questpdf.com/documentation/patterns-and-practices.html#accessing-custom-fonts)
