### ISSUE TITLE
Dynamic subtotal / variables per page

### ISSUE THREAD

**Issue by itmuckel** [QuestPDF/QuestPDF#121]
**Is your feature request related to a problem? Please describe.**
We want to generate invoices that may span multiple pages. We want the table footer to show the subtotal of the invoice items so far on the page. On the last page (or on the only page if there is only one) the footer should instead show the sum of all invoice items.

**Describe the solution you'd like**
I'm not sure how a good solution to this problem might look, but I think the use case is fairly common.
One solution might be to access the number of rows rendered on a page, so I know how many prices to add? Either way I have to know where my elements ended up in order to determine what the footer should contain.

**Describe alternatives you've considered**
Maybe it's possible to check if the next row to render is still on the current page and if not change the footer? I'm also not sure how to do that.

**Comment by MarcinZiabek** [comment]
Your requirements sounds very similar to the `DynamicComponent` idea [discussed here](https://github.com/QuestPDF/QuestPDF/discussions/39). Can you please take a look there and confirm this is the same functionality?

**Comment by itmuckel** [comment]
Yes, that's what we need. Any plans to publish the DynamicComponent or to bring it into the main branch?

**Comment by MarcinZiabek** [comment]
I am considering publishing this functionality next week. It will be either a pre-release version or an experimental add-on nuget 😁 

Do you have any suggestions regarding this feature? Any help to make the API easy to understand is welcome (please answer in the discussion linked above) 😁

**Comment by itmuckel** [comment]
No suggestions. I'll close this and if we run into problems, I'll open a new issue, thanks!
