### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by shojajou** [QuestPDF/QuestPDF#126]
I was implementing a PDF composer for our product. Then in the middle of implementation, When I check the result, I realized the library does not support RTL languages. And you didn't mention in the docs.

I need to make PDF in Persian language.

**Comment by MarcinZiabek** [comment]
Hello 😁 Indeed, QuestPDF does not support RTL languages at this moment. However, I am planning to investigate this area very soon. Would you like helping me with this topic? I am assuming that you can validate if library produces correct results. I can prepare experimental releases so we can cooperate.

**Comment by MarcinZiabek** [comment]
The RTL support was added to the current roadmap 😁 Once I start working on it, I am planning to open a special GitHub discussion, where community will be able to help. Closing
