### ISSUE TITLE
Text not showing when running under Alpine

### ISSUE THREAD

**Issue by ebi-j** [QuestPDF/QuestPDF#129]
**Describe the bug**
I have .net 6 a web api running under Alpine Docker to generate pdf files. The PDF doesn't seem to show the text.

![image](https://user-images.githubusercontent.com/72199341/155670020-319c774d-34d9-42c5-948a-5d72d6cb7d77.png)

If I run the API in normally debug mode, rather than in Docker. It works as expected.

![image](https://user-images.githubusercontent.com/72199341/155670185-55474511-29bc-4d75-a945-981779112e96.png)

I have `skiasharp.nativeassets.linux.nodependencies(2.80.3)` installed (otherwise it will have dll not found exception).
I've also added `RUN apk add --no-cache fontconfig` however it does have any effect (I thought it was font issue).

**Expected behavior**
To show the text in Alpine.

**Comment by RHaughton** [comment]
I'm having the exact same issue on Ubuntu Server. 


![image](https://user-images.githubusercontent.com/24850599/155706443-9cb280b2-fd67-4651-84bf-9a28ce25f0b1.png)

**Comment by MarcinZiabek** [comment]
@RHaughton Which language are you using? Can you please try with a different font?

**Comment by RHaughton** [comment]
Solved my issue by installing microsoft fonts using this tutorial:
https://itsfoss.com/install-microsoft-fonts-ubuntu/

**Comment by MarcinZiabek** [comment]
What fonts have you used?

**Comment by ebi-j** [comment]
I didn't set any font, so I assume it's the default font from the library.

**Comment by ebi-j** [comment]
Resolved by adding the following command to the Dockerfile:

```Dockerfile
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f
```
