### ISSUE TITLE
Image with fixed size

### ISSUE THREAD

**Issue by JSR33** [QuestPDF/QuestPDF#131]
It's not a bug. It's an how to use/how to do it.

I want to fix the size of one image instead of using the autofit, etc. I saw you have in API reference an option for Dynamic Images but then when using your package I'm not able to find it (could be because I'm not in the most recent version).
Meanwhile I saw that you have this method:

Image(this QuestPDF.Infrastructure.IContainer element, System.Func<QuestPDF.Infrastructure.Size, byte[]> imageSource)

However I'm not getting how to use it.

**Comment by girlpunk** [comment]
Dynamic images are for generating images to fit the available size of the container, whereas it sounds like you want the opposite. 

The easiest way to achieve this is using the `Width(this IContainer element, float value, Unit unit = Unit.Point)` and `Height(this IContainer element, float value, Unit unit = Unit.Point)` functions, and then one of the `ImageScaling` enum values (such as `ImageScaling.FitArea`) on the `Image(this IContainer parent, byte[] imageData, ImageScaling scaling = ImageScaling.FitWidth)` call

**Comment by JSR33** [comment]
I did the following to try to set image height and width:

` public void Compose(IContainer container)
        {
            if (ImageElement is null)
                throw new NullComponentException("Image component is null or empty. If this element is not needed consider to delete it.");
           
            container.Image(GenerateImage);
            //container.Image(ImageElement.Image); //ImageElement.Image, ImageScaling.FitArea);
        }

        
        byte[] GenerateImage(Size size)
        {
            byte[] resizedImage;

            using (var ms = new MemoryStream(ImageElement.Image))
            {
                var image = Image.FromStream(ms);

                var ratioX = (double)150 / image.Width;
                var ratioY = (double)50 / image.Height;
                var ratio = Math.Min(ratioX, ratioY);

                var width = (int)(image.Width * ratio);
                var height = (int)(image.Height * ratio);

                var newImage = new Bitmap(width, height);
                Graphics.FromImage(newImage).DrawImage(image, 0, 0, width, height);
                Bitmap bmp = new Bitmap(newImage);

                ImageConverter converter = new ImageConverter();

                resizedImage = (byte[])converter.ConvertTo(bmp, typeof(byte[]));

            }
            return resizedImage;
        }`

The problem is that it will allways do a AreaFit to my image. Other thing that is not possible is to use the real images sizes because it will always fit it.

**Comment by MarcinZiabek** [comment]
Hello 😁 The library works like this on purpose. 

PDF docuements use points to describe size, where 72 points is 1 inch. Images use pixels to describe content. However, pixel does not have any meaningful size. Only when you specify DPI (dots per inch), it is possisble to translate how bix pixels are. Therefore, the library always scales the image, as determining image size based on its resolution just does not make sense.

To force the image to take a specified area, you can use many elements, simplest ones are Width and Height, e.g.:

```csharp
container
    .Width(1, Unit.Inch)
    .Image(ImageElement.Image)
```

Please notice that thank to the default image scaling settings, you do not need to use both Width and Height, as image aspect ratio is preserved.

**Comment by JSR33** [comment]
Thank you!

**Comment by XueDee123** [comment]
> Hello 😁 The library works like this on purpose.
> 
> PDF docuements use points to describe size, where 72 points is 1 inch. Images use pixels to describe content. However, pixel does not have any meaningful size. Only when you specify DPI (dots per inch), it is possisble to translate how bix pixels are. Therefore, the library always scales the image, as determining image size based on its resolution just does not make sense.
> 
> To force the image to take a specified area, you can use many elements, simplest ones are Width and Height, e.g.:
> 
> ```cs
> container
>     .Width(1, Unit.Inch)
>     .Image(ImageElement.Image)
> ```
> 
> Please notice that thank to the default image scaling settings, you do not need to use both Width and Height, as image aspect ratio is preserved.

Hello, what if I don't want to scale, for example I want the image to be 300 width and 100 height, what if I try to set the width and height directly, but the result is that the layout is abnormal

**Comment by MarcinZiabek** [comment]
@XueDee123 You can follow this code snippet that forces the image to entirely cover desired space:

```csharp
.Width(300)
.Height(100)
.Image(MyImage)
.FitUnproportionally();
```

**Comment by XueDee123** [comment]
> 您可以按照以下代码片段强制图像完全覆盖所需空间：
> 
> ```cs
> .Width(300)
> .Height(100)
> .Image(MyImage)
> .FitUnproportionally();
> ```

Thank you for your reply, this is indeed feasible, but it needs to constantly evaluate the size of the container, when the value setting is large, the layout will be abnormal, looking forward to a solution that can adapt to the size of the container and completely tile, and other several configurations can not fully occupy the container
