### ISSUE TITLE
Font size different per server

### ISSUE THREAD

**Issue by Remo** [QuestPDF/QuestPDF#132]
**Describe the bug**

I've got a simple code that generates a PDF. You can take any example you'd like. When I run it within my WSL, the font sizes are smaller, than when I run the code on an actual server. Both are running Ubuntu 18.04.

**To Reproduce**

I wish I could tell you, it just happens on some servers.

**Expected behavior**

Same font size on all servers

**Screenshots**

n/a

**Additional context**

I wouldn't mind analysing a few things myself, but I'm a bit lost. If anyone could just push me in the right direction? I've searched for DPI and similar things but couldn't find anything in this issue list that sounds like the problem I've got.

**Comment by MarcinZiabek** [comment]
Hello 😁 Let me ask an important question: `do you specify in your code a font name anywhere? Or do you rely on the default font?` I have found an issue in Skia FontManager that may cause the behaviour you are experiencing.

**Comment by Remo** [comment]
No, all default, just setting the font size and style.

**Comment by MarcinZiabek** [comment]
That's great 😁 As far as I understand, the SkiaSharp FontManager returns a default font when the font specified is not present, instead of throwing an exception about missing font. I am hoping to publish a new QuestPDF release today/tomorrow that should fix this issue.

**Comment by MarcinZiabek** [comment]
No, it will be a part of the 2022.3 release that I am working on right now 😁

**Comment by denizakkas** [comment]
Ah okay is there maybe already a workaround to fix this issues so that linux has the same behaivour then windows?

**Comment by MarcinZiabek** [comment]
I am sorry for this delay. The war at Ukraine is driving me crazy and I have a hard time with focusing at work. I am from Poland and this situation is something serious and 9already) impactful in my country.

My suggestion is to use a custom font loaded from a file. This way, you can make sure that the proper font is used. [Please take a look here](https://www.questpdf.com/documentation/patterns-and-practices.html#accessing-custom-fonts).

**Comment by MarcinZiabek** [comment]
Hello! I have just updated font management algorithm with the QuestPDF 2022.3 release. Can you please take a look?

**Comment by kir0riwal** [comment]
Hello Remo, 
Today (June-23-2022) I facing same issue while using QuestPDF (2022.6.2) version with Asp.Net core 5.0 C#.
This exception is thrown after code push in Docker Linux box.
Error = "**The typeface ''calibri" could not be found.**

So my question is how did you resolved this error ? plz share the details with font file loading and docker file changes if any .
Appreciate your quick response.

**Comment by Remo** [comment]
There are a bunch of solutions, check these links:

* https://github.com/QuestPDF/QuestPDF/issues/153#issuecomment-1129226166
* https://www.questpdf.com/documentation/patterns-and-practices.html#accessing-custom-fonts
* https://github.com/QuestPDF/QuestPDF/issues/153#issuecomment-1075316710

**Comment by kir0riwal** [comment]
Thanks for your response, one question here
As mentioned in patterns by Marcin - 

this ""LibreBarcode39-Regular.ttf"" , do I need to put in Bin folder in local computer before starting Docker Build ? 
or my question is where to place this file in application structure, so that using below command font manager could get it ?

// perform similar invocation only once, when the application starts or during its initialization step
FontManager.RegisterFont(File.OpenRead("LibreBarcode39-Regular.ttf")); // use file name
