### ISSUE TITLE
How to Support Unicode text 

### ISSUE THREAD

**Issue by chiranstha** [QuestPDF/QuestPDF#136]

**Comment by MarcinZiabek** [comment]
Hello 😁 I am currently working on the text shaping capability and unicode support. It should be available around version 2022.05. A next version after that will provide improved support for RTL (right to left).

**Comment by UserIsAmitHasan** [comment]
@MarcinZiabek QuestPDF is fantastic but lack of Unicode support is limiting. Thank you for your awesome work.

**Comment by nikolastojkovichtec** [comment]
@MarcinZiabek Hello, I am using the release 2022.6.3 and some unicode characters are working while some are not, for example ↑ character seems to work while ★ doesn't. Can you tell me if this is because of some current limitation in the package or is the problem on my end?

**Comment by MarcinZiabek** [comment]
The Unicode text is fully supported via the HarfBuzzSharp library. However, it is possible that the current font does not contain certain glyphs, e.g. emojis. I am considering adding font fallback functionality, however there are a couple of reasons against that idea. [Read more here](https://github.com/QuestPDF/QuestPDF/pull/187)

For now, you can manually send another font (designed for emojis) for this special character.

**Comment by MarcinZiabek** [comment]
The font fallback functionality has been added in the 2022.9 release. Closing

**Comment by UserIsAmitHasan** [comment]
@MarcinZiabek thank you very much. It's safe to say  QuestPDF is currently the best open source PDF library for .Net.
