### ISSUE TITLE
PDF quality

### ISSUE THREAD

**Issue by JSR33** [QuestPDF/QuestPDF#142]
Hi ,
There is a way to define the quality that I want to generate the document?
For example, if I have a "draft" mode in my application can I reduce the pdf quality?

**Comment by MarcinZiabek** [comment]
Hello 😁 Can you please elaborate more about this feature/requirement? I don't fully understand...

**Comment by JSR33** [comment]
Yes, although I cannot send you an example due to privacy I'll try to explain my problem.

So, I have a logo image with high resolution but when I generate the report it seams to lose quality. In this case the logo have a circle with black border and it looks like it's creating lines in the top, bottom and left side of the image. Something like this:

![imagem](https://user-images.githubusercontent.com/66378706/158395969-65db3191-98fa-40cc-be92-07512936c00c.png)

However If I zoom in the pdf those lines disappear.

From my side what I have is the following:

 ```
column
      .Item()
      .Background(Colors.White)
      .Height(100)
      .Row(row =>
      {
          row.RelativeColumn().AlignMiddle().PaddingLeft(25).PaddingRight(25).Text(text =>
          {
              //Something goes here
          });

          row.RelativeColumn().AlignRight()
              .AlignMiddle()
              .PaddingLeft(25)
              .PaddingRight(25)
              .Height(28)
              .Image(LogoImage, ImageScaling.FitHeight);
      });
```

**Comment by JSR33** [comment]
Well just forgot it!
I was using Adobe to open the pdf and in the meantime I remembered to test on edge and everything if fine.

Closed from my side. sorry.
