### ISSUE TITLE
FileName when document returned by byte array

### ISSUE THREAD

**Issue by ABIOLI-COM** [QuestPDF/QuestPDF#149]
Hi.  
I'm returning a PDF document by bytes through a web request, and I can see that the title that I set in the DocumentMetadata is shown correctly in my client PDF viewer.  
But, when I try to save, the name that appears in the dialog is some sort of random guid, that I couldn't find in the source code (I was trying to understand...).  
How can I set the filename, before sending it back to the client?  
Thanks in advance.  
AB

**Comment by MarcinZiabek** [comment]
Hello! This is a typical ASP question, nothing connected to QuestPDF. Please find below an example code in asp core:

```c#
[HttpGet]
public async Task<IActionResult> ReturnPdf()
{
    // generate your file
    return File(byteArray, "application/pdf", "myFileName.pdf");
}
```

**Comment by ABIOLI-COM** [comment]
Oh... shame on me! :-)
Thank you!
A
