### ISSUE TITLE
Error when copying invoice example docs not up to date with revisions.

### ISSUE THREAD

**Issue by davidbuckleyni** [QuestPDF/QuestPDF#150]
Documentation needs update to show new column method 
When copying from the example I get the following error

![image](https://user-images.githubusercontent.com/5619229/159138938-08d0154c-4945-4186-83c8-a33a1a1a8dd5.png)

**Comment by MarcinZiabek** [comment]
Hello 😁 Please let me know from where have you copied the code above? 

I found old code only [in this repository](https://github.com/QuestPDF/QuestPDF-ExampleInvoice), fixing it.

**Comment by davidbuckleyni** [comment]
Thats where i copied it from the repo. I class that as documentation lol sorry for miss understanding

**Comment by MarcinZiabek** [comment]
The official documentation can be found [here (getting started, API reference, patterns and practices, etc.)](https://www.questpdf.com/documentation/getting-started.html) 😁

**Comment by davidbuckleyni** [comment]
Yeah but sometimes us devs copy and paste from repos lol.

**Comment by MarcinZiabek** [comment]
Closing
