### ISSUE TITLE
Line break rule not correct for none-English language

### ISSUE THREAD

**Issue by wossig** [QuestPDF/QuestPDF#154]
**Describe the bug**
As the title says, line break does not work as expected
![image](https://user-images.githubusercontent.com/22833218/159517801-f01d28c2-5090-4f36-889e-0b1017d8dbd5.png)

The pic shows Chinese in PDF, but the break line rule is not expected?

The code snippet I used:
```csharp
table.Cell().ColumnSpan(6).Element(DefaultCellStyle).Text(ReplaceChinesePunctuation(company.Memo ?? String.Empty) + Environment.NewLine).LineHeight(1.8f).DefaultCellFormat();
```
```csharp
private IContainer DefaultCellStyle(IContainer container)
{
    return container
        .Border(0.5f)
        .BorderColor(Colors.Grey.Lighten1)
        .PaddingHorizontal(8)
        .PaddingVertical(4)
        .AlignLeft();
}

public static T DefaultCellFormat<T>(this T descriptor) where T : TextSpanDescriptor
{
    return descriptor.FontFamily(_defaultFontFamily);
}
```

**Expected behavior**
none-English language can show full line.

**Comment by MarcinZiabek** [comment]
Hi 😁 QuestPDF ignores the `/r` character and breaks line on the `/n` character.

Please let me know what is a default new line character on your system. So, we are interested in the value of `Environment.NewLine`.

**Comment by wossig** [comment]
It's sub-Linux system in win11

![image](https://user-images.githubusercontent.com/22833218/159604927-0d4dcf2f-aff8-434a-a63d-d7e087a642d7.png)

**Comment by MarcinZiabek** [comment]
`\n` should be plenty to enable line-breaking algorihtm. 

Please elaborate more about the issue. What is the result and what exactly is expected. Screenshots could help a lot. My knowledge about Chinese is close to zero and I need to help to understand the problem 😊 Thank you!

**Comment by MarcinZiabek** [comment]
How do you categorize your solution with the `ReplaceChinesePunctuation` method? Is it something I can consider adding to the library? Or is it just a hack?

Can you please elaborate more about text wraping in Chinese? I have no idea how this language works and this will help me improving the implementation. Are there wors that have more than one character/sign? What are we rules or wrapping? Etc.

**Comment by MarcinZiabek** [comment]
I have found [this Wikipedia article](https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages) regarding line breaking rules in Chinese. I am not sure how viable it is to cover all of this rules in next release. Howerver, according to this article, line breaking can happen on almost every character. As a first point of improvement, I will a special flag to enable this type of line breaking. Can you suggest best name for such TextStyle flag?

**Comment by wossig** [comment]
Thank you man @MarcinZiabek, I think ```TextStyle.EastAsian```  will be great.  Of course, another name also is great if present the meaning.
I'm sorry that I've no reply on the issue since I was busy on a corporate project the two days.

**Comment by wossig** [comment]
Most East Asian languages,  they all be impacted by the Chinese language in very hong history, the article you found is very good.

**Comment by MarcinZiabek** [comment]
In the April release, I am planning to introduce a simple algorithm that breaks text anywhere. This should cover most of the East Asian language use cases. In May, I am planning to reimplement the text rendering component: namely, introduce text shaping, take into account more advanced rules mentioned in the Wiki above, and hopefully add a text justification feature.

Again, I am very sorry for this inconvenience, I am learning about the craziness of text rendering along with the library development 😥

**Comment by wossig** [comment]
This issue should be fixed.
