### ISSUE TITLE
allow us to specify SKImage directly (i.e. make the method public)

### ISSUE THREAD

**Issue by schmitch** [QuestPDF/QuestPDF#156]
**Is your feature request related to a problem? Please describe.**
currently we generate images on the fly via skiasharp and wanted to use them in QuestPdf, however to do that we first need to convert the image as png or something and than use it. however this step is unnecessary since questpdf does use SKImage for images anyway.

our code at the moment:
```
var encoded = bitmap.Encode(SKEncodedImageFormat.Png, 100);
x.Item().Width(80).Image(encoded.ToArray());
```

**Describe the solution you'd like**
make: `private static void Image(this IContainer parent, SKImage image, ImageScaling scaling = ImageScaling.FitWidth)` publich

**Comment by MarcinZiabek** [comment]
Generally speaking, I am against exposing this API. I want to keep QuestPDF separated from SkiaSharp API as much as I can. 

However, please notice that there is better option available for you. QuestPDF offerts the `Canvas` element - the only API that exposes SkiaSharp dependency. You can use this element to render your image. However, you can adjust your implementation to draw content on the SkCanvas or SkPicture. This way, your image could be preserved as vector graphics, resulting with sharper image and smaller file.

[Canvas element documentation and examples](https://www.questpdf.com/documentation/api-reference.html#canvas)

**Comment by schmitch** [comment]
hm I need to take a look if it is possible to use the canvas element. at the moment we use `zxing.net` to generate datamatrix and barcode128 barcodes and the library itself has a skia backend, which gives us a SKBitmap back.

Sadly I'm not too much into graphics so I will probably need to take a look if the canvas element would be helpful.

**Comment by Bebo-Maker** [comment]
You should be able to use the canvas element as @MarcinZiabek pointed out. The SKCanvas can draw a `SKBitmap` directly.
```csharp
x.Item().Width(80).Canvas((c,s) => c.DrawBitmap(bitmap, 0, 0));
```
or for `SKImage`

```csharp
x.Item().Width(80).Canvas((c, s) => c.DrawImage(image, 0, 0));
```

**Comment by schmitch** [comment]
I will try this out and close the issue for now, (big) thank you!
