### ISSUE TITLE
Question: Alternating footer alignment based on page (even/odd).

### ISSUE THREAD

**Issue by pespinho** [QuestPDF/QuestPDF#164]
Hello,

Thank you for the awesome library.

I was wondering if there is a way to generate a footer which contains text that alternates its alignment depending on the number of the page where it is shown. For example:

```
Page 1 -> Text aligned right.
Page 2 -> Text aligned left.
Page 3 -> Text aligned right.
...
and so on...
```

I couldn't find a way to query in which page something is being rendered when composing the document. Is it possible somehow?

Thank you very much.

**Comment by MarcinZiabek** [comment]
Hello 😁 I am afraid that right now it is not possible. 

However, this week, I am planning to prepare an experimental release that should be very useful in this requirement. More details about the feature can be [found here](https://github.com/QuestPDF/QuestPDF/discussions/39). Please take a look and let me know what do you think. This is an advance use case and I am not sure how to shape the API. All feedback is always welcome 😁

**Comment by pespinho** [comment]
Hello MarcinZiabek,

I am so sorry that I didn't answer here before. I will take a look at it and give you feedback after.
Thank you for the great work.

**Comment by MarcinZiabek** [comment]
I have added [one more example to the documentation](http://localhost:8080/documentation/patterns-and-practices.html#footer-with-alternating-text-alignment) that covers your exact case 😁

**Comment by pespinho** [comment]
This is just the thing! Looks great. I'm going to close the issue. 😊

There is only one thing that I found a little strange, and that is the State property. 

I find it a bit strange that we have to implement one, even when it doesn't seem to be necessary. Would it perhaps be possible to have two interfaces? One IDynamicComponent<TState> and one IDynamicComponent? I don't really know how practical that would be, just food for thought.

Anyway... Thanks again for implementing a solution and for taking the trouble to write an example exactly for my use case! 😄
