### ISSUE TITLE
.net Framework 4.5

### ISSUE THREAD

**Issue by davidbuckleyni** [QuestPDF/QuestPDF#166]
I was wondering if their was any limitations that would not make this work under .net framework 4.5 unfortunate we cannot upgrade our ep application to match the 4.7.1 requirement of quest pdf?

**Comment by MarcinZiabek** [comment]
SkiaSharp requires at least [.NET Framework 4.6](https://www.nuget.org/packages/SkiaSharp/). As QuestPDF depends on SkiaSharp, it has the same requirements. I am afraid that I can not do much about it 😥

Please consider upgrading to .NET Framework 4.6. Are there any significant differences?
