### ISSUE TITLE
Test Document renders elements correctly

### ISSUE THREAD

**Issue by pablocom** [QuestPDF/QuestPDF#168]
Hey, we want to test that the PDF content is correctly generated from a given Document.

We've been trying to look on the byte array from an approved snapshot and comparing it to the actual content being generated from QuestPDF, but these bytes are differing depending on the OS that generates the document. 

Do you know a way to test that the Document is rendering with all the expected elements in it?

Thanks in advance

**Comment by MarcinZiabek** [comment]
Hello 😁

> Hey, we want to test that the PDF content is correctly generated from a given Document.

Have you ever had issues with document content stability? Especially something connected with the library?

> We've been trying to look on the byte array from an approved snapshot and comparing it to the actual content being generated from QuestPDF, but these bytes are differing depending on the OS that generates the document.

The PDF itself is generated by SkiaSharp. Most likely, somewhere there is a reason why outputs differ between OS versions. Something out of control for me.

> Do you know a way to test that the Document is rendering with all the expected elements in it?

QuestPDF can also output images. Maybe comparing them is viable? E.g. when 99% of the content is the same, then accept the output. You may create different comparing functions. I know that this technique is used for checking webpage rendering stability.

**Comment by pablocom** [comment]
> Have you ever had issues with document content stability? Especially something connected with the library?

The PDF generation is stable, no problem there.

About testing: if the snapshot from which we want assert the actual content was generated by the same OS that is running, contents are equivalent. If the snapshot was generated in another OS different than in which the test is running, it has a few differences comparing them by byte array.

> QuestPDF can also output images. Maybe comparing them is viable? E.g. when 99% of the content is the same, then accept the output. You may create different comparing functions. I know that this technique is used for checking webpage rendering stability.

We've tried to compare them via Images, but seems to be event more different between. We'll keep you posted on that

Thanks! :)

**Comment by MarcinZiabek** [comment]
What version of the library are you using? Are the output visually the same? Maybe different fonts are visible? In versions prior to 2022.3, QuestPDF relied on the default SkiaSharp mechanism. It used a default OS font if the specified one was not available. Right now, QuestPDF throws an exception in such case.

> It could be related with the text shaping engine that SkiaSharp is using under the hood?

QuestPDF does not utilize text shaping capability right now. However, placing text on the bitmap and rendering characters may indeed differ, for reasons unknown to me. I am afraid this may be out of control for us. If you find anything interesting, please share!

**Comment by pablocom** [comment]
> What version of the library are you using?

We are using Version 2022.3.1

> Are the output visually the same?

No, they have small differences in some character rendering, as well as wider/thinner spaces depending the OS

We decide to assert PDF generated content by using [PdfPig](https://uglytoad.github.io/PdfPig/) package, then ensuring texts are present in certain locations of the document. It's working fine like that: 

```csharp
using (PdfDocument document = PdfDocument.Open(@"C:\path\to\pdffile\file.pdf"))
{
    foreach (Page page in document.GetPages())
    {
        IReadOnlyList<Letter> letters = page.Letters;
        string example = string.Join(string.Empty, letters.Select(x => x.Value));

        IEnumerable<Word> words = page.GetWords();

        IEnumerable<IPdfImage> images = page.GetImages();
    }
}
```

Many thanks for your great job with this package and quick responses to this issue, really appreciated, keep on going :)
