### ISSUE TITLE
column fit-content

### ISSUE THREAD

**Issue by caposharp** [QuestPDF/QuestPDF#18]
Hi,

I'm trying to reproduce a report made with PDFMake, is there a way to do something like this with the library (see screenshot).

With a quick glance at the documentation, 

If i do something like this :

```
stack.Item().BorderBottom(1).BorderColor("CCC").Padding(5).Row(row =>
{
    row.RelativeColumn().Text("blabla");
    row.RelativeColumn().AlignRight().Text("1000000000000000000000000000000000000");
    row.RelativeColumn().AlignRight().Text("hello");
    row.RelativeColumn().AlignRight().Text($"test");
    row.RelativeColumn().AlignRight().Text($"test");
    row.RelativeColumn().AlignRight().Text($"test");
    row.RelativeColumn().AlignRight().Text($"test");
    row.RelativeColumn().AlignRight().Text($"test");
});
```

Each column will still be the same width and the column with the big number will be displayed on 2 lines.

I would like each column to take the necessary space according to the content. 
So in the example above, i would like the column with the big number to be super large so it can display the number on 1 line.

![image](https://user-images.githubusercontent.com/88843838/129223648-07668758-5fc6-4eb1-9743-05c0c94d97f9.png)

**Comment by MarcinZiabek** [comment]
Currently, there is no such functionality, meaning each column need to take a predefined width (either constant or relative). However, you can achieve very close results to your example PDF by using `row.ConstantColumn()` where you provide estimated width in points. This way you can adjust the width of each column to the expected content and achieve a dense layout. In your case, I assume that header text will determine the maximum column width. 

Please let me know if it does help.

**Comment by MarcinZiabek** [comment]
I was thinking about your request. It is possible to create `row.DynamicColumn()` that adapts to its content and scales depending on needs. The biggest trouble, that I see, is composing multiple rows in a stack to create a table. In such a case, every row is independent and therefore all dynamic columns will have various widths. As a result, the final table structure will be a mess.

Having a component that is deeply aware of its children is very difficult to implement, especially within the pageable context when available width may change and things need to be recalculated. Moreover, PDF documents are very static in comparison to the responsive nature of web pages. If I need to choose one, I would rather skip that functionality for both: reducing internal complexity and keeping elements easy to predict.

In your case, my approach will be as follows. For columns of well-known width (time, traffic, etc.) I would use the `row.ConstantColumn'. To make the details column scale and take remaining space, I would use the `row.RelativeColumn`.

Any discussion is always welcome :)

**Comment by MichelMichels** [comment]
I have a use-case for this issue that isn't just applicable to pure tables.

I'm trying to insert a right aligned set of key values under a dynamic title. I tried to make a bad representation of what I'm trying to achieve: 
![questpdf alignment](https://user-images.githubusercontent.com/6505319/157853579-8e9e4ceb-94ee-486e-8d39-4c4f0f4c56fb.png)

The red line is not really there, it's to show that the content under the title (the black rectangle) is right aligned. The title has a dynamic width.

I think this is not possible atm without manually using a ConstantItem with a static width defined.

**Comment by MarcinZiabek** [comment]
The `Row` element now supports the `AutoItem` that dynamically scales itself to the required size. It covers some use cases. However, it will not work for building tables as described by the original issue. At this moment, I still think that in terms of PDF document generation, it is best to explicitly define sizes whenever possible. This ensures layout stability 😁
