### ISSUE TITLE
How to solve the problem of exporting PDF garbled code in Chinese?

### ISSUE THREAD

**Issue by impPDX** [QuestPDF/QuestPDF#183]
How to solve the problem of exporting PDF garbled code in Chinese?
![QQ截图20220421172144](https://user-images.githubusercontent.com/50691694/164423609-739b489c-1f99-4ba1-9b92-0101655def34.png)
![QQ截图20220421172222](https://user-images.githubusercontent.com/50691694/164423705-9e6bf4b7-32cc-4358-80e2-dc4e20f0c0b6.png)

**Comment by impPDX** [comment]
FontManager.RegisterFontType("simsun", File.OpenRead($"{AppDomain.CurrentDomain.BaseDirectory}/simsun.ttc"));

This method has been enabled. How can I use it now

**Comment by Bebo-Maker** [comment]
I think your font does not include these chinese characters.

You need to explicitly specify a font that includes these chinese characters (e.g. MS Gothic) like this 
`.Text(...).FontFamily("MS Gothic)`.

If the specified font is not present on your system you should be able to register the font file with 
`FontManager.RegisterFont`.

**Comment by impPDX** [comment]
@Bebo-Maker thanks
