### ISSUE TITLE
The document has obvious errors

### ISSUE THREAD

**Issue by impPDX** [QuestPDF/QuestPDF#184]
public class InvoiceDocument : IDocument
{
    /* code omitted */

    void ComposeTable(IContainer container)
    {
        container.Table(table =>
        {
            // step 1
            table.ColumnsDefinition(columns =>
            {
                columns.ConstantColumn(25);
                columns.RelativeColumn(3);
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
            });
            
            // step 2
            table.DefaultTextStyle(x => x.SemiBold()).Header(header =>
            {
                header.Cell().Text("#");
                header.Cell().Text("Product");
                header.Cell().AlignRight().Text("Unit price");
                header.Cell().AlignRight().Text("Quantity");
                header.Cell().AlignRight().Text("Total");
                
                header.Cell().ColumnSpan(5)
                    .PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Black);
            });
            
            // step 3
            foreach (var item in Model.Items)
            {
                table.Cell().Element(CellStyle).Text(Model.Items.IndexOf(item) + 1);
                table.Cell().Element(CellStyle).Text(item.Name);
                table.Cell().Element(CellStyle).AlignRight().Text($"{item.Price}$");
                table.Cell().Element(CellStyle).AlignRight().Text(item.Quantity);
                table.Cell().Element(CellStyle).AlignRight().Text($"{item.Price * item.Quantity}$");
                
                static IContainer CellStyle(IContainer container)
                {
                    container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(5);
                }
            }
        });
    }

1.Table does not contain a defaulttextstyle method；
2.[        container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(5);]Didn't write return

**Comment by impPDX** [comment]
![image](https://user-images.githubusercontent.com/50691694/164589374-815b94b6-b8eb-4d6a-a159-df051c065868.png)

Should be questpdf.previewer

**Comment by MarcinZiabek** [comment]
Thank you for finding those issues!

> 1.Table does not contain a defaulttextstyle method；
> 2.[ container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(5);]Didn't write return

I agree with both. Might have done a mistake when updating existing documentation code. Would you like to prepare pull request to the documentation repository?

> Should be questpdf.previewer

This part of the documentation is correct. The package name is different from the terminal command. This is the official convention as far as I understand.

**Comment by impPDX** [comment]
@MarcinZiabek ok, thanks
