### ISSUE TITLE
RegisterFontType Obsolete

### ISSUE THREAD

**Issue by fredericoregateiro** [QuestPDF/QuestPDF#189]
**Describe the bug**
I'm migrating the code to the new latest version, that had some methods marked has obsolete, in a Xamarin.Forms project.

Register a font `FontManager.RegisterFont(fontstream);` and using the font like `TextStyle.Default.FontFamily("RobotoPT");` i get this error:
`The typeface 'RobotoPT' could not be found. Please consider the following options: 1) install the font on your operating system or execution environment. 2) load a font file specifically for QuestPDF usage via the QuestPDF.Drawing.FontManager.RegisterFontType(Stream fileContentStream) static method.'
`

If i don't register any font i get this error:
`The typeface 'Calibri' could not be found. Please consider the following options: 1) install the font on your operating system or execution environment. 2) load a font file specifically for QuestPDF usage via the QuestPDF.Drawing.FontManager.RegisterFontType(Stream fileContentStream) static method.'
`

This code works
```csharp
var assembly = typeof(App).GetTypeInfo().Assembly;
var fontstream = assembly.GetManifestResourceStream("Mobile.Font.Roboto-Regular-pt.ttf");

FontManager.RegisterFontType("RobotoPT", fontstream);

container
    .Page(p =>
    {
        p.DefaultTextStyle(TextStyle.Default.FontFamily("RobotoPT"));

        //
    });
```

I think I'm missing something, but i didn't found nething on the docs or the samples.

**Comment by MarcinZiabek** [comment]
Would you like to attach those font files to the issue?

**Comment by fredericoregateiro** [comment]
Yes, i'm using this one
[Roboto-Regular-pt.zip](https://github.com/QuestPDF/QuestPDF/files/8545206/Roboto-Regular-pt.zip)

**Comment by MarcinZiabek** [comment]
Thank you for sharing the font. The name of this font is `Roboto PT` (notice the space) - it is visible in the font previewer available in Windows. Please try to refer to this font by the proposed name 😁

P.S. I am very sorry for the delayed reply. A lot is going on in my personal life, very positive yet time-consuming events. I hope that you understand 😁

**Comment by fredericoregateiro** [comment]
The space 😄 sometimes it's the little things .
I'm using this font on other places, and i've exported the font like this 
`[assembly: ExportFont("Roboto-Regular-pt.ttf", Alias = "RobotoPT")]`
For some reason i thought it was using this too.

Thanks and congratulations
