### ISSUE TITLE
Chinese. Net development asks whether you will do the function of PDF to word and excel in the future

### ISSUE THREAD

**Issue by impPDX** [QuestPDF/QuestPDF#190]
Chinese. Net development asks whether you will do the function of PDF to word and excel in the future.

I think this should also be the concern of other regions。

Yesterday, I released videos and articles about questpdf in China, and everyone was amazed by the library

[https://www.bilibili.com/video/BV1mr4y1J75a?spm_id_from=333.999.0.0]

**Comment by MarcinZiabek** [comment]
> Chinese. Net development asks whether you will do the function of PDF to word and excel in the future.

I am not planning such functionality at this moment. Inter-format conversion is an area more suitable for an entire highly paid team. It is just too much for a single person.

> I think this should also be the concern of other regions。

In the nearest updates, I am planning to improve support of more advanced languages, including Chinese. This is just very complex and time consuming process.

I am also planning to rewrite documentation in different technology, most likely in the Docusourus library. I hope that other communities will help with the translation process. 

Do you have any other suggestions?

> Yesterday, I released videos and articles about questpdf in China, and everyone was amazed by the library

Thank you a lot! Sharing the library with other communities certainly help with making it more popular and finding more people willing to help 😁

P.S. I am very sorry for the delayed reply. A lot is going on in my personal life: highly positive yet time-consuming events. I hope that you understand 😁

**Comment by impPDX** [comment]
@MarcinZiabek I can help translate Chinese documents I'm basically proficient in using questpdf now. I think there may be some problems with your document layout. Can I translate Chinese documents according to my own understanding later?

**Comment by impPDX** [comment]
@MarcinZiabek  I didn't find your docusourus library

**Comment by MarcinZiabek** [comment]
> I think there may be some problems with your document layout. 

Please share more information about this problem. If there is anything wrong, I want to fix it! 🤣

> Can I translate Chinese documents according to my own understanding later?

Yes! Helping with translation is something that may help entire Chinese community. I really appreciate any help in this regard.

> I didn't find your docusourus library

Currently, the documentation is written in VuePress. However, over last year, the library and the documentation have grown a lot. Currently, I see the need to redesign its structure and provide more helpful examples. 

I was talking with Matthias Koch (from JetBrains) and he recommends using Docusaurus as more suitable alternative to VuePress. As far as I know, it is more extandable and simplifies the translation process.

This is tought! Having limited spare time, I need to decide between library features and documentation quality. And both are quite important. Maybe some day, the library receives proper funding and I would be able to dedicate more time 😁

**Comment by impPDX** [comment]
@MarcinZiabek  Hi, brother, what are the better c# technology blogs abroad? Is there a large c# technology article sharing platform

**Comment by MarcinZiabek** [comment]
I have no idea to be honest 😁 For many years already, I am relying mostly on developer conferences / podcasts (usually on YouTube) to be aware about new technologies. Then, I usually default to official documentation webpages.
