### ISSUE TITLE
Poor table algorithm peformance

### ISSUE THREAD

**Issue by jimkilliansentinel** [QuestPDF/QuestPDF#198]
I really like QuestPDF, thank you for the work! The [API doc page](https://www.questpdf.com/documentation/patterns-and-practices.html#document-metadata) shows DocumentMetadata, but doesn't show how to actually change the values from the default.

We sometimes have users who produce HUGE reports. A recent one included a table with so many rows it caused an out of memory exception while building row 333,286. I'll work on limiting that.

Regardless, we frequently need to produce PDFs with more than 250 pages. As shown on the API page, I've added this to my code:
`public DocumentMetadata GetMetadata() => DocumentMetadata.Default;`

But don't know how to change the `DocumentLayoutExceptionThreshold` value to a higher number. Nothing I've tried actually changes the value, even though there are no errors.

I've been a professional programmer for 30+ years, but only using C# for a little more than a year. This might be something that's obvious to people with more C# experience, so I apologize for needing help beyond the norm.

Thanks!

Jim

**Comment by MarcinZiabek** [comment]
Hello 😁 The `public DocumentMetadata GetMetadata() => DocumentMetadata.Default;` is just a shortcut. Instead of returning a library-default metadata configuration, you can easily instantiate your own `DocumentMetadata` object and return it from the `GetMetadata` method, e.g.:

```csharp
class MyDocument : IDocument
{
    public DocumentMetadata GetMetadata()
    {
        return new DocumentMetadata
        { 
             DocumentLayoutExceptionThreshold  = 1000
        };
    }

    // more code
}
```

> We sometimes have users who produce HUGE reports. A recent one included a table with so many rows it caused an out of memory exception while building row 333,286. I'll work on limiting that.

This is really impressive! I have stress tested table generation up to 2000 pages and the performance scales nearly linearly. Not sure about so many rows.

**Comment by jimkilliansentinel** [comment]
Thank you for the quick response!

I just tested it and was able to produce a PDF with 1307 pages from 33,960 rows of data. Took 94 seconds.

It was certainly my lack of C# experience that caused the problem. I tried several ways of doing the same thing you did, but none of them was right (obviously).

I'll probably be asked to try a really huge one, just to be sure it won't fail (something like 300K rows), but hopefully that won't happen often in real life.

We'll probably be using QuestPDF for the foreseeable future!

Jim

**Comment by MarcinZiabek** [comment]
1307 pages is obviously quite a lot. I have never created tests for even bigger documents. Therefore, it is hard to estimate where the OutOfMemory exception happens first: in QuestPDF code (by building document structure with Fluent API) or in SkiaSharp code (when rendering final PDF file). If QuestPDF implementation causes the issue, I think that the next release may help. Where you don't generate entire document layout at once, rather you can implement structure streaming. We will see. 

Please let me know how your tests go, I am happy to fix any performance limitations, especially if this improve experience of entire community.

**Comment by jimkilliansentinel** [comment]
Sorry for the confusion, I was unclear about that point: the out of memory error happened using iTextSharp, which is what prompted the search for a new solution and finding QuestPDF.

Here are my testing results:

	33,960 points - 1307 pages - 361 points/sec
	4/29/2022 8:55:16 AM: Thread_1 - CreatePDF time: 00:01:33.598

	50,000 points - 1924 pages - 282 points/sec
	4/29/2022 10:35:48 AM: async - CreatePDF time: 00:02:56.877

	75,000 points - 2885 pages - 189 points/sec
	4/29/2022 2:20:39 PM: async - CreatePDF time: 00:06:36.041

	100,000 points - 3847 pages - 142 points/sec
	4/29/2022 11:13:49 AM: async - CreatePDF time: 00:11:41.270

	150,000 points - 5770 pages - 93 points/sec
	4/29/2022 11:46:16 AM: async - CreatePDF time: 00:26:45.958

	300,000 points - 11540 pages - 46 points/sec
	4/29/2022 1:41:22 PM: async - CreatePDF time: 01:47:46.394

I was quite surprised by the time required as the number of points (rows) grew. Each one slowed significantly. The data in each test is just multiples of the same rows in the initial test, so it's not due to different values.

Here's the code for the report:

```
        public void Compose(IDocumentContainer container)
        {
            container
                .Page(page =>
                {
                    page.Size(QuestPDF.Helpers.PageSizes.Letter.Landscape());
                    page.Margin(40);

                    page.Header().Element(ComposeHeader);
                    page.Content().Element(ComposeContent);


                    page.Footer().AlignLeft().Text(x =>
                    {
                        x.Span("Page ");
                        x.CurrentPageNumber();
                        x.Span(" of ");
                        x.TotalPages();
                    });
                });
        }

        void ComposeHeader(IContainer container)
        {
            var printStyle = TextStyle.Default.FontSize(9).FontFamily("Times New Roman");
            container.Row(row =>
            {
                row.ConstantItem(216).Height(36).Image("logo.png", ImageScaling.FitHeight);

                row.RelativeItem().AlignCenter().AlignMiddle().Text($"Report Time: {ReportTime}").Style(printStyle);
            });
        }

       void ComposeContent(IContainer container)
        {
            container
                .AlignTop()
                .Column(column =>
                {
                    //column.Item().Height(72).Image("logo.png", ImageScaling.FitHeight);
                    column.Item().LineHorizontal(1);
                    column.Item().Text(text =>
                    {
                        text.Span(Title).FontFamily(QuestPDF.Helpers.Fonts.TimesNewRoman).FontSize(16);
                        text.AlignCenter();
                    });
                    column.Item().ShowIf(!string.IsNullOrEmpty(Participant)).Text(text =>
                    {
                        text.Span("Participant: " + Participant).FontFamily(QuestPDF.Helpers.Fonts.TimesNewRoman);
                        text.AlignCenter();
                    });
                    column.Item().Text(text =>
                    {
                        text.Span("Time Interval: " + TimeInterval).FontFamily(QuestPDF.Helpers.Fonts.TimesNewRoman);
                        text.AlignCenter();
                    });
                    column.Item().LineHorizontal(1);
                    column.Item().Text(" ");
                    column.Item().Element(ComposeTable);
                });
        }
 
        void ComposeTable(IContainer container)
        {
            container
                .Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        foreach (var x in ColumnWidths)
                        {
                            columns.ConstantColumn(x, Unit.Inch);
                        }
                    });

                    table.Header(header =>
                    {
                        foreach (var x in ColumnLabels)
                        {
                            header.Cell().Border(0.5f).Padding(2).Text(x).FontFamily(QuestPDF.Helpers.Fonts.Arial).FontSize(11);
                        }
                    });

                    foreach (var row in Data)
                    {
                        foreach (var c in ColumnFields) 
                        {
                            table.Cell().Border(0.5f).Padding(2)
                                 .Text(row.GetValueString(c, row)).FontFamily(QuestPDF.Helpers.Fonts.TimesNewRoman).FontSize(10);
                        }
                    }
                });
        }

```

`Data` is a `List<StopsPointsReportData>`, so nothing special.

Regardless of the time issue, at least it completed successfully! We don't expect a report over 100K points to happen often. I don't have data from iTextSharp to compare it to.

If you have any suggestions about making the report more efficient, I'd be greatly appreciative, but the process seems pretty obvious to me. 

Jim

**Comment by jimkilliansentinel** [comment]
Actually just found an example from iTextSharp:

```
190,571 points - 2540 points/sec
4/1/2022 1:07:29 PM: Thread_1 - CreatePDF time: 00:01:14.854
```

Same report, different data (this was actual production data). QuestPDF makes a better looking report, but is much slower. Still, it doesn't fail on the reports that are bigger than this, where iTextSharp did fail.

**Comment by MarcinZiabek** [comment]
I have improved the table generation algorithm. A couple of numbers from my test:
- 250k rows, 10 columns,
- over 12k pages,
- generation time: around 2 minutes.

I think, it is pretty acceptable, and scales linearly. This improvement will be available in next release.

![image](https://user-images.githubusercontent.com/9263853/167026918-3a7c728a-89cb-44b9-b0ce-ae21b620bba3.png)

**Comment by jimkilliansentinel** [comment]
More than acceptable, it's fabulous! 150K rows took 26 minutes for me, so this is perfect. I imagine everyone else will be happy about it too.

Thanks again!

Jim

**Comment by MarcinZiabek** [comment]
Thanks 😁 My hope is to release the new version before Monday next week.

**Comment by jimkilliansentinel** [comment]
I was just able to redo my earlier testing and here are the results:

```
	50,000 points - 1924 pages - 847 points/sec
	5/9/2022 9:47:11 AM: async - CreatePDF time: 00:00:58.506
	
	75,000 points - 2885 pages - 806 points/sec
	5/9/2022 9:35:53 AM: async - CreatePDF time: 00:01:32.578

	100,000 points - 3847 pages - 892 points/sec
	5/9/2022 9:50:58 AM: async - CreatePDF time: 00:01:52.233
	
	150,000 points - 5770 pages - 882 points/sec
	5/9/2022 9:55:22 AM: async - CreatePDF time: 00:02:50.160
	
	300,000 points - 11540 pages - 879 points/sec
	5/9/2022 10:02:23 AM: async - CreatePDF time: 00:05:40.929
```
The slowest was more than twice the speed of v5's fastest and 19 times faster than the slowest. Did you learn to do magic?

This is a ***drastic*** improvement! Thank you so much!

**Comment by jimkilliansentinel** [comment]
Yes, it's while I'm debugging, but it was when testing iTextSharp too, so the comparison should be OK. I can understand you wanting to match their speed, but it's not an issue for us.

Our users won't be upset over waiting 5 minutes for a 300K-point report. They wouldn't get a report at all if we were still using iTextSharp! And, again, even the report with 190K points is an unusual occurrence.

Most of the time required when creating our reports is reverse-geocoding the points into addresses. We use Google and Geocodio in different circumstances, and Google took over an hour to process the data for the 190K-point report (they actually only needed to process about 17K points). Tacking on 5 minutes to generate a report that looks nicer than the old version isn't going to be a problem.

**Comment by MarcinZiabek** [comment]
> Yes, it's while I'm debugging, but it was when testing iTextSharp too, so the comparison should be OK. I can understand you wanting to match their speed, but it's not an issue for us.

Of course I would love to match their speed 😁 Making QuestPDF faster is something that everyone can benefit from.

> Most of the time required when creating our reports is reverse-geocoding the points into addresses. We use Google and Geocodio in different circumstances, and Google took over an hour to process the data for the 190K-point report (they actually only needed to process about 17K points). Tacking on 5 minutes to generate a report that looks nicer than the old version isn't going to be a problem.

That's true. I expect that collecting data to display on the report may still take significantly more time. So there is no practical reason to fight for every millisecond.

Either way, have fun with the library! I am glad that it is useful for you 😁 If you think it is worth, please consider talking with your management regarding sponsoring QuestPDF. This is a great option to promote your company, building industry position or even finding skilled developers. The company logo with clickable link and description will be visible on the repository homepage, basically accessible for everyone. Just a thought of course, no pressure.
