### ISSUE TITLE
How to make column elements paged?

### ISSUE THREAD

**Issue by swordream** [QuestPDF/QuestPDF#204]
The document says:
By default, all column elements should fit on a single page. Otherwise, the entire content is be wrapped to the next page.

My question is: Is there a way to  make column elments fit on multiple page?

**Comment by MarcinZiabek** [comment]
> By default, all column elements should fit on a single page. Otherwise, the entire content is be wrapped to the next page.

Apparently this is a very old description that is no longer correct. I will remove it from the documentation to avoid any future confusion. I am sorry for this inconvinience.

> My question is: Is there a way to make column elments fit on multiple page?

The `Column` element already behaves as you expect!

P.S. I am very sorry for replying so late. There is just a lot of going on in my personal life, very positive yet time-consuming events. I hope tha you understand 😁

**Comment by swordream** [comment]
Yeah! I tested it,thanks!
