### ISSUE TITLE
Superscript functionality released yet?

### ISSUE THREAD

**Issue by dprice** [QuestPDF/QuestPDF#205]
First off - such an amazing project. The code and documentation is top-notch - kudos. The JetBrains webinar really showed off so much! 

I need superscript for a current project and noticed there was a pull-request that looked like it was accepted:
https://github.com/QuestPDF/QuestPDF/pull/179

Is this in the 2022.4.1 release?

Thanks again for the awesome repo!

**Comment by MarcinZiabek** [comment]
> First off - such an amazing project. The code and documentation is top-notch - kudos. The JetBrains webinar really showed off so much!

Thank you! It is always great to hear positive feedback, nothing better to give some motivation to other person 😁

> I need superscript for a current project and noticed there was a pull-request that looked like it was accepted:
> https://github.com/QuestPDF/QuestPDF/pull/179
> 
> Is this in the 2022.4.1 release?

@dprice It is not release yet. I am planning to merge it into main this week and release new version early next week. A lot is going on in my personal life, very positive yet time-consuming events. I hope that you understand the delay 😥

**Comment by dprice** [comment]
Personal life always comes first - take your time! Thanks again :)
