### ISSUE TITLE
Dynamic header/footer based on page content

### ISSUE THREAD

**Issue by wbittlehsl** [QuestPDF/QuestPDF#215]
I'm generating a large document (100+ pages).  The document is produced by iterating over a data set that's 3 levels deep:
```
+ "Vehicles"
    + "Cars"
        + "Ford"
        + "Fiat"
    + "Vans"
+ "Lodging"
    + "Airbnb"
        + "Houses"
        + "Condos"
... and so on
```
For every page in this document, I want the header and footer to show the name of the top level section that the page contains.  For example, let's say that the "Vehicle" section spans pages 3-8.  I want to show "Vehicles" in the header and footer of pages 3-8.  Similarly, if "Lodging" spans pages 9-12, then I want "Lodging" to show in the header and footer.

That's what I'm looking for at a minimum.  In general though, it would be really nice to be able to query the content of the current page and determine what to show based on that content.

Is any of this possible?  And if so, how would I go about doing something like this?

**Comment by MarcinZiabek** [comment]
1) For each category, you can generate separate document section. Call the Page method multiple times, in each put desired content and custom header. [Details](https://www.questpdf.com/documentation/patterns-and-practices.html#page-settings)

2) Or you can use [the Decoriation element](https://www.questpdf.com/documentation/api-reference.html#decoration) that repeats content before and after its primary content.

**Comment by wbittlehsl** [comment]
@MarcinZiabek Thanks, that's what I ended up doing, just generate a page for each section and set the header then.
