### ISSUE TITLE
Could not load file or assembly 'SkiaSharp' or one of its dependencies. Strong name signature could not be verified.

### ISSUE THREAD

**Issue by djhvscf** [QuestPDF/QuestPDF#216]
**Describe the bug**
When installing QuestPDF 2022.5.0 it also installs the SkiaSharp package. But when running the .NET Framework 4.8 web application it shows this error: Could not load file or assembly 'SkiaSharp' or one of its dependencies. Strong name signature could not be verified.

**To Reproduce**
Add the package to the project and then run it.

**Expected behavior**
To be able to run it.

**Screenshots**
![image](https://user-images.githubusercontent.com/4496763/168942356-b5958ee0-9e60-4c78-9575-30c2d1317c16.png)

**Additional context**
ASP.NET MVC application running with .NET Framework 4.8

**Comment by djhvscf** [comment]
Nvm, see this as reference: https://github.com/mono/SkiaSharp/issues/1767

**Comment by MarcinZiabek** [comment]
Since the 2022.12 version, QuestPDF uses the SkiaSharp 2.88.x version. This should resolve the problem with incorrectly signed dependency. Closing
