### ISSUE TITLE
ArgumentNullException when processing some images - From SkiaSharp library

### ISSUE THREAD

**Issue by cropper1991** [QuestPDF/QuestPDF#217]
**Describe the bug**
Unable to render or process certain images when using a MemoryStream. Results in an ArgumentNullException within the SkiaSharp library (will add more detailed stack trace tomorrow)

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'buffer') at SkiaSharp.SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size) at SkiaSharp.SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)

**To Reproduce**
Unfortunately at this stage, I do not have a minimalistic code example but based on my initial research seems to be derived from the use of streams when creating the images

**Expected behavior**
Should not crash or have an exception raised within the SkiaSharp library and render the image correctly and successfully

**Screenshots**

**Additional context**
I appreciate this is rather sketchy in the detail, but I wanted to get this down initially in case you had some thoughts on this. We have a product which is due to go into production for 1st June so I really need this issue to be resolved or a workaround found.

I've had a look at the SkiaSharp repository issues list and found a few that may be related to this:
https://github.com/mono/SkiaSharp/issues/1745
https://github.com/mono/SkiaSharp/issues/1621

From preview version, but the issue stack trace is same or similar
https://github.com/mono/SkiaSharp/issues/1551

Is there any way the workarounds described in these issue tickets to be implemented? Or a possibility of dropping the library version requirement to a minimum of 2.80.2? I will gladly provide as much detail as I can, but this is in an environment whereby debugging this issue is tricky and will take me some time to track down the cause or the offending image.

**Comment by mark-hopper** [comment]
Please disregard this, it was an issue with some internal image processing I'm doing with SkiaSharp

**Comment by MarcinZiabek** [comment]
That's great. Closing then 😁
