### ISSUE TITLE
Table text and line breaking 

### ISSUE THREAD

**Issue by GvinPin47** [QuestPDF/QuestPDF#230]
Is there ability to line break long text to separate table row? 
Or some workaround for such behavior, cause there is a need for BottomBorder. 

for e.x:
text: "LongFooTextLongFooTextLongFooText..."

Row -> [ <ins>LongFooTextLongFooTextLongFooText</ins> ]
Row -> [ <ins>LongFooTextLongFooTextLongFooText</ins>]
Row -> [ <ins>LongFooTextLong</ins> ]

**Comment by GvinPin47** [comment]
I can't find smth similar to this logic in current lib, therefore it was decided to split string into separate lines by space and limit its length to a certain number of characters suitable for my pdf file format and then create a row for each element of the list.

I know that is not best solution and it must be suitable for text length too, but for now it's ok.

**Comment by MarcinZiabek** [comment]
The 2022.6 release should better handle this corner case. When there is a word longer than available space, it is split to wrapper to multiple lines. Would you like to make a try? 😁
