### ISSUE TITLE
Syntax error  in Getting Started - Data Source Layer documentation

### ISSUE THREAD

**Issue by OEbcampbell** [QuestPDF/QuestPDF#233]
This is a great project - thank you for leading it. 

The Data Source Layer section currently states:
Firstly, in the data source class, you can define all necessary business logic. Simple operations can be placed inside the template layer (discussed in the next chapter) but more complex calculations should be kept here or inappropriate services. This way you prevent business logic leakage from your domains.

However, I believe that the intent of this passage is supposed to mean "kept in appropriate services" and not "inappropriate services".

**Comment by MarcinZiabek** [comment]
Thank you! Fixed 😁
