### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by auladinamica** [QuestPDF/QuestPDF#238]
### Discussed in https://github.com/QuestPDF/QuestPDF/discussions/237

<div type='discussions-op-text'>

<sup>Originally posted by **auladinamica** May 31, 2022</sup>
hi guys This my problem

Excepción producida: 'System.IO.FileLoadException' en QuestPDF.dll
Excepción no controlada del tipo 'System.IO.FileLoadException' en QuestPDF.dll
No se puede cargar el archivo o ensamblado 'SkiaSharp, Version=2.88.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)

can somebody help me ?

</div>

**Comment by rtynski** [comment]
You probably need to add the library to the main project. (Because you only added to your library).
