### ISSUE TITLE
How to merge multiple PDFs and Add watermark

### ISSUE THREAD

**Issue by kevincwj2008** [QuestPDF/QuestPDF#244]
similar iTextSharp，I am currently using QuestPDF，But I need to merge PDF and add watermark，Is there any method available now?
thanks

**Comment by girlpunk** [comment]
Merging or otherwise editing existing PDFs is not currently possible with this library (#113).

Watermarks can be added using the layer function, such as in the [example given in the documentation](https://www.questpdf.com/documentation/api-reference.html#layers).

**Comment by kevincwj2008** [comment]
Thank you for your reply!

**Comment by kevincwj2008** [comment]
> Merging or otherwise editing existing PDFs is not currently possible with this library (#113).
> 
> Watermarks can be added using the layer function, such as in the [example given in the documentation](https://www.questpdf.com/documentation/api-reference.html#layers).



> Merging or otherwise editing existing PDFs is not currently possible with this library (#113).
> 
> Watermarks can be added using the layer function, such as in the [example given in the documentation](https://www.questpdf.com/documentation/api-reference.html#layers).

Thank you for your reply!
