### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by aclimarin** [QuestPDF/QuestPDF#25]
**Align the text so it will be straight in both left and right margin of the document**
Is there a way to justify the text by adjusting the space between words so it would be justified?

**Comment by MarcinZiabek** [comment]
Hi, text justification is not available at the moment. Unless there is higher demand, I am not planning to work on it in the nearest future. It adds a lot of complexity, corner cases and may reduce performance.

**Comment by aclimarin** [comment]
I know that via css would be something like this:

 ```
text-align: justify;
 text-justify: inter-word;
```

**Comment by aclimarin** [comment]
Is there a way to insert a custom style?

**Comment by MarcinZiabek** [comment]
Hi, QuestPDF uses its own layouting engine and does not rely on HTML or CSS. Therefore, it is not possible to inject any custom CSS styles as mentioned in your question.

**Comment by MarcinZiabek** [comment]
@Bebo-Maker created an interesting prototype for this feature. It is also added to the current roadmap. As the requirement is pretty simple, there is no really much to discuss. Closing 😁
