### ISSUE TITLE
[Bug] Unicode text shaping capability breaks when paragraph starts with English text

### ISSUE THREAD

**Issue by UserIsAmitHasan** [QuestPDF/QuestPDF#260]
**Describe the bug**
Unicode text shaping capability breaks when paragraph starts with English but does not when English text is in the middle of paragraph.

**To Reproduce**
.Text("English text at the start of a paragraph breaks the Unicode text shaping capability. বিপদ আরও বাড়াচ্ছে টানা বৃষ্টি। গতকাল শনিবারও অবিরাম বৃষ্টি আর পাহাড়ি ঢল অব্যাহত ছিল। প্রায় সব ধরনের যোগাযোগ বিচ্ছিন্ন হয়ে পড়া সিলেট ও সুনামগঞ্জের বন্যা পরিস্থিতি সামাল দিতে হিমশিম খাচ্ছে স্থানীয় প্রশাসন।");

.Text("বিপদ আরও বাড়াচ্ছে টানা বৃষ্টি। English text in the middle does not break the Unicode text shaping capability. গতকাল শনিবারও অবিরাম বৃষ্টি আর পাহাড়ি ঢল অব্যাহত ছিল। প্রায় সব ধরনের যোগাযোগ বিচ্ছিন্ন হয়ে পড়া সিলেট ও সুনামগঞ্জের বন্যা পরিস্থিতি সামাল দিতে হিমশিম খাচ্ছে স্থানীয় প্রশাসন।");

**Expected behavior**
Screenshot shows correct behaviour.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/41125642/174469207-328a13d2-9137-4251-95cb-c46b09fc1303.png)

**Additional context**
Language I am testing with is Bengali.
[Font Used: Kalpurush](https://www.omicronlab.com/download/fonts/kalpurush.ttf)

**Comment by MarcinZiabek** [comment]
Thank you for investigating this case! I am not an expert in this domain. I have tried to analyse your example as much as I could. I don't see any problems there. Would you like to double check and elaborate more about the current output and what is expected?

The text shaping capability is performed mostly by the HarfBuzz library so I have high confidence that the result should be correct. 😁

**Comment by khaledhosny** [comment]
The text needs to itemized before passing to HarfBuzz into runs with the same direction, script, and language. It seems that the whole text is passed to HarfBuzz as one item and the first script in the text is used (perhaps by using `hb_buffer_guess_segment_properties()`).

**Comment by MarcinZiabek** [comment]
As far as I know, HarfBuzz is capable of detecting the text direction automatically. E.g. Arabic is going to be classified as right-to-left but numbers in-between will be left-to-right. Please share more information, why you think that the current output is not right 😁

**Comment by khaledhosny** [comment]
How are using HarfBuzz, are you calling the C API directly or through some wrapper? HarfBuzz does not handle BiDi the way you describe.

**Comment by khaledhosny** [comment]
Youczn compare the individual words after the Latin text in the screenshot, it is the same text and the words are coming up differently.

**Comment by UserIsAmitHasan** [comment]
@MarcinZiabek  To reproduce please take a look this [Repository:QuestPdf.Issue.260](https://github.com/UserIsAmitHasan/QuestPdf.Issue.260). 

[Output PDF](https://github.com/QuestPDF/QuestPDF/files/8973252/1cb3c2902e684f7c872a4161edc1cabe.pdf)

It seems putting ASCII text first makes HarfBuzz to interpret the whole text as ASCII. Putting English and Bengali text in two different span solves the problem but it is not an ideal solution.

**Comment by girlpunk** [comment]
Looking at the original screenshot you posted, am I right in thinking these two would be examples of incorrect formatting?

![image](https://user-images.githubusercontent.com/161093/175537593-2a27570f-06cf-42c4-99f0-a375155a3cef.png)

**Comment by UserIsAmitHasan** [comment]
This issues is fixed in latest release.  Thank you @MarcinZiabek .
