### ISSUE TITLE
Text wrapping over multiple pages duplicates the last character on the second page

### ISSUE THREAD

**Issue by girlpunk** [QuestPDF/QuestPDF#271]
**Describe the bug**
When a `Text` element spans multiple pages, the last character shown on the first page is also on the second page. This appears to have started in 2022.6.0, and is repeatable with text in the root page container, tables, and columns.

**To Reproduce**
```csharp
private class TestDocument : IDocument
{
    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container) =>
        container.Page(
            page =>
            {
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(ReportConstants.BodyText);
                page.MarginLeft(ReportConstants.LeftMargin);
                page.MarginRight(ReportConstants.RightMargin);
                page.MarginTop(ReportConstants.TopMargin);
                page.MarginBottom(ReportConstants.BottomMargin);

                page.Content().Text(
                    static text =>
                    {
                        text.ParagraphSpacing(ReportConstants.BigStackSpacing);
                        text.Line("Replace this with some long text, which will fill up a page. Lorem ipsum dolor sit amet...");

                        text.Line("This is a very long block of text, which will run over multiple pages.");
                        text.Span("Lorem ipsum dolor sit amet...");
                    }
                );
            }
        );
}
```

**Expected behaviour**
The character should not appear on the second page.

**Screenshots**
2022.5.0:
![image](https://user-images.githubusercontent.com/161093/176412636-b6fd22aa-5be1-405d-8db3-0729c43ced85.png)

2022.6.0-prerelease and up, including 2022.6.2:
![image](https://user-images.githubusercontent.com/161093/176414195-f4ed9222-df2e-48db-bd50-e7b625d83677.png)

**Comment by MarcinZiabek** [comment]
This bug is fixed in the 2022.6.3 release. Please try it 😁 Thank you so much for finding it!
