### ISSUE TITLE
Font weight not working

### ISSUE THREAD

**Issue by amaleszewski** [QuestPDF/QuestPDF#282]
**Describe the bug**
Hello Marcin, at first I want to say thank you for the excellent library! The Fluent way of writing the layout is really great and I achieve what I wanted in just a few hours. Documentation is also really great!

I'm working on macOS Monterey and a class library in which I have whole logic to create PDFs is written in .NET 6. The case is following - every font is always at normal weight. I cannot change font for Bold/SemiBold/Medium etc. - of course I have written it in the code, but this is not reflected at the final document. 

**To Reproduce**
Just add an .Bold() / .SemiBold() etc. to the Text item and see result.

Packages which I have installed in my class library:

```
<PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="2.8.2.1-preview.79" />
<PackageReference Include="QuestPDF" Version="2022.6.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.1-preview.79" />
```

**Expected behavior**
I expect that fonts which have .Bold() / .SemiBold() etc. will be rendered with that weight on final PDF document.

**Screenshots**

Here is a code from my component to create Vendor details, the **Title** parameter is just **Vendor** text.

```
public void Compose(IContainer container)
    {
        container.ShowEntire().Column(column =>
        {
            column.Spacing(2);

            column.Item().Text(Title).Bold();
            column.Item().Text(Address.CompanyName);
            column.Item().Text(Address.Address);
            column.Item().Text(Address.Country);
            column.Item().Text(Address.RegistryNumber);
        });
    }
```

And here is outcome:

![image](https://user-images.githubusercontent.com/22931942/178951616-fa6c27dd-074d-4c72-9d9f-c02099061c94.png)

**Additional context**
On desired environment we have K8s cluster with Linux container, so I will check if it's only my local environment problem, but it will be great if I will have 1:1 design on local env and on desired envs.

**Comment by amaleszewski** [comment]
When I deployed it on the server, I got an `System.ArgumentException: The typeface 'Calibri' could not be found.` exception, so I added the fonts and I'm loading it when my singleton service for PDF generating is creating and now I have all weights, so problem solved :)

**Comment by MSroczynski3** [comment]
Solving this issue would really help our company, too.
