### ISSUE TITLE
Text is not displaying (.NET Core running on 64bit Amazon Linux)

### ISSUE THREAD

**Issue by m-azim** [QuestPDF/QuestPDF#285]
I have developed an application in .NET Core(5), I am using **QuestPDF (2022.2.6)**. Generated PDF is working fine on my local machine (**Windows 11**), but when I deploy this application on **.NET Core running on 64bit Amazon Linux**, It is not working. All the text is not displaying. 

Note: I am using **SkiaSharp.NativeAssets.Linux.NoDependencies** for Linux support. Image is also rendered properly. 

**Local environment** 
![t1](https://user-images.githubusercontent.com/49408144/179627342-0c51073b-789e-4638-bf53-bea0a4680f1d.png)

**.NET Core running on 64bit Amazon Linux environment**  Yellow marked, There is no text
![t3](https://user-images.githubusercontent.com/49408144/179628240-04129d0b-edf1-4ea1-91ff-7409f80a7f61.png)

Here is my code block 
`container.Row(row =>
{ 
 row.RelativeItem().Column(column =>
     {
          column.Item().Text("SKIN SCAN RESULTS", TextStyle.Default.Size(20).SemiBold().Color("#0DD0D9"));
     });
if (!string.IsNullOrEmpty(Model.ClientLogo))
                {
                    row.RelativeItem().AlignRight().Height(35).PaddingBottom(5).Image(GetImage(Model.ClientLogo), ImageScaling.FitHeight);
                }});
`

Is there anything I missed in my reference ?

**Comment by blogcraft** [comment]
For development try using WSL so you can catch Linux related problems in development. 

Also, beside `SkiaSharp.NativeAssets.Linux.NoDependencies` try adding `HarfBuzzSharp.NativeAssets.Linux` to the project. I use QuestPDF in linux also without problems.

**Comment by blogcraft** [comment]
Mhh.... 🤔
I also use .NET 6 instead of 5.

Try testing without adding any `TextStyle` inside the Text method. I usually create a separate `TextStyle` Object and then apply it using the `DefaultTextStyle(myTextStyleObject)` method.

**Comment by m-azim** [comment]
This actually seems the problem of font, In **QuestPDF (2022.2.6)** version, I don't find the way to define the **FontFamily** of text as latest version has.

I have upgrade my application and use the latest version of QuestPDF, and use below code 
`FontManager.RegisterFont(File.OpenRead("Roboto-Regular.ttf"));`

`page.DefaultTextStyle(x=> x.FontFamily("Roboto")); // this is important`

Its working now.

**Comment by m-azim** [comment]
I am closing this issue.
