### ISSUE TITLE
Bring image to front

### ISSUE THREAD

**Issue by JSR33** [QuestPDF/QuestPDF#286]
**Question**
I'm using a table where I'm translating an image in X axis -15.
Problem: The image is bellow the border. How can I bring that image to be in front of border?

**Comment by Bebo-Maker** [comment]
I hope i understood your request correctly.
I think the `Layer` element can help here. Try something like this:
```csharp
container.Layers(l =>
{
    l.Layer()
     .BorderColor(Colors.Red.Accent4)
     .Border(10);

    l.PrimaryLayer()
     .TranslateY(15)
     .Image("YourImage");
});
```

Result looks something like this:
![image](https://user-images.githubusercontent.com/53836821/180271606-1c536b25-03eb-446f-a3c0-5b6fd3cf46a7.png)

**Comment by JSR33** [comment]
I already used layers for other scenarios but how to use it inside the table? (I'm not able to upload images I'll try to show you 1 cell of my table)

     _______________
     |                     |
IMAGE                |
     |______________|

**Comment by JSR33** [comment]
After some experiments I am finally able to do it with layers :)

`table.Cell().Row(rowNumber).Column(columnNumber).Layers(l =>
                {
                    l.Layer()
                        .BorderLeft((float)0.5)
                        .BorderColor(Colors.Black);
                        

                    l.PrimaryLayer()
                        .AlignMiddle()
                        .TranslateX(-10)
                        .Text(text =>
                        {
                            text.Element().Height(20).Width(20).Image(Placeholders.Image);
                        });
                });`
