### ISSUE TITLE
[Question] Does this work in Unity

### ISSUE THREAD

**Issue by craftercis** [QuestPDF/QuestPDF#287]
Hello!

I would like to use this in Unity. But when I install QuestPDF with a tool named NuGetForUnity I get this error:
![image](https://user-images.githubusercontent.com/24845278/180078236-39ff2ea4-af55-4fb0-973e-70a91103c3f3.png)

Can someone help me with this?

**Comment by nextechar-hardik** [comment]
Even i am getting same error while creating .dll from source and add in unity 

Is there any solution ??
