### ISSUE TITLE
duplicate characters appear on the previous page and the next page

### ISSUE THREAD

**Issue by kevincwj2008** [QuestPDF/QuestPDF#291]
duplicate characters appear on the previous page and the next page，use chinese.
![image](https://user-images.githubusercontent.com/21054385/180350272-55dff42d-1946-4aaf-b033-033718dd96c1.png)

How can I fix this problem？
thanks

**Comment by MarcinZiabek** [comment]
Hello 😁 This bug is fixed in the QuestPDF 2022.6.3 release. Can you please try it?

**Comment by kevincwj2008** [comment]
> 

This bus has been fixed，thank you very much for your open source.
