### ISSUE TITLE
DocumentLayoutException: 'Composed layout generates infinite document.' is thrown when number of invoice detail items is 4967 or over in 'example-invoice' repository

### ISSUE THREAD

**Issue by preiius** [QuestPDF/QuestPDF#30]
I'm talking about line 14 in InvoiceDocumentDataSource.cs:

`.Range(1, 25)`

* Pdf is generated when count is < 4967.
* Exception is thrown when count is >= 4967
* Exception is thrown intermittently when count is 4967, at least once out of 5 tries

Only change I made is to update QuestPDF to version 2021.10.1. I'm running visual studio 2019.

As you alluded to in **Under consideration**, it's difficult to debug without the generated document.

Thank you for writing this awesome library.

**Comment by MarcinZiabek** [comment]
This is tricky to decide. I expect/suppose that most users will generate relatively short documents. When this exception happens, the library literally needs to generate so many pages, using processor and memory resources. Therefore, if I set this value really high (let's say 10000 pages), it will be just wasteful. 

What about adding a more sophisticated exception message? That describes both cases and let the developer know how to deal with them? E.g. to increase the threshold?
