### ISSUE TITLE
[Question] Handling varied languages in input string 

### ISSUE THREAD

**Issue by harvinders** [QuestPDF/QuestPDF#300]
**Describe the bug**
Our app has a feature to generate a pdf file, and before the user generates a pdf file, they can also add comments to the pdf file through the humble [`TextBox`](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.UI.Xaml.Controls.TextBox?view=windows-app-sdk-1.1). `TextBox` allows users to input their comments in any language. However, if I understand correctly we can only specify a single font when we create a text element in the quest pdf. This means 
- we need to somehow find out which font to use based on the input text, (detect language) and 
- if the input text has multiple languages, we would have to identify every character and convert the string into multiple text elements with correct fonts
Just wondering if the community has a known solution to this problem.

This [PR-187](https://github.com/QuestPDF/QuestPDF/pull/187) looked very promising, is there any chance it would be merged. If not, is there a way we can incorporate the code in our apps without making changes to the core library? @Bebo-Maker @MarcinZiabek

**Comment by girlpunk** [comment]
Would an easier solution not be to use or otherwise build a font that contains all characters you might need?

**Comment by harvinders** [comment]
Closed by #341
