### ISSUE TITLE
ITF 14 Barcode generation

### ISSUE THREAD

**Issue by hblaise** [QuestPDF/QuestPDF#305]
We started using Quest PDF instead of the old tools we used for a new reporting service but we ran into an issue where we need to generate ITF 14 Barcodes. Sadly currently, I do not see a way to do that with Quest PDF which possibly means we have to go back to using our old tools. It would be nice if this was possible with Quest PDF.

**Comment by hblaise** [comment]
> We also had a barcode requirement, ended up using this barcode library: [https://github.com/barnhill/barcodelib](url) as it has loads of barcode types & allows image access to the barcode result.
> 
> In code it was as simple as `BarcodeLib.Barcode barcode = new BarcodeLib.Barcode();` `barcode.Encode(BarcodeLib.TYPE.CODE39, "*6NB52TMA*", 300/*width*/, 40/*height*/);`
> 
> `table.Cell().Column(3).Image(barcode.GetImageData(BarcodeLib.SaveTypes.BMP), ImageScaling.FitArea);`

Thank you very much for taking the time to reply to me, I really appreciate it. In the meantime, I found a free ITF 14 font (https://grandzebu.net/informatique/codbar-en/code25I.htm), and with a bit of messing around, I made the example c# code work, and now it converts the strings to the required format to generate the barcode according to the standard. So far it seems to work but this lib will be very useful in the future also, thank you!

**Comment by MarcinZiabek** [comment]
Using a custom font may work too (and is vector-based): https://www.questpdf.com/going-production/font-management.html

**Comment by hblaise** [comment]
> Using a custom font may work too (and is vector-based): https://www.questpdf.com/going-production/font-management.html

That is what I ended up doing, the problem is that it is really hard to find and use a proper and freely available ITF 14 (Code 2 of 5 Interleaved) barcode font. In this regard, it would be nice to have built-in support for all kinds of barcodes in Quest PDF but I understand that this might not be a priority at this time. I appreciate all the hard work that went into creating Quest PDF and I hope to see this feature in it at some point in the future.
