### ISSUE TITLE
QuestPDF's goal is create pdf，not edit or more?

### ISSUE THREAD

**Issue by MiyamuraMiyako** [QuestPDF/QuestPDF#307]
**Is your feature request related to a problem? Please describe.**
PDF edit is a very important feature.

**Comment by MarcinZiabek** [comment]
Yes, that is correct. Right now, the primary focus is on generating PDF files. I am considering adding edit capability in the future. The reason is simple, this is my personal, spare-time project. I need to limit the scope, to be able to offer possibly best quality 😁

**Comment by MiyamuraMiyako** [comment]
@MarcinZiabek Thank you so much for creating such a good program! 😁😁
