### ISSUE TITLE
Table page break on complete row

### ISSUE THREAD

**Issue by miki-bgd** [QuestPDF/QuestPDF#313]
Hello, first to say i have recently using this library, and so far it is great! Easy to understand and easy to use :) 

I have small issue, have tried example for creating a table from api-reference https://www.questpdf.com/api-reference/table.html  , and created 'logical' row (which is actually made of 4 actual rows - there are 2 columns and i create 8 cells).

Is it possible to prevent page break to happen in the middle of my 'logical' row? Like, if it can't fit, move it to next page?

PS. Additional question, table header is displayed on every page - can this behavior be changed? I need it only on first one.

Thanks,
Miki

**Comment by Bebo-Maker** [comment]
1. To prevent paging check [here](https://www.questpdf.com/api-reference/show-entire.html)

2. To display elements only once check [here](https://www.questpdf.com/api-reference/show-once.html)

**Comment by miki-bgd** [comment]
@Bebo-Maker 
Thank you!

It is helpful, but i still have problems with table cell, because i am not sure to which ShowEntire should be applied.
Here example: I just add 6 cells, and with column definition (2 columns), they are arranged like this
____
cell cell
cell cell
cell cell
____
How can i apply ShowEntire() to all of them? Should i wrap them somehow?
(I tried to add 1 cell and use RowSpan(3)  with ShowEntire, but no luck)

Here some sample code i'm using:
```

container.Table(table=>
{
    table.ColumnsDefinition(columns=>
    {
        columns.RelativeColumn();
        columns.RelativeColumn();
    });

    foreach(...)
    {
        table.Cell()...
        table.Cell()...
        table.Cell()...
        table.Cell()...
        table.Cell()...
        table.Cell()...
    }
}
```

**Comment by Bebo-Maker** [comment]
You can always nest content as deep as you like. You need to apply `ShowEntire` to a container which contains all your cells. 

Modifying your structure like this should work:
```csharp
container.Column(c => //Column to place elements vertically, which was previously handled by the `Table` you used.
{
  foreach(...)
  {
    c.Item()
     .ShowEntire() //Prevent paging of your inner 'table'
     .Table(t => //Table is now generated for every item, so you can prevent paging for the entire item.
   {
      t.ColumnsDefinition(columns=>
      {
        columns.RelativeColumn();
        columns.RelativeColumn();
      });

      t.Cell()...
      t.Cell()...
      t.Cell()...
      t.Cell()...
      t.Cell()...
      t.Cell()...
   });
  }
});
```

**Comment by miki-bgd** [comment]
Great, thank you for your help!
