### ISSUE TITLE
Set default font family

### ISSUE THREAD

**Issue by 499978920** [QuestPDF/QuestPDF#314]
I'm in china, use chinese, lato not support 

I want set global default font family to Source Han Sans/思源黑体

``` 
FontManager.RegisterFont
container.FontFamily("Libre Barcode 39")
```
still need set each container

if we can set global default font family once effect all containers, that will be great

**Comment by Ammar441** [comment]
inside page you can use like this 

container.Page(page =>
{
    page.DefaultTextStyle(x =>x.FontFamily("Times New Roman"));

   //others code
});

**Comment by MarcinZiabek** [comment]
The `DefaultTextStyle` approach is a correct one. However, it does have a bug in 2022.8 release. I am hoping to release the update very soon 😁

**Comment by 499978920** [comment]
> inside page you can use like this
> 
> container.Page(page => { page.DefaultTextStyle(x =>x.FontFamily("Times New Roman"));
> 
> //others code });

yes. but still need set each page :(

**Comment by MarcinZiabek** [comment]
@499978920 How many times do you call the `.Page()` method? Please tell me more about your usecase.

I think, better name would be `.PageGroup()` as one invocation can easily generate dozens or even hundreds of pages. 

Please note, that to split document content, you can also use one `.Page()` invocation, and then use inside the `.PageBreak()` element.

**Comment by 499978920** [comment]
> The `DefaultTextStyle` approach is a correct one. However, it does have a bug in 2022.8 release. I am hoping to release the update very soon 😁

The 'DefaultTextStyle' look like ' default text style template'. Change it will return a new instance. It that correct?

**Comment by MarcinZiabek** [comment]
The `DefaultTextStyle` element applies additional text style properties to all its descendants. It is important that children can override that setting. [Read more](https://www.questpdf.com/api-reference/default-text-style.html)
