### ISSUE TITLE
.SkipOnce() is not working correctly.

### ISSUE THREAD

**Issue by realboubli** [QuestPDF/QuestPDF#323]
**Describe the bug**
the .SkipOnce() and probably the .ShowOnce() methods doesn't work as expected. Tried many times, never understood the way they work.

**To Reproduce**
[Just copy this exact code from the docs and render it with the previewer.](https://www.questpdf.com/examples/custom-first-page.html)

**Expected behavior**
Should have a blue rectangle on the first page and green ones on the next pages, like in the docs example.

**Screenshots**
The result I get:
![image](https://user-images.githubusercontent.com/49991411/185784936-f57d4809-0c20-4b06-9ee1-ba9a57a2ec5f.png)

**Additional context**
I use QuestPDF version 2022.8.1

**Comment by realboubli** [comment]
Downgrading to QuestPDF version 2022.8 seems to fix the bug. I will stay on this version for now.

**Comment by MarcinZiabek** [comment]
This bug has been fixed in 2022.8.2 😁 Please confirm that it is working as expected.

**Comment by realboubli** [comment]
It's working thanks! I think you just made a typo on the new version 😅 
![image](https://user-images.githubusercontent.com/49991411/185792267-d148c22a-713d-445e-9f9e-ca0cf7bf8009.png)

**Comment by MarcinZiabek** [comment]
Oops, I need to reupload this nuget with corrected name 😂 Thanks for noticing!
