### ISSUE TITLE
Korean Language Support

### ISSUE THREAD

**Issue by santoshmandal97788** [QuestPDF/QuestPDF#331]
**Korean Language not Supported**

text.Span("역 이름")
 .FontSize(20);

![image](https://user-images.githubusercontent.com/78499012/188363887-f38eb6b3-fe31-40b7-8d04-0f0bcd967580.png)

**Comment by girlpunk** [comment]
Have you specified a font that includes Korean characters?

**Comment by santoshmandal97788** [comment]
Issue solved need to specify font family in project
