### ISSUE TITLE
Ambiguous invocation error when following the Getting started guide

### ISSUE THREAD

**Issue by matt-clegg** [QuestPDF/QuestPDF#333]
**Describe the bug**
When following the Getting started guide (specifically this section: https://www.questpdf.com/getting-started.html#header-implementation) and reach the part where you create `ComposeHeader` and `ComposeContent` methods, the `page.Header().Element(ComposeHeader)` and `page.Header().Element(ComposeContent)` calls are erroring with the following:

`
Ambiguous invocation: QuestPDF.Infrastructure.IContainer Element<IContainer>(this QuestPDF.Infrastructure.IContainer, System.Func<QuestPDF.Infrastructure.IContainer,QuestPDF.Infrastructure.IContainer>) (in class ElementExtensions) void Element<IContainer>(this QuestPDF.Infrastructure.IContainer, System.Action<QuestPDF.Infrastructure.IContainer>) (in class ElementExtensions) match.
`

I copied the code directly from the docs site and it still errors. The ComposeHeader and ComposeContent methods both return void and both include an IContainer parameter argument, so I'm not sure how it's confusing it with a method that returns an IContainer.

**To Reproduce**
Create a class that implements `IDocument` and follow the getting started page, up until the Header implementation section.

**Expected behavior**
No errors when calling `page.Header().Element(ComposeHeader)` and `page.Header().Element(ComposeContent)`

**Screenshots**
![image](https://user-images.githubusercontent.com/34515355/188648964-b5a8c2ed-8422-43ef-a446-853eeae68ccd.png)
![image](https://user-images.githubusercontent.com/34515355/188649980-1e2a8f55-9a3a-4da5-b7bb-031cf03796ef.png)

**Additional context**
QuestPDF version: 2022.6.2
JetBrains Rider 2022.2.2
.NET Framework 4.7.2

**Comment by MarcinZiabek** [comment]
Hi 😁 Is it possible that you have copied the `ComposeContent` or `ComposeHeader` methods twice? Possibly with different content?

Would you like to compare your code with the working repository? https://github.com/QuestPDF/QuestPDF-ExampleInvoice

**Comment by matt-clegg** [comment]
Nope, I've only got one of each method in the class. 

This is what my class looks like: https://gist.github.com/matt-clegg/d2960772ab4166b10ac0880e07329141 

I commented out a few lines to do with the model, but it's essentially the same as the example invoice document. It seems that all lines that call a `ComposeFoo` method are complaining about the ambiguous invocation.

I think this issue is related to the dotnet version. I'm working on an ASP MVC project using .NET Framework 4.7.2. I copied the code from my gist into an empty .net6.0 project and the ambiguous invocation errors seem to be fixed.

**Comment by MarcinZiabek** [comment]
I copied your code into a newly created project, everything works. I have used the same QuestPDF version, .NET Framework 4.7.2 and also latest release of Rider. Maybe your IDE has some stale cache?

**Comment by matt-clegg** [comment]
I've fixed the issue! The C# language version was set to C# latest major (default), I switched it to C# 7.3 and the error has gone. Thanks for the help.

![image](https://user-images.githubusercontent.com/34515355/188824943-5669dbb9-0ca9-4714-9bb6-f7a3026676a6.png)
