### ISSUE TITLE
Can't find DynamicImage

### ISSUE THREAD

**Issue by Xwilarg** [QuestPDF/QuestPDF#340]
Hey,

I was looking at the documentation of Images and I wanted to try DynamicImage: https://www.questpdf.com/api-reference/image.html#dynamic-images

However when I'm trying to use it the way I would use an image (on the example above) Visual Studio doesn't find it, am I missing something?

**Comment by Bebo-Maker** [comment]
Looks like there is a mistake in the documentation, its just called .Image()

[Source](https://github.com/QuestPDF/QuestPDF/blob/3ba09ea8265516ce40a30e99882d08bdbda00a7b/QuestPDF/Fluent/ImageExtensions.cs#L59)

**Comment by Xwilarg** [comment]
Indeed that solve my issue, thanks

**Comment by MarcinZiabek** [comment]
@Bebo-Maker Thank you for help.

Updated documentation in https://github.com/QuestPDF/QuestPDF-Documentation/commit/90a4fd011610cf86b5b8a00ee6fa4247c71b298d
