### ISSUE TITLE
How can I read a document?

### ISSUE THREAD

**Issue by M-Allan2** [QuestPDF/QuestPDF#355]
I want to generate image from pdf. I can do that if I construct the pdf using QuestPdf, but I don't know how to do that if the PDF is already created. So is there a way to read the pdf and generate image?

**Comment by girlpunk** [comment]
QuestPDF unfortunately does not support opening or modifying existing PDFs.

You may be able to achieve this using [PdfPig](https://uglytoad.github.io/PdfPig/) instead?

**Comment by M-Allan2** [comment]
Thanks for the reply and help, unfortunately PdfPig can't convert a page to image

**Comment by MichelMichels** [comment]
> Thanks for the reply and help, unfortunately PdfPig can't convert a page to image

You should look into PDFiumSharp

**Comment by MarcinZiabek** [comment]
As we are not planning to introduce the PDF parsing functionality any time soon, I decided to close this issue.
