### ISSUE TITLE
CheckIfAllTextGlyphsAreAvailable and Fallback break hyperlinks

### ISSUE THREAD

**Issue by Relorer** [QuestPDF/QuestPDF#361]
**Describe the bug**
When the flag CheckIfAllTextGlyphsAreAvailable is enabled, text hyperlinks stop working

**To Reproduce**

1. Enable the flag CheckIfAllTextGlyphsAreAvailable 
2. Use [hyperlink for text](https://www.questpdf.com/api-reference/text#hyperlink)

**Expected behavior**
At least, I would like to have a warning about this behavior in the documentation.

**Additional context**
```
QuestPDF.Settings.CheckIfAllTextGlyphsAreAvailable = true;

var document = Document.Create(container =>
{
    container.Page(page =>
    {
        page.Content()
            .Text(text =>
            {
                text.Hyperlink("Please visit QuestPDF website", "https://www.questpdf.com");
            });
    });
});

document.ShowInPreviewer();
document.GeneratePdf("hello.pdf");
```

**Addition**
Fallback also breaks these hyperlinks
```
.Text(text =>
{
    text.Hyperlink("Please visit QuestPDF website", "https://www.questpdf.com")
        .Fallback(y => y.FontFamily("MS Reference Sans Serif"));
});
```

**Comment by MarcinZiabek** [comment]
Thank you for finding this issue 😁 Working on the fix.

**Comment by MarcinZiabek** [comment]
Fixed in: https://github.com/QuestPDF/QuestPDF/commit/ec31c9b063593a07fccd9690faceaccd2b8dceba Will be released soon
