### ISSUE TITLE
The generated document won't render correctly in Edge or SumatraPDF. 

### ISSUE THREAD

**Issue by mimoguz** [QuestPDF/QuestPDF#368]
**Describe the bug**
The generated pdf is rendered only partially in<sup>(1)</sup> MS Edge and SumatraPDF. It's rendered correctly in Firefox, and can be imported by Affinity Designer without any problems.

**To Reproduce**
I have a git repo, it's no way minimal though: [GitHub repo](https://github.com/mimoguz/QPdf-Report)

**Expected behavior**
The resulting document to be rendered correctly by different viewers.

**Screenshots**

Firefox:
![firefox](https://user-images.githubusercontent.com/7283047/194759344-0a07e2ef-0876-4641-af31-84a77792a888.png)

Edge:
![edge](https://user-images.githubusercontent.com/7283047/194759365-925010e4-7e95-4e2f-9669-c89ce3a45d8f.png)

**Additional context**
The project uses lots of svg images, drawn on a canvas with the help of Svg.Skia package. Replacing svg images with pngs seem to solve the issue, at the cost of considerably increased file size. Still, it's interesting that the document still works in Firefox.

(1) On? At? Sorry, English is not my first language.

**Comment by mimoguz** [comment]
At the end, I think this may not be a problem on the QuestPDF side of the mix. Sorry.

**Comment by MarcinZiabek** [comment]
@mimoguz What are your thoughs about this issue? I haven't been able to investigate your problem yet.

Btw, your report looks stunning, I love its design!

**Comment by mimoguz** [comment]
Maybe the canvas element don't mix well with heavy(ish) paths, but Firefox's svg/pdf renderer is just more resilient? What's interesting is that the issue breaks not just svgs, it breaks almost everything.

> Btw, your report looks stunning, I love its design!

It's not even its final form! 😁 Thanks.

**Comment by MarcinZiabek** [comment]
Would you like to share the PDF file? I can try to open it on my environment.

Also, you can try to upgrade the SkiaSharp library to latest (it will break Previewer) - just as an experiment.

**Comment by mimoguz** [comment]
> Would you like to share the PDF file? I can try to open it on my environment.

Sure: [link](https://1drv.ms/b/s!Ahsda0rPt-lgnvNRSqJ4cFBHy-6A6w?e=emendM)

> Also, you can try to upgrade the SkiaSharp library to latest (it will break Previewer) - just as an experiment.

I've simplified the design a lot and settled on using pngs for now. But I will try that if I find some time. I couldn't make Previewer work anyway.

**Comment by MarcinZiabek** [comment]
All of my webbrowsers (Edge/Chrome/Opera) are displaying the PDF incorrectly (as on your screenshot). Futhermore, my Ryzen R9 5950X is not particularly happy about it either, all browsers are lagging a lot.

What approach are you using for SVG? Maybe there is one SVG that makes the rendering that slow / not working?

**Comment by MarcinZiabek** [comment]
What is the size of the SVG files? Is there any text? Is text exported as curves?

**Comment by mimoguz** [comment]
> What is the size of the SVG files?

The biggest one was 59,038 bytes.

> Is there any text? 

In two of them.

> Is text exported as curves?

Yes.

Here is all of them: [link](https://1drv.ms/u/s!Ahsda0rPt-lgnvNSakaCeplAEryrsA?e=XW65SN)

**Comment by girlpunk** [comment]
Notably, the PDF does display in Adobe Reader (which suggests this isn't an issue with corrupt or invalid output), but not in Foxit reader.

A ~60k SVG is rather large, I wonder if the rendering engines in the respective browsers have limits on the number of shapes or similar they will try to render?
