### ISSUE TITLE
Table Header not repeated on multiple pages.

### ISSUE THREAD

**Issue by vanwinkelseppe** [QuestPDF/QuestPDF#370]
**Describe the bug**
Table not repeating headers if spans multiple pages. It will show the header color but no text will appear.

**To Reproduce**
Used the example: https://www.questpdf.com/api-reference/table#table-header-footer. (v2020.09)
`
.Page(page =>{
                page.Size(PageSizes.A6.Landscape());
                page.Content().Element(ComposeExample);
});`

**Expected behavior**
Header text to be repeated on next page.

**Screenshots**
![image](https://user-images.githubusercontent.com/9077926/195016420-9705bc74-d6d2-403a-8b25-3dc1dc24025b.png)

**Comment by MarcinZiabek** [comment]
Hello 😁 Fortunatelly, this is only an issue in the example code. I have pushed new version, would you like to try it and confirm that it is working as expected?

Change: moved the `ShowOnce()` invocation, now it is applied only to content cells.

**Comment by vanwinkelseppe** [comment]
Great! Thanks! Missed that `ShowOnce()`
