### ISSUE TITLE
Create a IDocumentAsync Interface 

### ISSUE THREAD

**Issue by Rafael94** [QuestPDF/QuestPDF#373]
**Is your feature request related to a problem? Please describe.**
I would like to run a data query (Ef .Core) in Compose. But this is not easily possible because the function is Sync. 

**Describe the solution you'd like**
An interface `IDocumentAsync` could be implemented with `Task ComposeAsync(IDocumentContainer container)`. For generating the PDFs the extensions `GeneratePdfAync(...)` could be used. 

**Additional context**
I would like to run the database query in Compose so I don't have to go through the list twice.

**Comment by MarcinZiabek** [comment]
I strongly advice against combining persisency layer access with document generation. 

A much cleaner solution would be to separate logic into multiple layers:
1) Document-related models.
2) Persistency layer logic - code that performs EF calls and projects database entities into target models.
3) Document layout code with QuestPDF.

Depending on the project complexity, some parts can be of course simplified. General idea is described in [the Getting Started article](https://www.questpdf.com/getting-started).

**Comment by Rafael94** [comment]
Thank you for the answer. I am closing the issue because of this.
