### ISSUE TITLE
Incorrect Version Number Uploaded to NuGet

### ISSUE THREAD

**Issue by girlpunk** [QuestPDF/QuestPDF#381]
**Describe the bug**
Version `2022.8.2` was uploaded to NuGet as `2202.8.2`, this causes Visual Studio and other tools to incorrectly assume this is the latest version, rather than offering an upgrade to `2022.9.1`.

**Screenshots**
![image](https://user-images.githubusercontent.com/161093/197152278-6d1ce561-34d5-41ae-8915-31f978b128e7.png)

**Comment by MarcinZiabek** [comment]
Thank you for noticing this issue 😁

This is strange as I alreadyd specifically set that particular package to "Unlisted". This was enough to make it dissapear in both: nuget website and in Rider. Just to make sure, I just deprecated the `2202.8.2` version.

Would you like try again?

**Comment by girlpunk** [comment]
Might have been something cached on my end then, I've explicitly removed 2022.8.2 from my end and it looks ok now.

**Comment by ArnautS** [comment]
Just installed this package for the first time, and this version still shows up as latest stable for me, even though it's marked as deprecated

![image](https://user-images.githubusercontent.com/44735497/234229107-0045c20a-2ff0-42b5-8598-423bce824ac8.png)
