### ISSUE TITLE
Draw linear gradient

### ISSUE THREAD

**Issue by meron1122** [QuestPDF/QuestPDF#383]
I would like to use linear gradient as background for Document/Component.
Is any way to achieve this?

**Comment by MarcinZiabek** [comment]
The following links should help:

Drawing content behind or in front of the main document: https://www.questpdf.com/api-reference/page#watermark-slots
Drawing content behind or in front of any content: https://www.questpdf.com/api-reference/layers
Drawing custom graphics (e.g. gradients) with SkiaSharp: https://www.questpdf.com/api-reference/canvas

**Comment by meron1122** [comment]
Canvas looks exactly what i need.
Thank you, good job!
