### ISSUE TITLE
[Question]: Letter spacing

### ISSUE THREAD

**Issue by lorenzogiudici5** [QuestPDF/QuestPDF#393]
Hi, is it possible to set letter-spacing for a Text?
Thanks!

![image](https://user-images.githubusercontent.com/8243275/199669570-0101a0d6-2c43-4a03-a039-7a43b1bd8f2d.png)

**Comment by Bebo-Maker** [comment]
Not possible currently, but i think it would be pretty straight forward to implement this.
We can add an option for letter spacing in `TextStyle` and handle the spacing in the [`TextShaper` implementation](https://github.com/QuestPDF/QuestPDF/blob/main/QuestPDF/Drawing/TextShaper.cs).

**Comment by Bebo-Maker** [comment]
@lorenzogiudici5 Just implemented this in #398. Let me know what you think.

**Comment by lorenzogiudici5** [comment]
Yeah @Bebo-Maker, I think it's ok! Thank you!
