### ISSUE TITLE
.ShowInPreviewer(); method not available

### ISSUE THREAD

**Issue by Eduard-Nuco** [QuestPDF/QuestPDF#404]
**The Bug**
.ShowInPreviewer(); method is not available in the document builder, so cannot use the previewer.

**To Reproduce**
Not sure how to reproduce the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/102159214/200495809-e95214c1-4ba7-4556-8420-090ab5a449dc.png)
![image](https://user-images.githubusercontent.com/102159214/200495141-d7698788-a42b-471e-91a5-28741bf37f62.png)
![image](https://user-images.githubusercontent.com/102159214/200495186-953d40e3-52ac-4130-93d9-20131582bda0.png)

**Additional context**
Windows 11
Microsoft Visual Studio Community 2022 (64-bit), Version 17.2.6
QuestPDF version 2022.11.0.0
QuestPDF Previewer version 2022.11 (installed as per "https://www.questpdf.com/document-previewer"
Application Target Framework: .NET Framework 4.8
Output Type: Windows Application

**Comment by MarcinZiabek** [comment]
This API is available only in dotnet 6 and beyond. The hot-reload API was introduced in dotnet 6. It allows the Previewer application to listen to changes and update preview in real-time. 

Technically, I can add the `ShowInPreviewer` method to all dotnet platforms, but for environments under dotnet 6 the hot-reload capability will just not work, requiring to recompile the code after each change. The proper message can be displayed somewhere to indicate this type of limitations. What do you think?

**Comment by Eduard-Nuco** [comment]
Are there any limitations for using QuestPDF on .NET Framework 4.8 vs .NET 6 (with the exception of hot-reload)?

I would like to future-proof our application by ensuring we use the newest technologies, and also switching from WPF to WinUI 3.

I understand the hot-reload feature and how it applies in this scenario, but maybe adding it more (maybe not all) .NET platforms it can help speed up development, especially in the prototyping stages. Like you said, if you maybe added a message to indicate these limitations then that would also help future users who could run into issues like this.

**Comment by MarcinZiabek** [comment]
No, there are no other limitations 😁

> I understand the hot-reload feature and how it applies in this scenario, but maybe adding it more (maybe not all) .NET platforms it can help speed up development, especially in the prototyping stages. Like you said, if you maybe added a message to indicate these limitations then that would also help future users who could run into issues like this.

This is mentioned [in the documentation](https://www.questpdf.com/document-previewer#introduction). I will investigate how to provide this information in a more discoverable way.

**Comment by Eduard-Nuco** [comment]
Okay thanks, I will take a look at upgrading to .NET 6.

I really love this tool. We will using it for our registration process for auctions, and it will be a big help.

Is there any possibility we can send you an example of our form and you could provide us with the C# code layout?

**Comment by MarcinZiabek** [comment]
I am afraid that right now, I have too little spare time to be able to help on the per-project basis. Please take a look at the Getting Started tutorial. It is a great indrocution to the 3-layer design that decouples persistency layer, models with business logic layer and finally visualization layer where QuestPDF truly is.

That being said, I am planning to introduce a paid support starting next year. I hope this will allow me to focus more on the project, for the benefit of entire community 😁
