### ISSUE TITLE
.ShowInPreviewer hangs application, does not show document in previewer

### ISSUE THREAD

**Issue by Eduard-Nuco** [QuestPDF/QuestPDF#415]
**Describe the bug**
.ShowInPreviewer() method hangs application and does not display the PDF preview. Application becomes unresponsive and has to force quit.

**Screenshots**
![image](https://user-images.githubusercontent.com/102159214/202141749-8575b1d7-002a-48ed-a71d-41025e87331b.png)
![image](https://user-images.githubusercontent.com/102159214/202141833-726d3255-7d38-4b39-b3f9-faebb98634b2.png)

**Additional context**
Windows 11
Microsoft Visual Studio Community 2022 (64-bit), Version 17.2.6
QuestPDF version 2022.11.0
QuestPDF Previewer version 2022.11 (installed as per "https://www.questpdf.com/document-previewer")
Application Target Framework: .NET 6.0
Output Type: Windows Application

**Comment by RainHash** [comment]
Hi! 
I'm having the same problem since today.
This is the code in previewer execution.

**Comment by Eduard-Nuco** [comment]
@RainHash I had a similar error the first time around, not sure how to reproduce, but it still hangs.

**Comment by Bebo-Maker** [comment]
Are you using any other library in your quest pdf project, which uses SkiaSharp?
The QuestPDF previewer is using SkiaSharp 2.80.x currently. This can cause issues if some package in your project uses SkiaSharp 2.88.x. 

See #269

**Comment by SuryaWalker** [comment]
Exactly the same issue for me after the update from 2200.8.0 to 2200.11.0. I did the update because of the fix regarding word wrap functionality

**Comment by MarcinZiabek** [comment]
> Exactly the same issue for me after the update from 2200.8.0 to 2200.11.0. I did the update because of the fix regarding word wrap functionality. SkiaSharp version is 2.80.0 (installed automatically via nuget with questpdf package).

What issue exactly? Is there any exceptions?

Btw. I am planning to update both library and previewer to latest version within the December release.

**Comment by Eduard-Nuco** [comment]
> Are you using any other library in your quest pdf project, which uses SkiaSharp? The QuestPDF previewer is using SkiaSharp 2.80.x currently. This can cause issues if some package in your project uses SkiaSharp 2.88.x.
> 
> See #269, #315

No, only QuestPDF

**Comment by SuryaWalker** [comment]
> > Exactly the same issue for me after the update from 2200.8.0 to 2200.11.0. I did the update because of the fix regarding word wrap functionality. SkiaSharp version is 2.80.0 (installed automatically via nuget with questpdf package).
> 
> What issue exactly? Is there any exceptions?
> 
> Btw. I am planning to update both library and previewer to latest version within the December release.
I do not see any error message there, just empty window of the previewer which is nog responsive, I updated my description.

**Comment by RainHash** [comment]
updating Previewer version from 2022.11.0 to 2022.11.1 worked for me
