### ISSUE TITLE
[question] multiple elements in a table cell?

### ISSUE THREAD

**Issue by adamfoneil** [QuestPDF/QuestPDF#435]
Hello! I'm trying to create this layout in QuestPDF.
Notice how some of the table cells have both a text value and an image, and they're centered as a single element within the cell.

![image](https://user-images.githubusercontent.com/4549398/207887048-625160bc-a328-4e31-882f-246cabcf6ca6.png)

The closest I can get to this is to put images in a separate column. But this doesn't look quite right to my customer.

![image](https://user-images.githubusercontent.com/4549398/207887520-dfd27bf5-84b9-4c88-965d-481c51e7697e.png)

Any thoughts how I can achieve a layout with multiple elements in a cell? I thought it might have to do with the `Stack` element, but I see that's deprecated.

**Comment by MarcinZiabek** [comment]
You can do this:

```csharp
table
.Cell()
.Border(1)
.Padding(5)
.Row(row =>
{
    row.Spacing(5);
    row.AutoItem().Text("4.10");
    row.AutoItem().AlignMiddle().Width(15).AspectRatio(1).Image(Placeholders.Image);
});
```

or this:

```csharp
table
.Cell()
.Border(1)
.Padding(5)
.Text(text =>
{
    text.Span("4.10");
    text.Element().PaddingLeft(5).PaddingBottom(-3).Width(15).AspectRatio(1).Image(Placeholders.Image);
});
```

![image](https://user-images.githubusercontent.com/9263853/207940058-a9a04528-d700-4277-9e62-1379c665c91b.png)

**Comment by adamfoneil** [comment]
wow that's beautiful thank you
