### ISSUE TITLE
Table Cell Text Trimming

### ISSUE THREAD

**Issue by rawmotionmb** [QuestPDF/QuestPDF#437]
Hi, 
i am quite new to QuestPDF and i have to say, I really like it. I am just walking through all your examples and 
would have a question regarding table cells and "loooooong" texts. 
What i can see so far is that if a text is too long for a cell it gets wrapped vertically. 

![longcellcontent](https://user-images.githubusercontent.com/119978138/208090248-6f068e75-9458-47e6-9882-34c6ce825eb6.png)

What i would like to do is, trim/clip the text, so it gets not wrapped to a new line. 
Whats would be the best way to accomplish this?

Thanks,
Manuel

**Comment by rawmotionmb** [comment]
Any updates on this?

**Comment by MarcinZiabek** [comment]
You can try the following code:

```csharp
.MaxHeight(100) // adjust to show a desired number of lines
.StopPaging()
.Text(Placeholders.Paragraph());
```

**Comment by rawmotionmb** [comment]
Thanks Marcin, this worked for me!
