### ISSUE TITLE
Table row duplicates if content doesn't have enough place in a cell.

### ISSUE THREAD

**Issue by DemeSteve** [QuestPDF/QuestPDF#442]
**Describe the bug**
If the content of cell is bigger (in height) than the space available the same row duplicates on the next page of the PDF. The rest of the content is displayed in this second row.

**Expected behavior**
If a row doesn't have enough space to display full content (in height), the row should be displayed in the next page without creating an additional part 2 of that same row.

**Screenshots**
![questpdfbugreport](https://user-images.githubusercontent.com/50642582/209811623-6eba7de8-c9f5-481c-aa24-eff1ca9a8ea7.jpg)

**Comment by girlpunk** [comment]
I believe this is expected behaviour, however adding [`ShowEntire()`](https://www.questpdf.com/api-reference/show-entire) or [`ShowOnce()`](https://www.questpdf.com/api-reference/show-once) as needed should achieve what you want.

**Comment by MarcinZiabek** [comment]
@girlpunk is right. At this moment, this is an indented behavior that can be easily tweak with the `ShowOnce` API. Thank you for pointing the issue's author to the right direction.

That being said, I fully understand that this behavior could be misleading or surprising in some cases. I am considering various changes to the library so to align it with what is expected, without loosing any functionality.

**Comment by DemeSteve** [comment]
Thank you so much guys, I was not aware of this. ShowEntire did the trick.
