### ISSUE TITLE
Documentation of length unit types not correct

### ISSUE THREAD

**Issue by Basvg** [QuestPDF/QuestPDF#459]
**Describe the bug**
The table with the different unit types lists 1 centimetre as 2.54 inches. This is not correct, it is the other way around.

**To Reproduce**
https://www.questpdf.com/concepts/length-unit-types

**Expected behavior**
1 centimetre = 1/2.54th of an inch

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/2334483/213429834-ef5b4c20-0ddb-4af0-9b8d-5904f2ecce4f.png)

**Comment by AntonyCorbett** [comment]
Suggested fix: https://github.com/QuestPDF/QuestPDF-Documentation/pull/27

**Comment by MarcinZiabek** [comment]
This is fixed thanks to @AntonyCorbett. Thank you 😁
