### ISSUE TITLE
Unit Test Failing

### ISSUE THREAD

**Issue by AntonyCorbett** [QuestPDF/QuestPDF#464]
The `QuestPDF.ReportSample.ReportGeneration.Profile` test fails with the following exception:

**System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.**

This is thrown from `FontManager.GetTextScale` because `FontPosition` is null.

`DocumentGenerator.RenderPass` visits all children and resets the state of applicable elements. When it attempts to reset the TextBlock state, `ApplyFontFallback` uses `GetFallbackOptions` with a textStyle that contains null `FontPosition`. The `FontManager` tries to convert this into an `SKPaint` instance and the exception is thrown attempting to `GetTextScale`.

**Comment by MarcinZiabek** [comment]
Thank you for finding this issue 😁 I have analysed this specific test method. Previously, it has been used for measuring rendering performance on both layout algorithm passes. Now, I switched to use dotTrace, making this particular test obsolete, thus not updating it for new rendering pipeline.

This test structure is just outdated and does not indicate any bug in the library implementation. As it is not needed anymore, I decided to delete it.
