### ISSUE TITLE
TextStyle does not apply for non-latin characters

### ISSUE THREAD

**Issue by MarcinZiabek** [QuestPDF/QuestPDF#487]
### Discussed in https://github.com/QuestPDF/QuestPDF/discussions/483

<div type='discussions-op-text'>

<sup>Originally posted by **rstm-sf** February  8, 2023</sup>
![image](https://user-images.githubusercontent.com/2669927/217469753-820cce46-204b-4fbe-99ea-b3e22561d08c.png)

Why might this be happening?</div>

**Comment by garryxiao** [comment]
I believe there are some connections with the issue: https://github.com/QuestPDF/QuestPDF/issues/162.

Not all the fonts have specific sub style fonts. Without the sub style fonts, PDF will apply some fake styles based on the font to display bold and italic styles.
