### ISSUE TITLE
How to place an element in the middle of the page taking up as much space as possible, but keeping the elements below on the same page?

### ISSUE THREAD

**Issue by luis-fss** [QuestPDF/QuestPDF#509]
**Is your feature request related to a problem? Please describe.**
How to place an element in the middle of the page taking up as much space as possible, but keeping the elements below on the same page?
My document has a series of fields populated dynamically via software, but it also needs a space to be filled in with a pen after printing and I would like that space to take up as much space as possible without pushing the elements below to the next page.

**Describe the solution you'd like**
I tried using "ExtendVertical()" but that will push the elements below to the next page.

**Describe alternatives you've considered**
I searched a lot, but without success.

**Comment by luis-fss** [comment]
@MarcinZiabek I hope you are well and healthy.
I was reading what you state in: [#134 ](https://github.com/QuestPDF/QuestPDF/issues/134#issuecomment-1066166945)
> "Please remember that you can always predict size of available space on the document (...)."

I think this might be a way to solve my problem here. Can you explain exactly how I could predict the size of available space in the document?

**Comment by flew2bits** [comment]
You can probably accomplish this with a DynamicComponent. Can you describe a little bit more about what you're trying to achieve?

**Comment by flew2bits** [comment]
I think this might be what you're going for: https://gist.github.com/flew2bits/5344d8691ac26d7881091cd18d0d5d4e

**Comment by luis-fss** [comment]
Hello @flew2bits, appreciate the help.

This weekend I'm going to try your code, but looking over it I don't know if that's what I'm trying to do.

I'll try to describe it: imagine a page that will be filled with horizontal blocks/containers, each containing a series of text items that will be added dynamically, so its height will be variable and dynamic. At the end of the page, the last block will hardly be aligned with the footer, thus leaving an empty space. Going back a bit, about the middle of the bottom half of the page I need to add a blank block that will be filled in with handwriting after the document is printed, so I only need to render the borders. Here comes what I asked in this issue: how to make this empty block with just the borders occupy as much vertical space as possible without pushing the blocks below it to the next page?

page header
'_____________________________________________
block 1 (a container with many text items)
'_____________________________________________
block 2 (a container with many text items)
'_____________________________________________

block 3 (an empty container with borders)

'_____________________________________________
block 4 (a container with many text items)
'_____________________________________________

here is the empty space I want to get rid of by increasing the height of block 3 but keeping block 4 on the same page.
page footer

**Comment by flew2bits** [comment]
The image below is what gets generated by the code sample here:

https://gist.github.com/flew2bits/ead2545ce3170555e9f1d9e9e125ee02 (this is an update that includes more content).

The box under "Signature" grows to fill the vertical space remaining on the page after everything else is placed on the page.

![image](https://user-images.githubusercontent.com/4671044/224453300-b49f1883-8f88-44f3-88b9-3a068f364945.png)

**Comment by flew2bits** [comment]
You can easily modify the FillAboveComponent to take another element action to draw what needs to go in the area with the rectangle, in case you need some other content in that area.

**Comment by luis-fss** [comment]
Fantastic! Thanks a lot for the help.
