### ISSUE TITLE
Change page size based on image size

### ISSUE THREAD

**Issue by criss02-cs** [QuestPDF/QuestPDF#516]
**Describe the bug**
I would like to change the page size to match the image size, only when I try to change the size it gives me an error:
`QuestPDF.Drawing.Exceptions.DocumentLayoutException: 'Composed layout generates infinite document. This may happen in two cases. 1) Your document and its layout configuration is correct but the content takes more than 250 pages. In this case, please increase the value QuestPDF.Settings.DocumentLayoutExceptionThreshold static property. 2) The layout configuration of your document is invalid. Some of the elements require more space than is provided.Please analyze your documents structure to detect this element and fix its size constraints.'`

**To Reproduce**
`public IActionResult ConvertImgToPdf([FromBody] string img)
        {
            Stream result = new MemoryStream();
            var stream = img.ToStream();
            Document.Create(document =>
            {
                document.Page(page =>
                {
                    // Inserisco l'immagine all'interno della pagina
                    page
                    .Content()
                    .Image(stream, QuestPDF.Infrastructure.ImageScaling.FitArea);
                    int width = stream.GetSize().Width;
                    int height = stream.GetSize().Height;
                    page.Content().Width(width + 50).Height(height + 50);
                    // Cambio l'orientamento in base alle dimensioni dell'immagine
                    if (stream.GetSize().Width < stream.GetSize().Height)
                    {
                        page.Size(PageSizes.A3.Portrait());
                    }
                    else
                    {
                        page.Size(PageSizes.A3.Landscape());
                    }
                });
            }).GeneratePdf(result);
            return Ok(result.ToBase64String());
        }`
Here is my code, I included 2 extension method, the most important is ToStream that converts a base64 file to a stream

**Expected behavior**
I would like to change the page size to match the image size.
I want to do this beacause if I use QuestPDF.Infrastructure.ImageScaling.Resize, the image will lose resolution, and i don't want that

**Screenshots**
![image](https://user-images.githubusercontent.com/52246268/223429502-a4f0b236-1bcb-41ae-a988-274f81b6a573.png)

**Comment by girlpunk** [comment]
QuestPDF may need the page size to be set before any content is added. Alternatively, is it possible that your image is larger than an A3 page?

**Comment by criss02-cs** [comment]
I already tried to set page size before add any content, I think that your second idea can be right, I will try

**Comment by criss02-cs** [comment]
`
page
                    .Content()
                    .Image(stream, QuestPDF.Infrastructure.ImageScaling.FitArea);
                    int width = stream.ToImage().Size.Width;
                    int height = stream.ToImage().Size.Height;
                    // Cambio l'orientamento in base alle dimensioni dell'immagine
                    var pageSize = new PageSize(width, height);
                    if (width < height)
                    {
                        page.Size(pageSize.Portrait());
                    }
                    else
                    {
                        page.Size(pageSize.Landscape());
                    }
`
This code resolves the issue
