### ISSUE TITLE
Opacity option on backgrounds

### ISSUE THREAD

**Issue by douglott** [QuestPDF/QuestPDF#525]
I would like a way to apply opacity to backgrounds to allow watermarks to show through boxes with a background color.   Please see attached sample of watermark being obscured by backgrounds.
<img width="532" alt="Screenshot 2023-03-27 at 10 46 33 AM" src="https://user-images.githubusercontent.com/19208649/227983764-f5dc87ac-078b-4b64-b32e-dcdb1d428c0f.png">

**Comment by flew2bits** [comment]
You can use a ARGB hexadecimal color for the background. E.g. `.Background("40000000")`. This will make a black background with ~25% opacity.

**Comment by douglott** [comment]
Appreciate the tip @flew2bits.   I used the following code to get ARGB string.

`        System.Drawing.Color myColor = System.Drawing.Color.FromArgb(200, 235, 235, 235);
        _bgColorWithOpacity = myColor.A.ToString("X2") + myColor.R.ToString("X2") + myColor.G.ToString("X2") + myColor.B.ToString("X2");`

The watermark now shows through the background overlay.
