### ISSUE TITLE
Settings.CheckIfAllTextGlyphsAreAvailable does it only support few languages?

### ISSUE THREAD

**Issue by Hamsavani-J** [QuestPDF/QuestPDF#527]
Does Settings.CheckIfAllTextGlyphsAreAvailable support all languages or only few?

```csharp
namespace QuestConsole
{
    internal class Program
    {
        static void Main(string[] args)
        {
            QuestPDF.Settings.CheckIfAllTextGlyphsAreAvailable = false;
            Document.Create(container =>
            {
                container
                .Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(style =>
                    {
                           return style.Fallback(s => s.FontFamily("SimSun"));
                    });
                    page.Content()
                    .Column(x =>
                    {
                        x.Item().Text("Mixed line: This 中文");
                        x.Item().Text("감사합니다 korean");
                        x.Item().Text("谢谢 chinese");
                        x.Item().Text("ありがとう ございます japanese");
                        x.Item().Text("நன்றி tamil");
                        x.Item().Text("धन्यवाद Hindi");
                        x.Item().Text("ขอบคุณ Thai");
                        x.Item().Text("teşekkürler Turkish");
                        x.Item().Text("ಧನ್ಯವಾದಗಳು Kannada");
                    });
                });
            }) .GeneratePdf("hello.pdf");
       }
   }
} 
```

It only supports Chinese and Japanese.

**Screenshots**
![PDfop](https://user-images.githubusercontent.com/68469382/229463802-56892cf0-f5a4-4b58-884c-a4128f9871d1.PNG)

**Expected behavior**
Does QuestPDF support all languages? Or should I have to add anything other than `QuestPDF.Settings.CheckIfAllTextGlyphsAreAvailable = false;` this to make it support other languages? 

Thank You

**Comment by Porkodi-S** [comment]
> namespace QuestConsole
{
    internal class Program
    {
        static void Main(string[] args)
        {
            QuestPDF.Settings.CheckIfAllTextGlyphsAreAvailable = false;
            Document.Create(container =>
            {
                container
                .Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(style =>
                    {
                        return style.Fallback(s => s.FontFamily("SimSun"));
                    });
                    page.Content()
                    .Column(x =>
                    {
                        x.Item().Text("Mixed line: This 中文");
                        x.Item().Text("감사합니다 korean");
                        x.Item().Text("谢谢 chinese");
                        x.Item().Text("ありがとう ございます japanese");
                        x.Item().Text("நன்றி tamil");
                        x.Item().Text("धन्यवाद Hindi");
                        x.Item().Text("ขอบคุณ Thai");
                        x.Item().Text("teşekkürler Turkish");
                        x.Item().Text("ಧನ್ಯವಾದಗಳು Kannada");
                    });
                });
            })
            .GeneratePdf("hello.pdf");
        }
    }
}

**Comment by Porkodi-S** [comment]
`namespace QuestConsole
{
    internal class Program
    {
        static void Main(string[] args)
        {
            QuestPDF.Settings.CheckIfAllTextGlyphsAreAvailable = false;
            Document.Create(container =>
            {
                container
                .Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(style =>
                    {
                        return style.Fallback(s => s.FontFamily("SimSun"));
                    });
                    page.Content()
                    .Column(x =>
                    {
                        x.Item().Text("Mixed line: This 中文");
                        x.Item().Text("감사합니다 korean");
                        x.Item().Text("谢谢 chinese");
                        x.Item().Text("ありがとう ございます japanese");
                        x.Item().Text("நன்றி tamil");
                        x.Item().Text("धन्यवाद Hindi");
                        x.Item().Text("ขอบคุณ Thai");
                        x.Item().Text("teşekkürler Turkish");
                        x.Item().Text("ಧನ್ಯವಾದಗಳು Kannada");
                    });
                });
            })
            .GeneratePdf("hello.pdf");
        }
    }
}`

**Comment by MarcinZiabek** [comment]
I expect that the functionality should work for all languages and fonts. I will investigate the problem. 

Thank you for reaching out!

**Comment by MarcinZiabek** [comment]
You are using quite a diverse set of languages in your test. Therefore, multiple fonts could be needed to provide all necessary glyphs. Each time a glyph is not present, you will get a proper exception:

```
Could not find an appropriate font fallback for glyph: U-0E02 'ข'. Font families available on current environment that contain this glyph: Leelawadee UI, Microsoft Sans Serif, Tahoma, Leelawadee. Possible solutions: 1) Use one of the listed fonts as the primary font in your document. 2) Configure the fallback TextStyle using the 'TextStyle.Fallback' method with one of the listed fonts.
```

By following the exception and choosing random font names provided in the exception, I got the following set of font fallbacks:

```csharp
container
    .Padding(25)
    .DefaultTextStyle(x => x.FontSize(fontSize)
        .Fallback(s => s.FontFamily("SimSun")
            .Fallback(s => s.FontFamily("Malgun Gothic")
                .Fallback(s => s.FontFamily("Nirmala UI")
                    .Fallback(s => s.FontFamily("Microsoft Sans Serif"))))))
    .Column(x =>
    {
        x.Item().Text("Mixed line: This 中文");
        x.Item().Text("감사합니다 korean");
        x.Item().Text("谢谢 chinese");
        x.Item().Text("ありがとう ございます japanese");
        x.Item().Text("நன்றி tamil");
        x.Item().Text("धन्यवाद Hindi");
        x.Item().Text("ขอบคุณ Thai");
        x.Item().Text("teşekkürler Turkish");
        x.Item().Text("ಧನ್ಯವಾದಗಳು Kannada");
    });
```

That results with:
![image](https://user-images.githubusercontent.com/9263853/229934992-2daef113-839f-4284-be6a-685b59dd2f7d.png)

**Comment by Hamsavani-J** [comment]
Thank you so much @MarcinZiabek
