### ISSUE TITLE
ElementTrace - determine why and which element causing the DocumentLayoutException

### ISSUE THREAD

**Issue by troncomputers** [QuestPDF/QuestPDF#530]
Hi!
I need some help with explanation about ElementTrace. The last element in the ElementTrace is
```
 🔥 TextBlock
------------
Available space: (Width: 46,000, Height: 0,000)
Requested space: Wrap
Content Direction: LeftToRight
Alignment: Left
Text: 2320,62
```
But, what is the problem? Is it width? Text is just a number.

I would like to parse this string to extract and throw more readable exception or fix this in code without throwing an exception at all. Is there a way to do that?

Documentation says that
```
🔥 - represents an element that causes the layout exception. Follow the symbol deeper to find the root cause.
```
This `TextBlock` is the last element in ElementTrace, but I don't know what is wrong with it?

**Comment by MarcinZiabek** [comment]
This is a great suggestion, thank you! 😁 

I am already planning a couple of potential improvements for the debugging experience. Your suggestion will surely find its release.
