### ISSUE TITLE
Is it possible to update the header of a table after a page break?

### ISSUE THREAD

**Issue by ArnautS** [QuestPDF/QuestPDF#538]
When a table spans multiple pages, the header is repeated.
Is it possible to know that the header is repeated and update the text of the header like this:

![image](https://user-images.githubusercontent.com/44735497/234516394-75f3df3f-e2fc-419e-92b9-6aeecba8c607.png)
Example from [here](https://www.questpdf.com/api-reference/table.html#table-header-footer), with (continued) added to the first cell of the header.
Or maybe with parts, like (1/2) and (2/2) in the header?

**Comment by girlpunk** [comment]
Using a [Dynamic Component](https://www.questpdf.com/concepts/dynamic-components.html#state-management) inside the cell should be able to achieve this. Use the state to track if this is the first page and add the continued text if not.

**Comment by ArnautS** [comment]
Thank you for pointing out this component, it does exactly what I wanted.
I used the following code to track the first page of the header
```
int firstPage = State.FirstPage > 0 ? State.FirstPage : context.PageNumber;
State = new HeaderContinuedState
{
    FirstPage = firstPage
};
```

**Comment by MarcinZiabek** [comment]
There is one more option that fits your requirement. You can use the `SkipOnce` API to show certain things only on the second and consecutive pages. This is a way simpler approach than using the `DynamicComponent`.
