### ISSUE TITLE
Support for rendering latex

### ISSUE THREAD

**Issue by SoggyBottomBoy** [QuestPDF/QuestPDF#547]
**Is your feature request related to a problem? Please describe.**
An API for rendering latex, ideally with multiple lines aligned to "=".

**Describe the solution you'd like**
An API similar to Text for rendering latex using the latex syntax.

**Describe alternatives you've considered**
I've tried using chsarpmath to give a skid canvas to render latex, however the quality is extremely poor. Unsure if I'm missing something or there is another way.

**Additional context**

**Comment by MarcinZiabek** [comment]
> I've tried using chsarpmath to give a skid canvas to render latex, however the quality is extremely poor. Unsure if I'm missing something or there is another way.

Would you please share more details about the problem? Why do you think that the output is of poor quality when using the CSharpMath library? If possible, please share some screenshots 😀

**Comment by SoggyBottomBoy** [comment]
Sorry been pretty busy of late. This is from the previewer. I'm not that familiar with skiasharp, so I could be using the wrong APIs.

```csharp
        SKBitmap bitmap = new(100, 100);
        SKCanvas canvas = new(bitmap);
        CSharpMath.SkiaSharp.MathPainter painter = new()
        {
            LaTeX = @"\frac\sqrt23"
        };
        painter.Draw(canvas);

        container.Height(50).Canvas((c, size) =>
        {
            c.DrawBitmap(bitmap, new SKRect(0, 0, 100, 100));
        });
```

![image](https://github.com/QuestPDF/QuestPDF/assets/36346832/44124ac1-8d6e-4146-8182-a0040e8d3fda)

**Comment by SoggyBottomBoy** [comment]
Wait my bad, I was looking at this code and thought it odd I seemed to be double hanlding. Corrected to 
```csharp
CSharpMath.SkiaSharp.MathPainter painter = new()
{
    LaTeX = @"\frac\sqrt23"
};

container.Height(50).Canvas((c, size) =>
{
    painter.Draw(c);
});

![image](https://github.com/QuestPDF/QuestPDF/assets/36346832/3600805a-9abc-4f1d-9506-7f11af4a683a)
