### ISSUE TITLE
How do I get QuestPDF Community MIT license ? 

### ISSUE THREAD

**Issue by jayonsoftware** [QuestPDF/QuestPDF#548]
I am not using QuestPDF for commercial purposes. Been using it past few weeks just to learn. I do not have a company that makes 1M year either (I wish I had :))....but last night I updated the packages and now get a lic exception, and I can't use the product. How do I go about fixing this? Thanks

**Comment by luis-fss** [comment]
`QuestPDF.Settings.License = LicenseType.Community;`

**Comment by MarcinZiabek** [comment]
@luis-fss Thank you for the fast response! I will do my best to cover this question in the documentation and the getting started tutorial.
