### ISSUE TITLE
Container of inlined elements increase height on HorizontalSpacing > 0

### ISSUE THREAD

**Issue by dermoench42** [QuestPDF/QuestPDF#55]
**Describe the bug**
Container of inlined elements increase height on HorizontalSpacing > 0.

I build a 6 month scheduler with a typical 'day' container of 40mm x 5mm. In that Container I inserted image elements with the inlined container. Works fine until I wanted some horizontal spacing and therefore added the .HorizontalSpacing(50). After that the containing day element increases its height, depending on the count of images I inserted. But all images fit in and were displayed  all in one Line.

** probably wrong **
I took a look in the well readable sources at ./Elements/Text/Inlined.cs and found line 67 which looks suspicious to me:
```var heightWithSpacing = size.Height + (line.Count - 1) * HorizontalSpacing```
Semanticaly a horizontal length is probably wrong in an height, which is an vertical measurement.

**Expected behavior**
Increase height only when the inlined items wrap line.

**Additional context**
Since this is only a short look in the code I coul'd not provide a detailled analysis and a solving pull request yet.

**Comment by MarcinZiabek** [comment]
Hello, thank you for finding this issue! Indeed, there is something wrong. After some investigation, I think this is a correct implementation:

```csharp
var lineSizes = lines
	.Select(line =>
	{
		var size = GetLineSize(line);
		var widthWithSpacing = size.Height + (line.Count - 1) * HorizontalSpacing; // changed here
		return new Size(widthWithSpacing , size.Height); // and here
	})
	.ToList();

var width = lineSizes.Max(x => x.Width);
var height = lineSizes.Sum(x => x.Height) + (lines.Count - 1) * VerticalSpacing;
var targetSize = new Size(width, height);
```

It would be great if you can confirm :)

**Comment by MarcinZiabek** [comment]
Can you please share your code and a screenshot showing its result?

**Comment by dermoench42** [comment]
I'm a little short in time, but this is a cool piece of code and therefore  I think about preparing a Year Scheduler example to show this issue and investigate the code a little more.

**Comment by MarcinZiabek** [comment]
@dermoench42 Hi, I have just pushed a new 2021.11.4 release that hopefully fixes this issue 😁 Can you please try it and let me know?

**Comment by dermoench42** [comment]
This seem to be fixed.
