### ISSUE TITLE
CMYK Support

### ISSUE THREAD

**Issue by pha3z** [QuestPDF/QuestPDF#56]
So I realize this is a deep problem.  I'm hoping for a way to accomplish this with QuestPDF, or perhaps some direction on a different library I could use.

The workflow I'm doing is this:
Save CMYK document to SVG file (this is the problem!)
Use SKCanvas with Quest to draw the SVG into a PDF.

It works fantastic except SVG is NOT a CMYK format.  I need proper CMYK colors in my PDF.  Some reading on Skia says that Skia does support CMYK color space, so if I could somehow get the CMYK image into Skia, we're gold.  Unfortunately, the only vector format I'm finding support for with Skia is SVG :(.

Does anyone know of a way to bring .EPS or .AI or .PDF files into Skia?  Any of those would allow transport of CMYK format from application to Skia to PDF to printer.

**Comment by MarcinZiabek** [comment]
I have read about including additional information within SVG files that contain CMYK colours. However, I doubt it will be properly recognized by the SkiaSharp.Svg library. Can you please provide an example of the graphics that you want to include in the PDF file?

**Comment by pha3z** [comment]
I would bet money importing an SVG with CMYK will not work reliably with SkiaSharp.Svg.  I don't think its a good road to go down, because it would probably require modifying SkiaSharp.Svg to interpret the CMYK data.... and it would bring up consensus problems -- since there's no standard on CMYK in SVG, you'd literally have to create the spec out of thin-air  (unless whoever maintains the SVG spec has put out a plan for a CMYK spec).

I can't find a single C# library that reads .EPS files.  I've found a few examples of C++ implementations but they look crude/suspect.

It might make the most sense to write a C# library for SkiaSharp that parses .EPS.  I'm considering that, but realistically I'm not sure I have time.  The primary challenge in making an .EPS library would probably be correctly interpreting the Bezier curves/shapes and turning them into Skia data.  If a person could overcome that, I think the rest of it its non-trivial reverse-engineering by just looking at the Text of some .EPS files.

**Comment by MarcinZiabek** [comment]
Before you start working on the translation layer from EPS to SkiaSharp commands, please first make sure that Skia supports CMYK in PDF the rendering process 😁

**Comment by pha3z** [comment]
That is a good point. I read that the Skia color space supports CMYK. How are you using Skia to generate the PDF?  Is everything going onto a Canvas first?  And does Skia make the PDF for you?

**Comment by MarcinZiabek** [comment]
That's correct. The entire document's layout is converted into a stream of commands to perform on the SkiaCanvas. So it is important to check first if Skia supports what you are trying to accomplish :)

Either way, isn't EPS just a PostScript? Meaning... it is a turing-complete programming language which makes it rather difficult to translate? I am really interested in what you are trying to accomplish. Maybe, using just using high enough DPI would be enough for your usecase?

**Comment by pha3z** [comment]
I am creating and printing CMYK vector graphics.  DPI doesn't address a color space problem.  Whenever you run an RGB doc to the printer, the printer drivers translate the RGB color to CMYK.  Most printers (mine included) will give you some basic options for the translation.  Mine for instance has "Adobe RGB", "Epson Vivid", and Nothing.  Epson Vivid does what you'd expect -- the transformed colors are made bright and vivid by maximizing concentrate in one or two inks and minimizing complex mixing. Of course, that might not be what one wants... and it can have negative consequences for particular colors.

One of the problem with RGB to CMYK color transformations is that CMYK is woefully inadequate at portraying many colors.  Greens come from C and Y pigments.  You are quite limited on the range of greens from pigment mixing.  Getting an exact true Red can also be challenging... and its never really quite right.

To get the best result, you need to give the printer a CMYK document so that the colors translate directly to ink amounts, giving you exact control in your design.  When you translate CMYK to RGB, varying levels of Black (K) are often injected depending on the translation function.  Some translations may prefer to mix CMY to create darker colors in certain ranges -- but such colors can sometimes look muddy -- making addition of Black (K) a better choice depending on the look you need.   It's a lot of voodoo and guesswork put into an n-dimensional mapping function basically, and it sucks to pass data through that function if you could instead set the colors to what you want.

Regarding your question about EPS.... EPS is an extension of PostScript.  I can't find much documentation on it -- sadly the Wikipedia page is the best info I've found.

Regarding Turing-Complete languages, I'm woefully uneducated to answer that question.  I have a lot of experience tinkering with syntax and expressions for human readability and expressiveness, but I couldn't tell a Turing-Complete language from one that isn't.

When I look at an EPS text file, it actually looks pretty straight forward.  Its mostly just a collection of line segments (optionally curved) with fill color and stroke color definitions.  I have a lot of experience transforming 3d data, so to me the file mostly just looks like an advanced form of geometry data I would expect to see.  But maybe I'm missing something because I'm not familiar with Turing-Completeness or what that would mean for the file format.  I haven't seen any good documentation on Postscript either .... :(   even a thin blog post -- do you know of anything?

- James

**Comment by MarcinZiabek** [comment]
It almost raises a question if SkiaSharp (and therefore QuestPDF) are the right tools for your requirements. Although I have general knowledge about CMYK and how printers work, I doubt that SkiaSharp support is enough. Thank you for describing how this color space works - I didn't know it is so complex and hard to grasp.

In terms of EPS and PostScript reference, I've found [this reference from Adobe](https://www.adobe.com/content/dam/acom/en/devnet/actionscript/articles/PLRM.pdf). Just the size of this document suggests that an attempt of implementing support for this file format is almost a fiasco. If there are any well-working paid products, they may be cheaper compared to your work after all. The only exception is if you want to support only a couple of very simple cases OR your graphics software generates files with a well-known subset of instructions. 

By saying that PostScript is a Turing-complete language I mean that I have support for array/variables/loops/procedures, etc. So it almost requires an interpreter...

**Comment by pha3z** [comment]
I have not seen an EPS file that contains any of those things.  That comes as a surprise to me.  Its basically just geometry data. I will keep this in mind though.

SkiaSharp is kind of the de-facto drawing library for .net is it not?  If it supports CMYK, that should be enough.  This problem really *should* be as simple as packing 4 data points (CMYK instead of ARGB) in a transport format and keeping those data points.  Its silly that CMYK is barely paid attention to in the portable data arena.

**Comment by pha3z** [comment]
I'm revisiting this issue from a different angle.  It seems like it might be more viable to find a solution that allows the path data from PDF files to be used as the source for drawing shapes on the Skia canvas.  So PDF instead EPS as the image source (both support CMYK).  Do you know of a library that would allow us to go from PDF paths to Skia commands?

**Comment by pha3z** [comment]
You're right about the CMYK in Skia support being pretty much entirely absent.  Anything that depends on Skia is a non-option.

:\

Looks like I would have to consider a different PDF library altogether.  I found a commercial one that writes CMYK PDFs: https://www.graphicsmill.com/docs/gm/graphics.htm
Although I still have the problem of reading a PDF or an EPS file for my source art. LOL

Thank you for your help and consideration!!!
