### ISSUE TITLE
QuestPDF.Drawing.Exceptions.DocumentComposeException: Cannot load or decode provided image.  

### ISSUE THREAD

**Issue by seobjk** [QuestPDF/QuestPDF#567]
I use Quest to generate PDF documents in my Azure Web App service with NopCommerce.
Unfortunately, I get the following error, which I don't know what to do:
**QuestPDF.Drawing.Exceptions.DocumentComposeException: Cannot load or decode provided image.**  

I want to add a image to the header:
```
 row.ConstantItem(75).AlignRight().AlignTop().Column(stack =>
                        {
                            stack.Item().MaxWidth(75).MaxHeight(75)
                                 .Image("Themes/Platform/Content/images/Logo.png",
                                 ImageScaling.FitArea);
                        });
```

Anyone have an idea what could be the cause?

Thanks

**Comment by MarcinZiabek** [comment]
Are you sure that the image file is available under provided relative path? Please check using the `File.Exists` method from the standard library.

Best, Marcin

**Comment by seobjk** [comment]
> Are you sure that the image file is available under provided relative path? Please check using the `File.Exists` method from the standard library.
> 
> Best, Marcin

Hi Marcin,
thanks for your answer.
It was the leading "\" in the file path. After this was removed, the PDF could also be created without errors.
