### ISSUE TITLE
License Query

### ISSUE THREAD

**Issue by PlayerModu** [QuestPDF/QuestPDF#578]
I would like to confirm, if I may, if I am okay to use QuestPDF under the Community MIT license within my current company of employment.

Matching against the wording on the QuestPDF website under the "What license do you need?" section on the Pricing page, my current company:
- Does create closed source software for internal use only
- Does have more than 1M USD annual gross revenue 
- But is not a for-profit company

**Comment by MarcinZiabek** [comment]
If the project is not for-profit (is meant to generate profit, e.g.: commercial application, reduced company costs, paid product, etc.), you can safely use the MIT license 😁

Please feel free to use the enhanced licensing experience on the homepage: https://www.questpdf.com/pricing.html
