### ISSUE TITLE
Different border colors ?

### ISSUE THREAD

**Issue by namtab00** [QuestPDF/QuestPDF#579]
I'm trying to set different border colors on a table cell.

![image](https://github.com/QuestPDF/QuestPDF/assets/995900/b6a87214-e056-46df-95de-14b93caeb48b)

![image](https://github.com/QuestPDF/QuestPDF/assets/995900/6ad6942b-10ac-4e9a-884f-0831242542bb)

![image](https://github.com/QuestPDF/QuestPDF/assets/995900/80f0622e-9451-45f5-87f1-f74061053e26)

What am I missing ?

**Comment by MarcinZiabek** [comment]
@namtab00 Your solution is correct 😁 Do you have any suggestions on improving the general development experience? I suppose that your use case is not very common. Maybe an additional section in the documentation will be sufficient?
