### ISSUE TITLE
Printing Support

### ISSUE THREAD

**Issue by sbrkich** [QuestPDF/QuestPDF#58]
Our company is looking at upgrading some old software written in Visual Basic 6, they were using VSReport to generate invoices and other things that could easily be reworked into QuestPDF. However, we need the ability to send these to a printer so we can print them out automatically. Would it be possible to add support to QuestPDF to print the documents instead?

**Comment by MarcinZiabek** [comment]
Hello :) 

I am afraid that the printing functionality is outside of the library scope. 

However, you can use QuestPDF to generate your PDF files and then use other libraries to send such files to the printer. I have seen some examples in WinForms, WPF, PDFium, etc. Please take a look. If you find something useful and open source, please feel free to share here with others 😁

**Comment by sbrkich** [comment]
> Hello :)
> 
> I am afraid that the printing functionality is outside of the library scope.
> 
> However, you can use QuestPDF to generate your PDF files and then use other libraries to send such files to the printer. I have seen some examples in WinForms, WPF, PDFium, etc. Please take a look. If you find something useful and open source, please feel free to share here with others 😁

Thank you for the response. However, I was taking a look at different ways of printing in .NET without using external libraries and come to find out it's relatively easy to print using a PrintDocument or a FixedDocument without using any third party libraries. This had me going down the rabbit hole of figuring out how QuestPDF actually generates the files to see if I could make something to generate those instead. This took me down another rabbit hole of looking into SkiaSharp and realized it is capable of generating XPS files as well which connected a bunch of dots. You can convert an XPS to a FixedDocument without relying on a third party library, from there you can easily print the FixedDocument.

So, would you be able to add the option to QuestPDF to generate XPS files as well?

**Comment by MarcinZiabek** [comment]
I will investigate the XPS format support. If everything goes well, it may be available in the next release. At this point, I am just not sure what surprises may wait for me on the SkiaSharp integration. Once I make any progress, I will publish a beta version, so we can work together.

**Comment by MarcinZiabek** [comment]
Hello :) I have implemented support for generating documents in the XPS file format. Can you please try the `QuestPDF 2021.12-alpha0` and let me know if it works as expected?

Also, if you are correct and this helps with printing documents, it would be fantastic to update the documentation to help others. I hope we can cooperate on this 😁

**Comment by MarcinZiabek** [comment]
Generating XPS documents is already available in QuestPDF 2021.12. Closing.
