### ISSUE TITLE
Text Wrap & multiple Items in one Cell in Tables

### ISSUE THREAD

**Issue by mmDevel** [QuestPDF/QuestPDF#588]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Currently If you try to insert multiple items, into same table cell, it just put it on top of each other, we would need to display them side by side, something like this:
![image](https://github.com/QuestPDF/QuestPDF/assets/118260991/320ba1c9-6e42-49e1-9338-0540f3ec791a)

Also nice feature would be if it would be able to hide overflow text.
Or maybe if there is a different way, how to achieve this, any help will be highly appreciated. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MarcinZiabek** [comment]
Inside a table cell, you can put other layout structures, e.g.: row, column or even another table. It gives you a high flexibility, for example:

```csharp
.Table(table =>
{
    // columns definition code

    table.Cell().Column(column => {
        column.Item().Text("A");
        column.Item().Text("B");
    });
});
```

You can stop displaying overflow text, by using the [StopPaging element](https://www.questpdf.com/api-reference/stop-paging.html#stop-paging) with additional size restrictions, e.g.: with WidthMax and HeightMax elements 😁

**Comment by mmDevel** [comment]
Thank you, this is really helpful. 😊
