### ISSUE TITLE
Table in Table content over content

### ISSUE THREAD

**Issue by mmDevel** [QuestPDF/QuestPDF#589]
**Describe the bug**

Hi I have code:
``` C#
table.Cell()
  .Row(8).RowSpan(4)
  .Column(6)
  .Element(BlockAccepted)
  .Element(container => {
      container.Table(table => {
          table.ColumnsDefinition(columns => {
              columns.RelativeColumn();
              columns.RelativeColumn();
              columns.RelativeColumn();
          });
          table.Cell().Column(0).Text("1");
          table.Cell().Column(1).Text("2");
          table.Cell().Column(2).Text("3");
  
      });
  });
```
And it gets rendered like this:
![image](https://github.com/QuestPDF/QuestPDF/assets/118260991/2b415fbc-e6ad-4407-ab5f-d10369617a97)

**To Reproduce**
Please provide an example, minimalistic code that shows the problem.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by MarcinZiabek** [comment]
Counting starts at 1 by design - it is to make code closer to HTML convention. But I certainly understand the reason of confusion 🤣
