### ISSUE TITLE
Collection of 2 in iteration only writes first item to document

### ISSUE THREAD

**Issue by needledrag** [QuestPDF/QuestPDF#595]
**Describe the bug**
I have list which is iterated over and each item fed into a component to render the details for the document.  
It works fine in all scenarios except when there are only 2 items in the list.  For some reason only the first item is present in the document even though I've debugged and the 'foreach' loop executes twice with no errors.

If I then call the component a third time and execute straight away without writing anything to the document then the second item is present in the document.  
In scenarios of n == 1 item or n > 2 items it works fine and always writes the correct amount of items to the document.

**To Reproduce**
Produce a situation similar to the below with only 2 items in the Items collection.  MyComponent just creates a table and fills some rows.

`

 container.PaddingVertical(10)
            .Column(x =>
            {
                x.Spacing(5);
                x.Item()
                    .BorderBottom(1)
                    .PaddingBottom(5)
                    .Text("My Items").SemiBold();

                foreach (var item in MyCollection)
                {
                    x.Item().Row(row =>
                    {
                        row.RelativeItem().Component(new MyComponent(item));
                    });
                }
            });
`

**Expected behavior**
When there are 2 items in the collection both should appear in the document.

**Additional context**
In trying to figure out the problem I found the following hack works but it's far from ideal and just skirts around the problem.
In MyComponent if the item is null then it just returns without any processing.

`

                // force a last call with null as the item and somehow it works?
                if (MyCollection.Count == 2)
                {
                    x.Item().Row(row =>
                    {
                        row.RelativeItem().Component(new MyComponent(null));
                    });
                }

`

Any help would be greatly apprecitated.

**Comment by MarcinZiabek** [comment]
Hi 😁 Would you please share a reproducible code that I can use to debug and help? Some screenshots also could be beneficial.

**Comment by needledrag** [comment]
Hey man, thanks for getting back to me.  So, apologies, I found the problem while producing a sample for you.
In the final row of the table I add a bottom border that spans all columns to act as a separator but there was no content (.Text()).  If I add an empty string to the Text property it works as expected.
I'm not sure why this only happens when there are 2 items in the collection but now it works for all items.
Will close asap.

Apologies for the premature post, I'll close it.
