### ISSUE TITLE
How to add left spacing to a piece of text?

### ISSUE THREAD

**Issue by Prototipo-Erick-Santander** [QuestPDF/QuestPDF#605]
Hello, 

It's exactly as the title says, how could I add a spacing left to a piece of text,
I can't find a way to do this with a specific distance with points or something. 

I know I can do something  like;

```c#
int spacesLeft = 2;
container.Text(text =>
{
    text.AlignLeft();
    for (int i = 0; i < spacesLeft; i++)
    {
        text.Span(" ");
    }

    text.Span("This is the text that is indented");
});
```

But this uses spaces to create the 'spacing', so it's not ideal since it can change based on font family and size.

Is there any better way to accomplish this?

Thanks in advance.

**Comment by MarcinZiabek** [comment]
This is a good alternative:
```csharp
.Padding(25)
.Background(Colors.Grey.Lighten3)
.Text(text =>
{
    // this line is important, it injects a transparent space of a certain width
    text.Element().Width(50);

    text.Span(Placeholders.LoremIpsum()).FontSize(20);
});
```

That produces:
![image](https://github.com/QuestPDF/QuestPDF/assets/9263853/ea600da3-76ba-4b7e-891f-7677c0215cd4)
