### ISSUE TITLE
How can I make a table of contents?

### ISSUE THREAD

**Issue by leandrobattochio** [QuestPDF/QuestPDF#608]
I just found this lib and it is very good but one thing I don't understand and didn't find any information of how to do is a table of content, like this one:
![image](https://github.com/QuestPDF/QuestPDF/assets/1385182/5648b7ab-0d88-4c55-b428-202ea7a16bf9)

I'm using QuestPDF to generate a report, it's a dynamic report, may have random number of pages but it follows a structure and table of contents is one of the required features of the report.

How would I go to achieve this feature and generate a dynamic table of contents based on the current document I'm generating?

**Comment by leandrobattochio** [comment]
What do I do with `TableOfContentsTemplate`? How to use it? Should I copy and paste? Should I be able to run QuestPDF.ReportSample project to get a preview of an example report?

**Comment by girlpunk** [comment]
Read the code and implement something similar in your program?

**Comment by leandrobattochio** [comment]
I was able to generate the given report example by running the test. Btw, is this how it should look? It doesn't seem like the page numbering is correct. I can navigate by right clicking, but there is no page numbering.

![image](https://github.com/QuestPDF/QuestPDF/assets/1385182/3f59300b-3d32-4852-a862-167f96028bd1)

Can you confirm the issue ?
