### ISSUE TITLE
[BUG] Missing page numbers in StandardReport table of contents

### ISSUE THREAD

**Issue by leandrobattochio** [QuestPDF/QuestPDF#609]
**Describe the bug**
When executing `GeneratePdfAndShow` test method and vieweing the generated pdf report, sections of the table of contents are being rendered with incorrect/missing page numbers.

**To Reproduce**
Run `GeneratePdfAndShow` test and inspect the generated pdf file.

**Expected behavior**
It should should contain the page numbers for each section as intended.

**Screenshots**
![image](https://github.com/QuestPDF/QuestPDF/assets/1385182/2a652a0e-9520-4a99-bede-c78fe523b3fa)

**Comment by leandrobattochio** [comment]
> Please could you share the full code for generating this document, thanks

Just clone the repository and run the test as I said.

@MarcinZiabek 
Thanks!!!

**Comment by MarcinZiabek** [comment]
This bug should be fixed in the `2023.6.1` release.

**Comment by leandrobattochio** [comment]
@MarcinZiabek  it is working now as screenshot:
![image](https://github.com/QuestPDF/QuestPDF/assets/1385182/1ed64369-70b1-44f5-8388-058a69974cee)

The only error I'm getting I don't know why, is this:
![image](https://github.com/QuestPDF/QuestPDF/assets/1385182/cb84e36c-3568-4f3d-9444-2673e655ddf8)

**Comment by MarcinZiabek** [comment]
The Previewer functionality is available only in dotnet 6 and beyond (the version when hot-realod was introduced) 😁

**Comment by leandrobattochio** [comment]
Its okay! You can close the bug =)
