### ISSUE TITLE
Multilevel list

### ISSUE THREAD

**Issue by LearningProcesss** [QuestPDF/QuestPDF#614]
Hi,

is a multilevel list possible? Something like:

![image](https://github.com/QuestPDF/QuestPDF/assets/38817460/a41146f0-5eef-4895-9fae-531c248234f6)

Thanks.

**Comment by bennetbo** [comment]
Yes, this is pretty straight forward, see the example below:
```csharp
public record FlatListItem(string Data, int Position, int Indent);

public static void GenerateMultilevelList(IContainer parent, IEnumerable<FlatListItem> elements)
{
  parent.Column(c =>
  {
      foreach (var element in elements)
      {
          c.Item().PaddingLeft(10 * element.Indent).Row(r =>
          {
              r.Spacing(2);

              r.AutoItem().Text(element.Position + ")");
              r.RelativeItem().Text(element.Data);
          });
      }
  });
}

//Somewhere in your code...

var container = //your outer container, e.g. a Column.

GenerateMultilevelList(container, new FlatListItem[]
{
  new FlatListItem("Item 1",  1, 0),
  new FlatListItem("Item 1.1", 1, 1),
  new FlatListItem("Item 1.2", 2, 2),
  new FlatListItem("Item 2", 2, 0),
  new FlatListItem("Item 3", 3, 0),
  new FlatListItem("Item 3.1", 1, 1),
});
```
Which will generate the following structure:
![image](https://github.com/QuestPDF/QuestPDF/assets/53836821/4f6d1857-0093-4941-98b1-b18d800e61b2)

---

If you have a hierarchical structure of items, you can do something like this:
```csharp
//Lets assume your data structure looks like this:
public record NestedListItem(string Data, List<NestedListItem> Children);

//Using this we can flatten the structure and use the code above.
public static IEnumerable<FlatListItem> FlattenListItems(List<NestedListItem> items) {
    static IEnumerable<FlatListItem> FlattenListItemsRecursive(IEnumerable<NestedListItem> items, int indent)
    {
        int positionOuter = 1;
        foreach(var item in items) {
            yield return new FlatListItem(item.Data, positionOuter, indent);
            positionOuter++;
            
            int position = 1;
            foreach(var child in FlattenListItemsRecursive(item.Children, indent + 1)) {
                yield return new FlatListItem(child.Data, position, indent + 1);
                position++;
            }
        }
    }

    foreach(var item in FlattenListItemsRecursive(items, 0)) {
        yield return item;
    }
}

//Somewhere in your code...
var items = new NestedListItem[]
{
  new NestedListItem("Item 1", new List<NestedListItem>()
  {
      new NestedListItem("Item 1.1", new List<NestedListItem>()),
      new NestedListItem("Item 1.2", new List<NestedListItem>()),
  }),
  new NestedListItem("Item 2", new List<NestedListItem>()),
  new NestedListItem("Item 3", new List<NestedListItem>()
  {
      new NestedListItem("Item 3.1", new List<NestedListItem>())
  })
};

var container = //your outer container, e.g. a Column.

GenerateMultilevelList(container, FlattenListItems(items));
```

**Please note that the code is just an example, i threw it together in a couple of minutes (Its kinda messy 😅).**

**Comment by LearningProcesss** [comment]
> Yes, this is pretty straight forward, see the example below:
> 
> ```cs
> public record FlatListItem(string Data, int Position, int Indent);
> 
> public static void GenerateMultilevelList(IContainer parent, IEnumerable<FlatListItem> elements)
> {
>   parent.Column(c =>
>   {
>       foreach (var element in elements)
>       {
>           c.Item().PaddingLeft(10 * element.Indent).Row(r =>
>           {
>               r.Spacing(2);
> 
>               r.AutoItem().Text(element.Position + ")");
>               r.RelativeItem().Text(element.Data);
>           });
>       }
>   });
> }
> 
> //Somewhere in your code...
> 
> var container = //your outer container, e.g. a Column.
> 
> GenerateMultilevelList(container, new FlatListItem[]
> {
>   new FlatListItem("Item 1",  1, 0),
>   new FlatListItem("Item 1.1", 1, 1),
>   new FlatListItem("Item 1.1.1", 2, 2),
>   new FlatListItem("Item 2", 2, 0),
>   new FlatListItem("Item 3", 3, 0),
>   new FlatListItem("Item 3.1", 1, 1),
> });
> ```
> 
> Which will generate the following structure: ![image](https://user-images.githubusercontent.com/53836821/255650886-bf2e91cf-ab40-4861-9098-3fdfffe86b8d.png)
> 
> If you have a hierarchical structure of items, you can do something like this:
> 
> ```cs
> //Lets assume your data structure looks like this:
> public record NestedListItem(string Data, List<NestedListItem> Children);
> 
> //Using this we can flatten the structure and use the code above.
> public static IEnumerable<FlatListItem> FlattenListItems(List<NestedListItem> items) {
>   static IEnumerable<FlatListItem> FlattenListItemsRecursive(IEnumerable<NestedListItem> items, int indent)
>   {
>       var list = new List<FlatListItem>();
>       int pos = 1;
>       foreach(var item in items) {
>           list.Add(new FlatListItem(item.Data, pos, indent));
>           pos++;
>           
>           list.AddRange(FlattenListItemsRecursive(item.Children, indent + 1));
>       }
>       return list;
>   }
> 
>   return FlattenListItemsRecursive(items, 0);
> }
> 
> //Somewhere in your code...
> var items = new NestedListItem[]
> {
>   new NestedListItem("Item 1", new List<NestedListItem>()
>   {
>     new Helper.NestedListItem("Item 1.1", new List<Helper.NestedListItem>()
>     {
>         new Helper.NestedListItem("Item 1.1.1", new List<Helper.NestedListItem>())    
>     }),
>   }),
>   new NestedListItem("Item 2", new List<NestedListItem>()),
>   new NestedListItem("Item 3", new List<NestedListItem>()
>   {
>       new NestedListItem("Item 3.1", new List<NestedListItem>())
>   })
> };
> 
> var container = //your outer container, e.g. a Column.
> 
> GenerateMultilevelList(container, FlattenListItems(items));
> ```
> 
> **Please note that the code is just an example, i threw it together in a couple of minutes (Its kinda messy 😅).**

Thanks for the detailed example definitly to check out since i ended up with something very close.

**Comment by MarcinZiabek** [comment]
Let me share an alternative solution that does not use list postprocessing but rather utilizes library layout structures.

I believe that the solution provided by @bennetbo is likely more performant as it utilizes simpler layout algorithms. However, the approach below is slightly more extendable.

Model:
```csharp
public class ListItem
{
    public string Title { get; set; }
    public IList<ListItem> Items { get; set; }
}
```

Sample data generation:
```csharp
public IList<ListItem> GenerateSampleList(int level = 3)
{
    return Enumerable
        .Range(1, Placeholders.Random.Next(3, 5))
        .Select(x => new ListItem
        {
            Title = Placeholders.Label(),
            Items = level > 0 ? GenerateSampleList(level - 1) : new List<ListItem>()
        })
        .ToList();
}
```

Helper function:
```csharp
void ComposeList(IContainer container, IList<ListItem> listItems)
{
    const float LeftOffset = 20;
    
    container
        .Column(column =>
        {
            column.Spacing(5);

            foreach (var index in Enumerable.Range(0, listItems.Count))
            {
                column.Item().Row(row =>
                {
                    row.ConstantItem(LeftOffset).ShowOnce().Text($"{index+1}.");
                    
                    row.RelativeItem().Column(column =>
                    {
                        column.Item().Text(listItems[index].Title);
                        column.Item().Element(container => ComposeList(container, listItems[index].Items));
                    });
                });
            }
        });
}
```

Usage:
```csharp
var list = GenerateSampleList();

content
    .Padding(20)
    .Element(container => ComposeList(container, list));
```

Result:
![image](https://github.com/QuestPDF/QuestPDF/assets/9263853/0a70797c-2130-46f9-9894-866c7220ff9f)
