### ISSUE TITLE
[Question] Table cell padding

### ISSUE THREAD

**Issue by leandrobattochio** [QuestPDF/QuestPDF#619]
I'm trying to add padding to all my table cells like the example:

![image](https://github.com/QuestPDF/QuestPDF/assets/1385182/49868707-b8de-44e0-b549-81945e82efbf)

But I'm failing to find out what api's to use.  Is that possible?

**Comment by girlpunk** [comment]
Are you referring to the white gaps between cells, or the space between the edge of the cell background and the content?

The prior can be done by adding padding before the background, for example
```csharp
container
    .Padding(5)
    .Background("#00FF00")
    .Text("Hello")
```

The latter is item/text alignment, using `.AlignCenter()`, and `.AlignMiddle()`

**Comment by leandrobattochio** [comment]
I'm referring to the white gap between cells.
This is my code:
![image](https://github.com/QuestPDF/QuestPDF/assets/1385182/3455a2ff-a2e5-496e-b765-e95e6fe8f900)

And the result:
![image](https://github.com/QuestPDF/QuestPDF/assets/1385182/198c11f5-6897-4165-aa52-d5c9058cab9a)


Still no white gaps. The padding does not do the job also. Am I missing something?

**Comment by girlpunk** [comment]
Using the first cell from your code as an example
```csharp
table.Cell()
    .Padding(6)
    .Background("#16365c")
    .BorderColor("#ff0000") // Change or remove as needed
    .Border("0.2f")
    .AlignCenter()
    .AlignMiddle()
    .Text("Content goes here")
```

Effects are applied in the order they are specified. In this case, so specifying the padding before the background colour is important.

**Comment by leandrobattochio** [comment]
Wow, works like a charm thanks. Just wondering, I should do this for all cells, right? Isn't there something like a default table style where I can set this only once?

**Comment by girlpunk** [comment]
You could make a wrapper for the `Table` class that applies this to every cell (which may be useful if you want to standardise styles across an entire document), but at the moment it's not an option to set at the table level.

@MarcinZiabek Thoughts on adding that as a feature?

**Comment by leandrobattochio** [comment]
I think something like the ColumnsDefinition method would be cleaner. I'll try to get my head around the source code, I'm not very familiarized with this kind of pattern... But I bet @MarcinZiabek could do this in a blink of an eye lol

But no worries then, I'll either make a wrapper or just add in every cell.

**Comment by MarcinZiabek** [comment]
I have been thinking about this idea for a couple of days. Indeed, implementing a default child style for elements such as Column, Row, Inlined, Table is rather simple. It may work as simple decoration, additional layout structure put in between. The difficulty is, it may not be possible to undone such default style once applied, e.g. border.

However, let me propose an alternative. You can declare default cell styles using local functions:

```csharp
IContainer CellStyle(IContainer container)
{
    return container
        .Padding(6)
        .Background("#16365c")
        .BorderColor("#ff0000") // Change or remove as needed
        .Border("0.2f")
        .AlignCenter()
        .AlignMiddle();
}
```

And then use it as follows:

```csharp
table.Cell().Element(CellStyle).Text("myText");
```

If the style is common across multiple documents, you can even create an extension method. Please read more about this technique here: https://www.questpdf.com/concepts/creating-dsl.html

**Comment by leandrobattochio** [comment]
Awesome idea! I haven't thought about it this way.

**Comment by jaguarxii** [comment]
Hi, I know its a bit old but I am trying to centralise the "cell formatting" of my documents that can have dynamic definitions, i.e. borders, alignments not only for columns but also certain cells can have its own format.

I am trying to implement a DSL extension, but cannot make it work, I don't know if this is possible by using this approach.

I end up receiving an error "You should not assign multiple child elements to a single-child container....", perhaps is something simple to chain the definitions to the current container but it is not clear in the documentation.

![image](https://github.com/user-attachments/assets/ea892aef-23b4-4c5f-8811-1d255233c1ea)

**Comment by girlpunk** [comment]
The documentation is correct, operations on containers need to be chained and multiple operations not performed on a single container instance. From your example, changing line 10 to `cellContainer = cellContainer.Border(2, Unit.Mil);` (and similar changes elsewhere) will resolve the issue.
