### ISSUE TITLE
Same border value is rendered differently

### ISSUE THREAD

**Issue by troncomputers** [QuestPDF/QuestPDF#623]
Hi!
All of these border lines have same size/width which is `0.1` / `Unit.Point`. Why it looks so different?
![Zrzut ekranu 2023-08-04 150658](https://github.com/QuestPDF/QuestPDF/assets/29543667/05550622-6de8-44d1-8dcb-420bc2fd905d)

**Comment by girlpunk** [comment]
Hi, are you able to share the source code used to generate this? Thanks

**Comment by MarcinZiabek** [comment]
0.1 point thick line is barely visible (only 0.035 mm). You need to zoom in significantly to render that line correctly (up to the point where 2 inches of your document are visible on the entire FullHD screen). With such thin lines, depending on your PDF previewer application, certain visual artifacts could be visible.

A good alternative is to use thicker lines (e.g. 1 point thick) but of lighter color (e.g. `Colors.Grey.Lighten3`).

**Comment by troncomputers** [comment]
That is a fair advice but... I think there is something else wrong and issue is based probably on DPI/Resolution, which is impossible to fix 🤔

**BEFORE ZOOM** - lines where `1,0000` text is are much thicker than the rest and the smallest table has like randomly generated thickness all over the place
![Zrzut ekranu 2023-08-07 072620](https://github.com/QuestPDF/QuestPDF/assets/29543667/e020026e-2610-420e-9d56-f0ed26837796)

**AFTER ZOOM** 
![Zrzut ekranu 2023-08-07 073102](https://github.com/QuestPDF/QuestPDF/assets/29543667/9f9bcf07-1a64-4850-b0de-b5ccb5690c46)

PS.
The **after zoom** looks even more different here when not open in seperate tab. All borders have 1 point of thickness and color `Grey.Lighten1`

**Comment by MarcinZiabek** [comment]
Please share the code used to generate the table. I am happy to investigate 😀

**Comment by troncomputers** [comment]
Fixed with thicker borders
