### ISSUE TITLE
Error: QuestPDF.Drawing.Exceptions.DocumentComposeException: Cannot load or decode provided image.

### ISSUE THREAD

**Issue by agilealtitude** [QuestPDF/QuestPDF#624]
When I try to implement an image as either byte[], stream, or even a Placeholders.Image, I get the following error:

**"Error: QuestPDF.Drawing.Exceptions.DocumentComposeException: Cannot load or decode provided image."**

At first, I thought I was providing bad data, however, even the Placeholders.Image causes the error.

I'm developing on a Mac using JetBrains Rider. I have installed the QuestPDF Nuget package.

Given the error description, is there a secret trick or any guidance that I can use to overcome this issue?
<img width="1186" alt="Screenshot 2023-08-08 at 5 08 56 PM" src="https://github.com/QuestPDF/QuestPDF/assets/47539548/fc34cae1-22a3-4712-8d09-61e617c18a59">

**Comment by MarcinZiabek** [comment]
Hi :) Please share a code snippet showing how you use the Image API. Feel free also to check this project that generates an invoice with an image: https://github.com/QuestPDF/QuestPDF-ExampleInvoice

I cannot reproduce the issue on MacOS with M2 and Rider.
