### ISSUE TITLE
Unable to set image size

### ISSUE THREAD

**Issue by XueDee123** [QuestPDF/QuestPDF#625]
This is not a bug，I wanted to set the image size freely, but I found that the image had to be set according to the zoom ratio, so that the image displayed in a row would not be full, resulting in empty Spaces, and if I forced the length and width to be set, I would report an error layout exception，By looking at the source code, I found that the proportion is calculated according to the length and width of the picture, can not be modified externally, whether you can get other ways to achieve open interface

**To Reproduce**
```
t2.Cell().Height(240).Table(t2_1 =>
                    {
                        t2_1.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                        });
                        if(Model!.TestReportInfo!.Image!=null)
                        {
                            byte[] imageBytes = Convert.FromBase64String(Model!.TestReportInfo!.Image);
                            t2_1.Cell().Image(Image.FromBinaryData(imageBytes)).WithRasterDpi(98).WithCompressionQuality( ImageCompressionQuality.High).FitArea();
                        }
                    });
```

**Expected behavior**
I want the freedom to set the size of the image even if it is distorted，Can you add a configuration to adapt the aspect ratio based on the external container size

**Screenshots**
![20230809181610](https://github.com/QuestPDF/QuestPDF/assets/59790386/97387431-0932-46d5-8c32-c92e4fc72de2)

**Additional context**

**Comment by MarcinZiabek** [comment]
Please use the`FitUnproportionally` API: https://www.questpdf.com/api-reference/image.html#image-scaling It completly ignores the image's aspect ratio.

**Comment by XueDee123** [comment]
> 你好 😀
> 
> 请使用 API：https://www.questpdf.com/api-reference/image.html#image-scaling。它完全忽略图像的纵横比。`FitUnproportionally`
Hi, I tried the FitUnproportionally method you mentioned, but reported the abnormal layout error, I really have no way, I can only modify the aspect ratio myself
```
  t2.Cell().Height(240).Table(t2_1 =>
                    {
                        t2_1.ColumnsDefinition(columns =>
                        {
                            columns.ConstantColumn((PageSizes.A4.Width - 26) / 5 * 3);
                            columns.ConstantColumn((PageSizes.A4.Width - 26) / 5);
                            columns.ConstantColumn((PageSizes.A4.Width - 26) / 5);
                        });
                        if (Model!.TestReportInfo!.Image != null)
                        {
                            t2_1.Cell().ColumnSpan((uint)(Model!.DisplayBlood ? 1 : 3)).Image(Image.FromBinaryData(Convert.FromBase64String(Model!.TestReportInfo!.Image))).WithRasterDpi(98).WithCompressionQuality(ImageCompressionQuality.High).FitHeight().SetRatio(Model!.DisplayBlood ? ((PageSizes.A4.Width - 26) / 5 * 3 / 240) : ((PageSizes.A4.Width - 26) / 240));
                        }
});
```
I added a new method to the source code
```
public ImageDescriptor SetRatio(float ratio)
        {
            AspectRatioElement.Ratio = ratio;
            return this;
        }
```
My requirement is that my picture can be stretched adaptively according to the size of the external container, even if it is deformed. I know that my way is awkward, but this is a way to solve my problem at present, and I look forward to a better way to achieve it

**Comment by MarcinZiabek** [comment]
Thank you so much for the clarification! 

I am considering changing the default behavior of the `Image` element when using the `FitUnproportionally` option. Instead of using all available space (and usually causing layout exceptions), it should report minimal space requirements and fit only space provided by its parent. I need to investigate further if there are any breaking changes.

If I decide to follow this change, it will be released as a bug fix to the latest stable release.

**Comment by XueDee123** [comment]
> 

Thank you and look forward to the new version. I will close comment after the update

**Comment by MarcinZiabek** [comment]
@XueDee123 Hello 😀 Apologies for the delay in addressing this. Took a bit longer than expected, but I wanted to double-check the image content functionality to avoid any breaking changes. Good news: the update is now live in the 2023.6.2 release. Happy coding!

**Comment by XueDee123** [comment]
> @XueDee123 Hello 😀 Apologies for the delay in addressing this. Took a bit longer than expected, but I wanted to double-check the image content functionality to avoid any breaking changes. Good news: the update is now live in the 2023.6.2 release. Happy coding!

Thank you very much.
