### ISSUE TITLE
Please stop calling the project "open-source"

### ISSUE THREAD

**Issue by ironsm4sh** [QuestPDF/QuestPDF#627]
In multiple places, QuestPDF is called "open-source". An example of this can be found in the project's `README.md`
> QuestPDF is a modern **open-source** .NET library for PDF document generation. Offering comprehensive layout engine powered by concise and discoverable C# Fluent API.

However, the license is **not** [open-source](https://opensource.org/osd/). Your license clearly states the following:
> Companies with an annual gross revenue exceeding $1M USD are required to purchase a paid license

The definition of the word open-source almost always refers to the term defined by the [OSI](https://opensource.org/about/). The restriction on gross revenue is clearly incompatible with the first OSI criteria:
> **1. Free Redistribution**
> The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale.

Please stop using the term "open-source" to describe your project.

**Comment by MarcinZiabek** [comment]
Hello 😀

First and foremost, I want to sincerely apologize for the delayed response.

Thank you for taking the time to raise your concerns about the licensing and communication surrounding QuestPDF.

To provide some context, QuestPDF was available purely under the MIT license for over two years. The recent license update was introduced after extensive discussions within our community, including comments and survey results, to ensure that a broad spectrum of opinions is considered. While it's challenging to accommodate everyone's perspective, our primary goal was to keep the license simple and optimize its benefits for both the .NET Community and businesses. 

I will describe my entire perspective and experience sometime in the future, once I validate that my understanding is accurate.

Although our current license closely follows the open-source spirit, I acknowledge it doesn't align perfectly with any of OSI's recommended licenses. I believe that the current approach may be called "modern-open-source" at some point in the future. For a deeper understanding of our licensing philosophy, please refer to https://www.questpdf.com/license/guide.html.

As you have mentioned, the term "open-source" has various definitions, with OSIs being prominent. Please be assured that I do not intend to mislead anyone; our license terms are transparently outlined in multiple locations. My primary objective is to continue offering the Community maximum value in a way that I believe is the most optimal.

Warm regards,
Marcin

**Comment by ironsm4sh** [comment]
Hello,

Thanks for taking your time to reply to my comment. While I still think that the wording used is incorrect; I have decided that I simply do not care.

Greetings,
Iron
