### ISSUE TITLE
Open Existing PDF

### ISSUE THREAD

**Issue by michaelakin** [QuestPDF/QuestPDF#628]
**Is your feature request related to a problem? Please describe.**
Hi, I am trying to open existing PDF's to merge into a larger PDF, but I cannot figure out how to do that.  Is that an option with QuestPDF?

**Describe the solution you'd like**
I would like to create a new pdf and do the following:
- Add new pages that contain an Image file 
- Merge existing PDF's into the new PDF
- Then create an image and thumbnail for each page of the image.

**Describe alternatives you've considered**
I have looked in the documentation and cannot find how to open an existing PDF.  Other solutions are to go with another package of some sort, but all I can find are expensive options.

**Additional context**
n/a

**Comment by girlpunk** [comment]
Hi,

Unfortunately merging or otherwise editing existing PDFs is not currently possible with this library (https://github.com/QuestPDF/QuestPDF/issues/113). You may be able to achieve what you're looking for with [PdfPig](https://uglytoad.github.io/PdfPig/)?

**Comment by bretbas** [comment]
Hello. Is it possible to open a pdf file through your library and ultimately convert each page in the pdf file into an image?

**Comment by michaelakin** [comment]
> Hello. Is it possible to open a pdf file through your library and ultimately convert each page in the pdf file into an image?

Not with this library.    If you want to do that, it is possible to use [ImageMagick](https://imagemagick.org/)   or I ended up having  to purchase [Aspose PDF](https://products.aspose.com/pdf/) because I wanted to keep it all in memory and not use temporary disk space.
