### ISSUE TITLE
PageSizes.Letter / PageSizes.Legal Incorrect?

### ISSUE THREAD

**Issue by markhewett** [QuestPDF/QuestPDF#63]
**Describe the bug**
When using the `PageSizes.Letter` helper, Adobe Acrobat Reader shows that the page is not the correct size.  It shows 8.50 x 10.99 in.  US Letter paper is 8.5 x 11 in.

At 72 points per inch, it seems like letter should be defined as `new PageSize(612f, 792f)` (8.5 and 11 * 72, respectively), but it is currently coded as `new PageSize(612.4f, 791f)`.

Similarly, `PageSizes.Legal` results in 8.50 x 14.01 in, instead of 8.50 x 14.00 in.  That should probably be `new PageSize(612f, 1008f)`.

**To Reproduce**
```
class MyDoc : IDocument
{
	public DocumentMetadata GetMetadata()
	{
		return DocumentMetadata.Default;
	}
	
	public void Compose(IDocumentContainer container)
	{
		container.Page(page =>
		{
			page.Size(PageSizes.Letter);
			page.Margin(50);
			page.Header().Height(100).Background(Colors.Grey.Lighten1);
			page.Content().Background(Colors.Grey.Lighten3);
			page.Footer().Height(50).Background(Colors.Grey.Lighten1);
		});
	}
}
```

**Expected behavior**
The page size should be 8.5 x 11 in when using the `PageSizes.Letter` helper, and 8.5 x 14 in when using `PagesSizes.Legal`.

**Screenshots**
n/a

**Additional context**
This is my first time trying out QuestPDF, so it's entirely possible that I did something wrong!

**Comment by MarcinZiabek** [comment]
Thank you for finding this issue. It is very possible that some values may be wrong. I'm not sure from where current values came from. Would you be able to provide a pull request with a fix? 😁

**Comment by MarcinZiabek** [comment]
Please also note that `PageSizes` class is only a set of helpers. You can always provide your own, custom size. Just saying in case it is a blocking issue for you.

**Comment by markhewett** [comment]
I submitted a pull request with just the tweaks to the page sizes.  I tested in my test project and it worked OK, but I don't know if there are any unit tests that need updating - I got some errors when I ran `dotnet test` before making any changes. :-/
