### ISSUE TITLE
[Question/Help] Elements on entire page sides - SOLVED!

### ISSUE THREAD

**Issue by salixzs** [QuestPDF/QuestPDF#630]
I have a requirement to have specific elements on left and right page sides, like this (in red):
![image](https://github.com/QuestPDF/QuestPDF/assets/3694770/7d920fb6-7186-48ac-97b8-05959daefa96)
As these are located outside of `page` area and spans entire length of `Header(), Content()` and `Footer()` parts of the page, I cannot figure out whether it is possible at all.

Do you have any hints or approaches how this can be achieved (if possible)?

**Comment by girlpunk** [comment]
I'd suggest using an additional layer to position the elements, in conjunction with `.RotateLeft()` and `.RotateRight()`, `.TranslateX()` and `.TranslateY()`, and possibly also some negative `.Padding()`

**Comment by salixzs** [comment]
I managed to achieve it with `Unconstrained()` element.
As I had Footer the most stable element in layout in regard to static location, Adding additional unconstrained columns with necessary settings did the thing:
```c#
private void ComposeFooter(IContainer container) =>
    container.Column(column =>
    {
        column.Item().Row(row =>
        {
            // Actual Footer contents
        });

        var printableAreaHeight =
            PageSizes.A4.Portrait().Height -
                TopMarginCentimetre.ToPoints(Unit.Centimetre) -
                BottomMarginCentimetre.ToPoints(Unit.Centimetre);
        var printableAreaWidth =
            PageSizes.A4.Portrait().Width -
                2f.ToPoints(Unit.Centimetre) -
                2f.ToPoints(Unit.Centimetre);

        // Left side rotated text with line
        column
            .Item()
            .Unconstrained()
            .TranslateX(-35)
            .TranslateY(-printableAreaHeight)
            .Width(14)
            .Height(printableAreaHeight)
            .RotateRight()
            .Row(row =>
            {
                row.AutoItem().AlignBottom().Text("COMPANYNAME");
                row.RelativeItem().BorderBottom(0.7f);
            })
            ;

        // Right side rotated text with line
        column
            .Item()
            .Unconstrained()
            .TranslateX(printableAreaWidth + 10)
            .TranslateY(-printableAreaHeight)
            .Width(14)
            .Height(printableAreaHeight)
            .RotateLeft()
            .Row(row =>
            {
                row.AutoItem().AlignBottom().Text("COMPANYNAME");
                row.RelativeItem().BorderBottom(0.7f);
            });
    });
```

Hope it will help someone with similar needs in future.
Big thanks for this library!

**Comment by MarcinZiabek** [comment]
Hey there! I'm sorry for the late response. I took some time to experiment with the layout. I have published my attempt in the documentation so others can benefit from it as well. Please take a look here: https://www.questpdf.com/api-reference/page.html#watermark-slots.
