### ISSUE TITLE
Table with cell that extends to multiple page is not formatting properly.

### ISSUE THREAD

**Issue by LeRoy91** [QuestPDF/QuestPDF#631]
**Describe the bug**
When building a simple 2 column table, one of the cells will extend over multiple pages. The sample data will extend the cell across 5 pages.  The problem occurs on page 3 of the cell extension.  On page 3 all previous rows of the table are repeated before the cell continues to expand

**To Reproduce**
See sample code

**Expected behavior**
I would expect the cell to simply expand and not repeat rows. 

**Screenshots**
See Tester.pdf

**Additional context**
[Tester.pdf](https://github.com/QuestPDF/QuestPDF/files/12396913/Tester.pdf)
[SampleCode.txt](https://github.com/QuestPDF/QuestPDF/files/12396916/SampleCode.txt)

**Comment by girlpunk** [comment]
Hi,

This is expected default behaviour for the table component. To achieve what you want, use `ShowOnce()`
https://www.questpdf.com/api-reference/show-once.html

**Comment by LeRoy91** [comment]
Thanks, that worked.
