### ISSUE TITLE
TextDescriptor.Line(string text) inserting \r\n at the end of string

### ISSUE THREAD

**Issue by troncomputers** [QuestPDF/QuestPDF#647]
Hi.
I've implemented a `<br>` tag to my code that will break the text at specific point, but there is an issue with `Line()` because it's adding `\r\n` at the end event if I do a `Replace()` in my string

**CODE**
```C#
string[] lines = data.Split("<br>");
foreach (var line in lines)
{
   string currentLine = line;
   int index = lines.ToList().IndexOf(currentLine);
   if(index == lines.Length - 1)
       currentLine = currentLine.Replace("\r\n", string.Empty);
   text.Line(currentLine).Style(style);
}
```

**RESULT**
```
77,00
94,71

```
![Zrzut ekranu 2023-09-19 131349](https://github.com/QuestPDF/QuestPDF/assets/29543667/f3357bb0-c43d-45e8-8ec9-4c8774de98f4)

**Comment by MarcinZiabek** [comment]
This is correct. If the described behavior is not desired, please use the `text.Span()` method that does not concatenate any additional text.

**Comment by troncomputers** [comment]
Works fine with `text.Span() + Environment.NewLine`. Thx ✌️
