### ISSUE TITLE
Document how to use QuestPDF in WebAssembly

### ISSUE THREAD

**Issue by pablopioli** [QuestPDF/QuestPDF#67]
If found QuestPDF just recently and I think it's awesome. 

I saw that the native libraries for WASM are available as a preview, so I thought on testing if QuestPDF would work in a Blazor WebAssembly app. 

It worked without problems, creating the files 100% inside the browser. The only gotcha is that you can't embed a font as the sandbox would not allow it.

So, this is not really an issue. I would like to know how can I help to document what you need to do to use it in Wasm.

A sample would help, more documentation on the subject?

**Comment by MarcinZiabek** [comment]
Thank you for your comment and being open to help, I really appreciate it!

As I haven't worked with WASM yet, I don't have much experience in this regard. I would like to ask you to create a pull request to the [documentation repository](https://github.com/QuestPDF/QuestPDF-Documentation). Please describe anything that could be useful for other developers. Especially if there are any unexpected issues or problems. I propose to include this information in [the Patterns and Practices section](https://www.questpdf.com/documentation/patterns-and-practices.html#page-settings). It uses vuepress and documentation is written in markdown.

Generally, QuestPDF should work on any dotnet environment as long as SkiaSharp is also functional there. I expect that 99% of potential problems and limitations come from the SkiaSharp dependency. It is not Skia fault, we just need to be aware of it. So, usually, we want to point developers to proper patterns and practices in this regard 😁

**Comment by pablopioli** [comment]
Great! I will test it thoroughly and build a pull request.

If there is something missing we can discuss it in the PR. 

Thanks to you for sharing your great work.
