### ISSUE TITLE
Exception related to skiaSharp-related library

### ISSUE THREAD

**Issue by DBrdak** [QuestPDF/QuestPDF#676]
Hi, I'm facing an issue with missing dependency I think. I'm running my api in docker-compose in microservices architecure and when trying to generate pdf, getting this error: 

`Cannot create the PDF document using the SkiaSharp-related library. This exception usually means that, on your operating system where you run the application, SkiaSharp-related requires installing additional dependencies. Such dependencies are available as additional nuget packages, for example *.NativeAssets.Linux.NoDependencies. Some operating systems may require installing multiple nugets, e.g. MacOS may need both *.NativeAssets.macOS.NoDependencies and *.NativeAssets.Linux.NoDependencies.Please refer to the SkiaSharp-related documentation for more details. Also, please consult the inner exception that has been originally thrown by the dependency library.`

And deeper in stack trace:

`System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies.`
`libfontconfig.so.1: cannot open shared object file: No such file or directory /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.12/libSkiaSharp.so: cannot open shared object file: No such file or directory`

I've tried to install both libraries, NativeAssets.Linux.NoDependencies and NativeAssets.Linux, either solo and both in one time. Also I was searching for solution, and found a few topics, so I've also tried to add this to dockerfile:

`RUN apt-get update`
`RUN apt-get install -y libfreetype6`
`RUN apt-get install -y libfontconfig1`
`RUN apk update \`
`    && apk --no-cache add icu-libs fontconfig ttf-dejavu`

In the end, none of these solutions helped me, after looking to docker files of my service, I see that there is libSkiaSharp.so in app/bin/Debug/net7.0/runtimes/linux-arm/native/libSkiaSharp.so and there is not in here: /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.12/libSkiaSharp.so

I'll be grateful for any help, I would like to use your library, after testing almost every pdf generator I'm not seeing any other option, QuestPDF is honestly the best. 

Thank you

**Comment by DBrdak** [comment]
Ok, I've resolved it by reading #667 and found it: HarfBuzzSharp.NativeAssets.Linux. After adding this package, everything works fine

**Comment by MarcinZiabek** [comment]
I wonder why the exception says `SkiaSharp-related` (which is a default, fallback value)

Technically, there already is [logic that should detect if the exception is about SkiaSharp or HarfbuzzSharp](https://github.com/QuestPDF/QuestPDF/blob/main/Source/QuestPDF/Drawing/Exceptions/InitializationException.cs), and then provide a more detailed message. The logic is quite simple, just checking if a given keyword is present in the exception message text.

`libSkiaSharp` corresponds to SkiaSharp, while `libHarfBuzzSharp` to HarfBuzzSharp. 

Also, it is unexpected that the exception was saying `libSkiaSharp` but you needed to install `HarfBuzzSharp.NativeAssets.Linux` to resolve the issue.
