### ISSUE TITLE
Image without scaling, unless needed?

### ISSUE THREAD

**Issue by Riboe** [QuestPDF/QuestPDF#680]
Hi,

I'm trying to create a PDF, which will contain a bunch of images.

These images vary greatly in size. Some of them need to be scaled down to fit the width of the page, which the default scaling strategy does already.  
However, some of them do not need to be scaled at all, but I cannot figure out how to render an image without scaling.

Basically how can I render an image like this?:
![image](https://github.com/QuestPDF/QuestPDF/assets/3437394/f3dcce3a-0df3-47b5-94e5-17a85677d78c)

The above is made with HTML to illustrate what I need.
You can see the page, which has some margins set and the blue border represents the item containing the image. The item fills the entire width of the page, as you'd expect.
The image itself isn't large enough to fill the width of the page, so it just takes up whatever space it needs and no more.
To be clear, I am not interested in drawing the blue border. It's just there for illustrative purposes.

I know the image width and height in pixels, so my first thought was to simply use the `.Width()` container element, but it does not accept pixels as a unit.

The code I have so far is basically just:

```c#
public void Compose(IDocumentContainer container)
{
    container.Page(page =>
    {
        page.Margin(1, Unit.Inch);
        
        page.Content().Column(column =>
        {
           byte[] image = ...; // not important.
           column.Item().Image(image);
        });
    });
}
```

The code works well for large images that are then scaled down to fit the width of the page, but how do I prevent smaller images from scaling up, when I don't know their sizes in any unit supported by QuestPDF?

**Comment by MarcinZiabek** [comment]
Generally speaking, translating resolution (pixels) to physical size (points) does not make sense, as the conversion logic depends on the DPI and is related to final visual fidelity. 

You can make certain assumptions yourself. In the PDF world, 1 inch = 72 points. Then you can choose the DPI value - usually around 300 for printed documents. QuestPDF uses 288 by default (4 * 72 = 288) when scaling down images. 

Then, calculating physical size is easy. Example for an image of width 1024px: `1024 / 288 * 72 = 256pt`

**Comment by Riboe** [comment]
I see, that makes sense.

In the end, I ended up solving it in a slightly different way, but I wouldn't have thought of it without your input.

I'm building a visual report editor/builder and in the HTML, I have a `div` that represents the paper and as such, it has a fixed with of 210 millimeters, matching the standard of an A4 paper.

HTML already converts those 210 millimeters to pixels, so it was just a matter of calculating how much many millimeters there is in a pixel (dividing those two numbers) and multiplying the result with the pixel width of the image element to get an accurate millimeter width, that I can then use when generating the PDF.

Thanks for the swift reply and clear explanation!
