### ISSUE TITLE
Is it possible to generate header with dynamic content on every page?

### ISSUE THREAD

**Issue by sakopov** [QuestPDF/QuestPDF#681]
I'm building a long invoice consisting of multiple sections. I'm trying to add dynamic content to the header which changes with every page to display information about each section. The content is a list of string which gets outputted as text elements. 

I tried implementing a dynamic component and sharing a state object called `HeaderStateProvider` which would be updated with header values as each invoice section is built, but I end up with headers which only display the last list of values in `HeaderStateProvider`. Does anybody know if something like this is possible to achieve?

```csharp
    public struct HeaderState
    {
        public List<string> Items;

        public HeaderState(List<string> items)
        {
            Items = items;
        }
    }
    
    public sealed class HeaderStateProvider
    {
        public IEnumerable<string> Items { get; set; } = new List<string>();
    }
```

The dynamic component:

```csharp
    public class DynamicHeader : IDynamicComponent<HeaderState>
    {
        public HeaderState State { get; set; }

        private readonly HeaderStateProvider _provider;

        public DynamicHeader(HeaderStateProvider headerState)
        {
            _provider = headerState;

            State = new HeaderState(_provider.Items.ToList());
        }

        public DynamicComponentComposeResult Compose(DynamicContext context)
        {
            var content = context.CreateElement(element =>
            {
                element
                    .Border(1)
                    .BorderColor("#03243e")
                    .Background("#03243e")
                    .Padding(5)
                    .DefaultTextStyle(style => style.FontColor("#ffffff").FontSize(10))
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        table.Cell()
                            .AlignLeft()
                            .AlignMiddle()
                            .Width(100)
                            .Image(File.ReadAllBytes("logo.png"))
                            .FitArea();

                        table.Cell()
                            .AlignTop()
                            .AlignRight()
                            .Column(col =>
                            {
                                foreach (var item in State.Items)
                                {
                                    col.Item().PaddingVertical(1).Text(item);
                                }
                            });
                    });
            });

            State = new HeaderState(_provider.Items.ToList());

            return new DynamicComponentComposeResult()
            {
                Content = content,
                HasMoreContent = false
            };
        }
    }
```

**Comment by sakopov** [comment]
After looking into this for an entire day I came to the conclusion that dynamic component feature is just too limiting to be able to support this in scenarios where the content portion of the document is one continuous stream of elements.

**Comment by MarcinZiabek** [comment]
The DynamicComponent should fully support your use case. If your content spans multiple pages, you must manually divide the content across the pages, usually by measuring children's sizes and detecting how many will fit on a page. Unfortunately, it is a rather complex requirement.

Please analyze the following example that shows how to achieve per-page totals for an invoice: https://www.questpdf.com/concepts/dynamic-components.html#table-with-per-page-totals

The `State` object is used internally by the library. Use it to store the current state of the component (e.g., how many items are already displayed), but do not use it anywhere outside of the component. The library may dynamically change state value while performing layout measurements.
