### ISSUE TITLE
Support for making a Grid cell spanning multiple rows/columns

### ISSUE THREAD

**Issue by hungnd1475** [QuestPDF/QuestPDF#69]
**Is your feature request related to a problem? Please describe.**
After finding out about this awesome library, I tried to port an existing solution we have to generate reports in our company. We use Puppeteer to generate PDFs from HTMLs produced by a template engine. The HTML template heavily utilises CSS `grid` and `grid-area` to make a cell spanning multiple rows/columns. However, it seems like your library doesn't support this for `Grid`, or at least that is what I can see from reading the documentation.

**Describe the solution you'd like**
The ability to make a `Grid`'s cell spanning multiple rows/columns.

**Describe alternatives you've considered**
An alternative that I can think of is to manually compose the cells without using `Grid`, but it would be very tedious.

**Comment by MarcinZiabek** [comment]
Hello 😁 Could you please take a look [at this article](https://www.questpdf.com/documentation/patterns-and-practices.html#complex-layouts-and-grids) and let me know what do you think? 

Having cells spanning multiple rows/columns can be challenging, especially in conjunction with the paging support. Would you like to discuss first the Fluent API that you expect to be available? Then we can slowly build feature requirements.

**Comment by hungnd1475** [comment]
Hi Marcin, thanks for pointing that out, I must've missed it while reading your documentation. Anyway, let me play around with it a bit to see if it can solve our problem.

**Comment by hungnd1475** [comment]
Just wanted to update you that I'm able to port our HTML layout to your library by following the article you send, so I'm closing this now.
