### ISSUE TITLE
Any Plan to upgrade to .Net 7/ 8(Its upcomming)?

### ISSUE THREAD

**Issue by ks1990cn** [QuestPDF/QuestPDF#699]
Any Plan to upgrade to .Net 7/ 8(Its upcomming)?

**Comment by MarcinZiabek** [comment]
The library is already fully compatible with dotnet 7 and 8. We are considering building an additional artifact for dotnet 8 once it reaches stable release.

Do you see any important reasons for adding support for additional targets?

**Comment by ks1990cn** [comment]
> The library is already fully compatible with dotnet 7 and 8. We are considering building an additional artifact for dotnet 8 once it reaches stable release.
> 
> Do you see any important reasons for adding support for additional targets?

Just wanted to check if we are moving ahead with latest versions or this repo is in stage to get archieved.

**Comment by MarcinZiabek** [comment]
> Just wanted to check if we are moving ahead with latest versions or this repo is in stage to get archieved.

It's quite the opposite 😀 There are numerous enhancements on the upcoming roadmap!
