### ISSUE TITLE
Merging same document ends up adding 1 to total page count

### ISSUE THREAD

**Issue by luisabreu** [QuestPDF/QuestPDF#704]
Merging the same container twice (Document.Merge) ends up adding 1 to the total page count of each report even though the visible pages are correct. In this example, we have 3 pages, and total count returns 4 (but the previewer shows only 3 pages - there's no empty page). If I show the preview for the original container, the total page number is correct. 

Demo code for this issue is available here https://github.com/luisabreu/questpdfdemo

**Comment by PALILIPA** [comment]
Hello, I have the same problem.I have checked everythingvand and was happy when I have found your report.

**Comment by MarcinZiabek** [comment]
Hi :) Thank you for finding and reporting this issue, especially for providing a minimal example. I confirm that the bug exists. - I am working on it now.

**Comment by luisabreu** [comment]
Thanks a lot for fixing this. Any timeframe for getting the nuget package updated? Thanks again.

**Comment by aldahiraguilar** [comment]
Hi, I am facing a similar issue, when merging multiple different documents it always says "Page 1 of 2". Could it be related? It previously worked well

**Comment by PALILIPA** [comment]
For me, the last version has fixed everything !
Thanks

Le lun. 20 nov. 2023 à 18:59, aldahiraguilar ***@***.***> a
écrit :
