### ISSUE TITLE
DocumentDrawingException when using FitHeight with some image sizes

### ISSUE THREAD

**Issue by MohamedA-Ibrahim** [QuestPDF/QuestPDF#709]
**Describe the bug**
When you add an image using byte[], path, or from stream for some image sizes and use FitHeight with it, it raises QuestPDF.Drawing.Exceptions.DocumentDrawingException

**Inner Exception:**
ArgumentNullException: Value cannot be null. (Parameter 'bitmap')

**Stacktrace:**
`QuestPDF.Drawing.Exceptions.DocumentDrawingException
  HResult=0x80131500
  Message=An exception occured during document drawing.
  Source=QuestPDF
  StackTrace:
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, ContainerElement content)
   at QuestPDF.Drawing.DocumentGenerator.RenderSingleDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at Test.GenerateFromImage() in C:\Users\HP\source\repos\TestQuestPdf\TestQuestPdf\Program.cs:line 40
   at Program.<Main>$(String[] args) in C:\Users\HP\source\repos\TestQuestPdf\TestQuestPdf\Program.cs:line 8 `

**To Reproduce**
```csharp
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

QuestPDF.Settings.License = LicenseType.Community;

Test.GenerateFromImage();

Console.ReadLine();

static class Test
{
    public static void GenerateFromImage()
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
            
                page.Content()
                .Column(column =>
                {
                    column.Item().Row(row =>
                    {
                       byte[] byteImage = File.ReadAllBytes("300.png");
                       byte[] byteImageLarge = File.ReadAllBytes("1024.png");

                       //This works
                        row.RelativeItem().Image(byteImageLarge).FitHeight();

                         //All three ways of importing an image fails
                        row.RelativeItem().Image(byteImage).FitHeight();
                        //row.RelativeItem().Image("300.png").FitHeight();
                        
                       // using var stream = new FileStream("300.png", FileMode.Open);
                        //row.RelativeItem().Image(stream).FitHeight();
                    });

                   
                });
            });
        });


        document.GeneratePdf("document.pdf");
    }
}
```

**Expected behavior**
The method should be called and applied correctly without raising exceptions.

**Additional context**
- This only happens with images with small height.
- This only happens with FitHeight and doesn't happen when using FitWidth, FitArea or FitUnproportionally

**Sample Images**
![1024](https://github.com/QuestPDF/QuestPDF/assets/39552203/9aead529-b544-4bc2-a68f-755bf775cb95)
![300](https://github.com/QuestPDF/QuestPDF/assets/39552203/de8153aa-5d75-48a5-afcc-cd96ce505d87)

**Comment by MarcinZiabek** [comment]
Most likely, it is partially expected behavior. Depending on available space and the image's aspect ratio, specific scaling options may result in layout constraints that are impossible to meet, resulting in layout exceptions. The method of loading the image is not related. 

However, it should be clearly communicated as a layout issue. I am working on a fix at this moment.
