### ISSUE TITLE
Add the ability to pass a cancellation token to the `ShowInPreviewerAsync` method

### ISSUE THREAD

**Issue by ricardoboss** [QuestPDF/QuestPDF#713]
**Is your feature request related to a problem? Please describe.**
For faster development, I created a special project just to start the previewer with some data from the actual data sources.

In this project, I create a `HostApplicationBuilder` that can - you guessed it - host a service. As my hosted service, I provide a class that generates an `IDocument` and calls `ShowInPreviewerAsync` in its `StartAsync` method (from `IHostedServer`).

Now, when stopping the service, I have no way to tell the previewer to disconnect or close down and the runtime waits until I press Ctrl+C again or kill the process.

In an otherwise fantastic DX (thanks to you!) this is a small hiccup in my workflow. Nothing major.

**Describe the solution you'd like**
I'd like to pass a cancellation token to the `ShowInPreviewerAsync` method that should disconnect and/or close the previewer when cancellation is requested.

**Describe alternatives you've considered**
The alternative is closing down the previewer/the process manually.

**Comment by MarcinZiabek** [comment]
Thank you for this awesome suggestion! It will undoubtedly be a part of the next release 😀
