### ISSUE TITLE
.NET 8 Support

### ISSUE THREAD

**Issue by schroedermarius** [QuestPDF/QuestPDF#714]
I am currently evaluating PDF or Report Libraries for a .NET 7 or .NET 8 Project.
Unfortunately the Roadmap you linked on reddit is not available anymore.

Are you planning to update the library to .NET8?

**Comment by marcmognol** [comment]
Hi @schroedermarius 

I can confirm you that QuestPDF library is working great in a project targeting net8.0 TFM.

Regards. Marc

**Comment by girlpunk** [comment]
I don't have anything updated to 8 yet, but can confirm it also works great in 7
