### ISSUE TITLE
Table Cell PaddingVertical Not Adhering To Right Border Styling

### ISSUE THREAD

**Issue by PlayerModu** [QuestPDF/QuestPDF#721]
I am struggling to get the right border of a table cell to wholly follow the border I've set. It looks like when the cell has vertical padding, the padding is adding whitespace into the border (see content-redacted image below) instead of it forming one clean vertical line between the two columns (which is what I want to achieve). 

@MarcinZiabek please can you advise if there another way to achieve this or if I'm doing something wrong? 

![image](https://github.com/QuestPDF/QuestPDF/assets/65035377/ecc79092-a30a-4e69-bd11-8f9a6f51eafe)

This is the code for each row (each column is set as Relative):

                    table
                        .Cell()
                        .Element(CellStyle)
                        .ShowEntire()
                        .PaddingLeft(20)
                        .PaddingRight(5)
                        .AlignLeft()
                        .Text($"{value}")
                        .Light()
                        .FontSize(13);
                    table
                        .Cell()
                        .Element(CellStyle)
                        .ShowEntire()
                        .PaddingLeft(60)
                        .AlignLeft()
                        .Text($"{value2}")
                        .Light()
                        .FontSize(13);

                    static IContainer CellStyle(IContainer container) => container
                        .PaddingVertical(5)
                        .BorderRight(1)
                        .BorderColor("#0079c8");

**Comment by PlayerModu** [comment]
This issue seems to be resolved by remove the paddingvertical from the container and adding .PaddingBottom to one of the cells

**Comment by girlpunk** [comment]
You may also find this works as expected when calling BorderColor and BorderRight before PaddingVertical. Elements are applied in the order they are defined, so the code above will apply the border 5pt below/above where is expected.

**Comment by MarcinZiabek** [comment]
> You may also find this works as expected when calling BorderColor and BorderRight before PaddingVertical. Elements are applied in the order they are defined, so the code above will apply the border 5pt below/above where is expected.

Your comment is spot on! Thank you!
