### ISSUE TITLE
Table row formatting but only for the first row of multi-page table

### ISSUE THREAD

**Issue by PlayerModu** [QuestPDF/QuestPDF#723]
Is there a way I can apply specific styling to the first row in a table if that table spans multiple pages? I can get it looking as I want for the first page but as I'm only picking it up manually by looking for the first entry in the iteration and applying the style to that manually, it then doesn't apply to the first row on page 2 or 3, 4, etc.. where the table continues.

I looked at setting the header bottom padding but as the heading has a background colour it's not achieving the right results with the then white rows in the table. If I could set a bottom margin on the header to push the top row down without extending down the styled cell of the header row (as I'm trying to do), then that would be ideal, but I cannot see how to do this :(

Please can you advise?

**Comment by PlayerModu** [comment]
I managed to mostly resolve this issue but re-working my table and providing set heights for the cells.

**Comment by MarcinZiabek** [comment]
@PlayerModu As I understand, you would like to define a table header displayed on every page, especially when your content spans multiple pages. You can do this with existing API: https://www.questpdf.com/api-reference/table.html#table-header-footer

If your requirements is different, please share more details. I am happy to help and/or extend available features.

**Comment by PlayerModu** [comment]
Hi @MarcinZiabek , not quite. This was asking to be able to set specific styling for the first row in every table on every page. But I realised I was approaching the problem the wrong way and setting a height for each row cell solved my problem perfectly ☺️
