### ISSUE TITLE
How to convert to Base64?

### ISSUE THREAD

**Issue by mhosman** [QuestPDF/QuestPDF#74]
How can I convert the result to base64? Thanks!

**Comment by MarcinZiabek** [comment]
This question is more about C# than the library itself, so let me keep my answer short 😀

You can use one of the QuestPDF overloads to get a stream of binary data - just provide a stream where the document will be written to. Then, you have a couple of choices. For example, you can materialize the stream into the binary array and use standard c# base64 conversion. Please note that the result may still be in the binary form (just a different kind), and you may need to convert it back to the text format.

**Comment by spoofermark21** [comment]
How can I convert base64 to image in quest?
