### ISSUE TITLE
Column spacing issues

### ISSUE THREAD

**Issue by Huangzc88** [QuestPDF/QuestPDF#745]
**Describe the bug**
I think it's a bit of a problem to set the spacing of columns, I want to make the spacing of some columns different from other columns, therefore, I set the spacing of some columns to 20 first, and then set the spacing of columns to 0, but the actual effect is that all the column spacing becomes 0. 

At the moment I can only solve this problem by setting PaddingBottom to the specified column.

**To Reproduce**

```
container.PaddingVertical(0).Column(column =>
 {
      column.Spacing(20);

      column.Item().Element(ComposeHeader);

      column.Item().Element(ComposeAddress);

      column.Item().PaddingBottom(20).Element(ComposeDetails);

      column.Spacing(0);

      column.Item().PageBreak(); 

      column.Item().Element(ComposeOther);
 });
```

**Environment**
v2023.12.1 on win10

**Additional context**
I like the design of QuestPDF very much, I feel that it is much easier to use than iTextSharp, but at present, I see a big problem is the pdf size problem caused by font citation, and I look forward to the improvement of this problem.

**Comment by girlpunk** [comment]
I believe this is expected behaviour, however as a workaround you could try something like this

```csharp
container.Column(column =>
{
    column.Item().PaddingBottom(10).Element(ComposeHeader);
    column.Item().PaddingVertical(10).Element(ComposeAddress);
    column.Item().PaddingVertical(10).Element(ComposeDetails);

    column.Item().PageBreak(); 

    column.Item().Element(ComposeOther);
});
```

Note that the padding applied here is half the expected outcome, as it is applied from elements on both sides of the gap.

Alternatively, layout containers can be nested:

```csharp
container.Column(column =>
{
    column.Item().Column(innerColumn =>
    {
        innerColumn.Spacing(20);
        column.Item().Element(ComposeHeader);
        column.Item().Element(ComposeAddress);
        column.Item().Element(ComposeDetails);
    });

    column.Item().PageBreak(); 

    column.Item().Element(ComposeOther);
});
```
