### ISSUE TITLE
incompatibility In Azure QuestPdf

### ISSUE THREAD

**Issue by joaopaulobiesek** [QuestPDF/QuestPDF#750]
Hello,

I'm facing difficulties when trying to publish an API exclusively with QuestPdf. In my local environment, the application works perfectly and is also operational on a machine under my maintenance, accessible at (https://gitpdf.blogbraga.com.br/swagger/index.html).

Initially, I attempted to publish the application with .NET 7, but due to issues, I decided to revert to .NET 6 to see if the situation improved. Unfortunately, when deploying to Azure (https://bfs-pdf.azurewebsites.net/), the application is not running correctly. I'm unsure if there's any specific configuration that needs adjustment to ensure proper functionality in the Azure environment.

:( Application Error
If you are the application administrator, you can access the [diagnostic resources]
`---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
`

My execution environment on Azure is set up as a Web-App using Linux. Any guidance on how to troubleshoot this issue or additional configurations I should consider to ensure proper operation on Azure would be greatly appreciated.

I appreciate in advance any assistance you can provide.

**Comment by MarcinZiabek** [comment]
What version of QuestPDF are you using?

All issues related to SkiaSharp will hopefully be fixed soon thanks to this https://github.com/QuestPDF/QuestPDF/discussions/622 effort.

**Comment by joaopaulobiesek** [comment]
What version of QuestPDF are you using? **2023.12.2**
What is your development OS? **WINDOWS**
Which nuget packages do you have installed on your startup project?

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="HTMLToQPDF" Version="1.1.0" />
	  <PackageReference Include="QuestPDF" Version="2023.12.2" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

</Project>
`

**Comment by MarcinZiabek** [comment]
Would you please share the stack trace of the exception mentioned in your first message?

**Comment by joaopaulobiesek** [comment]
https://mega.nz/file/FYZEzK6b#haxaoD2ncc5RkDfT8jYpb1kf8zU7IjbUN5zEmxH4y48

**Comment by joaopaulobiesek** [comment]
If you want, I can also share the git of the project with you, if you want to take a look and if you have an Azure then you can go up to test and find the problem more easily

**Comment by MarcinZiabek** [comment]
You have missed the wrapper exception generated by QuestPDF that provides some guidance on how to fix this issue. Hopefully, it will do the trick 😀

> 2024-01-04T13:52:40.755518836Z Unhandled exception. System.TypeInitializationException: The type initializer for 'QuestPDF.Settings' threw an exception.
> 2024-01-04T13:52:40.756847245Z  ---> QuestPDF.Drawing.Exceptions.InitializationException: The QuestPDF library has encountered an issue while loading one of its dependencies. This type of error often occurs when the current runtime is missing necessary NuGet packages. 
> 2024-01-04T13:52:40.756861445Z 
> 2024-01-04T13:52:40.756865045Z Please ensure the following NuGet packages are added to your primary/startup project and has matching versions:
> 2024-01-04T13:52:40.756868745Z - SkiaSharp.NativeAssets.Linux.NoDependencies
> 2024-01-04T13:52:40.756871945Z - HarfBuzzSharp.NativeAssets.Linux
> 2024-01-04T13:52:40.756879745Z 
> 2024-01-04T13:52:40.756883045Z For a detailed understanding, please examine the inner exception and consult the official SkiaSharp library documentation.

**Comment by joaopaulobiesek** [comment]
Thank you so much for your assistance!

Your guidance regarding the QuestPDF issue was incredibly helpful. I had missed the wrapper exception, and your insights allowed me to identify the root cause of the problem. Your advice to check and add the necessary NuGet packages was spot on. Here's the revised set of dependencies that resolved the issue:

`<PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="7.3.0" />
<PackageReference Include="HTMLToQPDF" Version="1.1.0" />
<PackageReference Include="QuestPDF" Version="2023.12.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.6" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />`
With these updated dependencies, the application on Azure is now functioning smoothly. I sincerely appreciate your timely assistance and guidance. It made a significant difference!

https://bfs-pdf.azurewebsites.net/swagger/index.html

**Comment by MarcinZiabek** [comment]
I am excited to help! Have fun with QuestPDF 😀

Closing
