### ISSUE TITLE
Arabic text that contains number are rotates numbers from right to left 

### ISSUE THREAD

**Issue by ahmniny** [QuestPDF/QuestPDF#752]
**Describe the bug**
Arabic text that contains number are rotates numbers from right to left 

**To Reproduce**
if Arabic text contains numbers numbers are rotated also.
"2024" will be "4202"

 ```
Document.Create(container =>
 {
     _ = container.Page(page =>
     {
         page.ContentFromRightToLeft();
         page.Content().Text("ديسمبر 1986 م").FontFamily(Fonts.Calibri);
     });
 })
 .GeneratePdf("temp.pdf");
 Process.Start("temp.pdf");
```

**Screenshots**
![number](https://github.com/QuestPDF/QuestPDF/assets/13631754/b9685829-8ef1-4341-bb32-4dac0adce70f)
**Environment**
windows 10 - arm64

**Comment by ahmniny** [comment]
[GeneratePdfExample.zip](https://github.com/QuestPDF/QuestPDF/files/13854670/GeneratePdfExample.zip)

**Comment by bennetbo** [comment]
See #445

**Comment by girlpunk** [comment]
I believe this comment still applies:

The best workaround I can come up with would be to split the input string based on the codepage of characters in it, as detailed [here](https://stackoverflow.com/a/45628450/1132448), and then render the result as separate spans with or without the direction override as needed.

**Comment by ahmniny** [comment]
> I believe this comment still applies:
> 
> The best workaround I can come up with would be to split the input string based on the codepage of characters in it, as detailed [here](https://stackoverflow.com/a/45628450/1132448), and then render the result as separate spans with or without the direction override as needed.

https://github.com/QuestPDF/QuestPDF/releases/tag/2024.3.0-alpha

**Comment by ahmniny** [comment]
> Seems to be the same as #445

https://github.com/QuestPDF/QuestPDF/releases/tag/2024.3.0-alpha

**Comment by ahmniny** [comment]
> I believe this comment still applies:
> 
> The best workaround I can come up with would be to split the input string based on the codepage of characters in it, as detailed [here](https://stackoverflow.com/a/45628450/1132448), and then render the result as separate spans with or without the direction override as needed.

https://github.com/QuestPDF/QuestPDF/releases/tag/2024.3.0-alpha
