### ISSUE TITLE
wsl compatibility

### ISSUE THREAD

**Issue by jaguarxii** [QuestPDF/QuestPDF#764]
**Is your feature request related to a problem? Please describe.**
I am starting to test QuestPDF in a project of an aspnet (dotnet 8) web application, the main development team works on windows and some members works on linux.

So I installed a wsl debian 11 instance on my windows environment, everything installed correctly, but got some errors while trying the test project, which already runs on windows and linux (debian 12).

I do not know if its a limitation of WSL (due to its trimmed library) or wsl is not a valid environment to test the library

Project references:
`<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.1" />
    <PackageReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.1" />
    <PackageReference Include="Plotly.NET" Version="4.2.0" />
    <PackageReference Include="Plotly.NET.ImageExport" Version="5.0.1" />
    <PackageReference Include="QuestPDF" Version="2023.12.4" />
    <PackageReference Include="SkiaSharp" Version="2.88.7" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.7" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="2.88.7" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="7.3.0.1" />
    <PackageReference Include="Svg.Skia" Version="1.0.0.10" />
  </ItemGroup>`

QuestPDF Startup settings

`
QuestPDF.Settings.License = LicenseType.Community;
FontManager.RegisterFont(File.OpenRead("./wwwroot/fonts/mbf-icons.ttf"));
FontManager.RegisterFont(File.OpenRead("./wwwroot/fonts/Nunito-SemiBold.ttf"));
FontManager.RegisterFont(File.OpenRead("./wwwroot/fonts/Poppins-Medium.ttf"));
`

WSL: 
debian 11
questpdf.previewer version 2023.12.2

this is the exception of running the previewer alone
`
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libICE.so.6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibICE.so.6: cannot open shared object file: No such file or directory
   at Avalonia.X11.ICELib.IceAddConnectionWatch(IntPtr watchProc, IntPtr clientData)
   at Avalonia.X11.X11PlatformLifetimeEvents..ctor(AvaloniaX11Platform platform)
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c.<UseX11>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Program.<Main>$(String[] args) in D:\a\QuestPDF\QuestPDF\Source\QuestPDF.Previewer\Program.cs:line 22
Aborted
`

UPDATE: Solved by installing libice6 and libsm6.

**Comment by MarcinZiabek** [comment]
I haven't tested the library on WSL, so I cannot confirm nor deny if it is compatible. 😀 

Would you please share the error you got? It is likely that running the project on the Linux environment may require installing one additional Nuget package (the exception should provide all details).

**Comment by Ziirf** [comment]
We are currently running our project on a linux docker on a linux system. We have had some issues as well, But was later fixed.
Some things you can try is using `HarfBuzzSharp.NativeAssets.Linux` and `SkiaSharp.NativeAssets.Linux.NoDependencies` with the appropriate version for the skia version.
Make sure you are not on QuestPdf v2023.10.1 (had some problems if your image didn't have a font manager).
If your image doesn't have a font manager, you need to load in all the fonts in manually with the QuestPDF fontmanager.

Currently everything for us is running smooth, and we are using v2023.12.0

**Comment by blogcraft** [comment]
I test using WSL (I can't recommend it enough!) And it works, but as @Ziirf said, `HarfBuzzSharp.NativeAssets.Linux` and `SkiaSharp.NativeAssets.Linux.NoDependencies` are a Must Have.
