### ISSUE TITLE
Containers rendered with ShowIf() method always take space

### ISSUE THREAD

**Issue by UsmanFarooq-Dev** [QuestPDF/QuestPDF#766]
If we conditionally show a container with `ShowIf()` method. It always takes column spacing no matter whether the condition is `true` or `false`. If the condition is `false`, the container will be hidden but the column spacing `column.Spacing(10)` would always be rendered.

However, we can use normal if-else in case if we want to avoid this issue.

**Comment by girlpunk** [comment]
Are you able to share the code used to generate your condition?

**Comment by UsmanFarooq-Dev** [comment]
Here is what I get when middle column is **shown**

`column.Item().DebugArea().BookingDetails(booking, isForGuest);
column.Item().DebugArea().ShowIf(true).GuestMessage(booking, isForGuest);
column.Item().DebugArea().HotelDetails(booking, isForGuest);`

![image](https://github.com/QuestPDF/QuestPDF/assets/46762281/0494fe1d-0b33-4295-a845-6442a4a5e26c)


Here is what I get when the middle column is **hidden**.

`column.Item().DebugArea().BookingDetails(booking, isForGuest);
column.Item().DebugArea().ShowIf(false).GuestMessage(booking, isForGuest);
column.Item().DebugArea().HotelDetails(booking, isForGuest);`

![image](https://github.com/QuestPDF/QuestPDF/assets/46762281/ea73ec77-09ed-4163-8e8b-b342c894febf)


In both cases then the column space is preserved.

**Comment by girlpunk** [comment]
I believe that's expected behaviour at the moment, as the column is still being created (`column.Item()` in your example).

@MarcinZiabek are there any plans to allow `ShowIf()` on a `ColumnDescriptor`?

**Comment by MarcinZiabek** [comment]
Indeed, it is an expected outcome. However, I believe it would be better if the `Column` element does not put additional spacing when empty content is detected. I will investigate this enhancement in the next upcoming release :)

**Comment by MarcinZiabek** [comment]
This problem was fixed in the latest `2023.12.5` release and also backported to the `2022.12.15` release. Would you please try it?

**Comment by UsmanFarooq-Dev** [comment]
I have updated the QuestPDF version to `2023.12.5` in my project. This issue seems to be fixed. Thanks @MarcinZiabek 

**With ShowIf(true)**
`column.Item().DebugArea().ShowIf(true).GuestMessage(booking, isForGuest);`

![image](https://github.com/QuestPDF/QuestPDF/assets/46762281/e6221843-1d75-4e6a-9bb8-f1c5606f9726)


**With ShowIf(false)**
`column.Item().DebugArea().ShowIf(true).GuestMessage(booking, isForGuest);`

![image](https://github.com/QuestPDF/QuestPDF/assets/46762281/7c202181-9188-4fe5-950c-3ea6f34dc4b2)
