### ISSUE TITLE
missing font in SVG

### ISSUE THREAD

**Issue by jaguarxii** [QuestPDF/QuestPDF#777]
**Describe the bug**
Missing letters (font) when adding a SVG to a document.
I have three different development environments, this issue occurs in debian 12.

**To Reproduce**
I am using Plotly.Net to create a basic chart then render to SVG (attached)
Add the SVG to the document
Saving or displaying the resulting PDF shows the SVG chart with squares instead of the letters

![image](https://github.com/QuestPDF/QuestPDF/assets/8013436/41d9242d-86df-4f11-bb16-90a49bb8bd41)

**Expected behavior**
This happens when I run the test project in a linux (Deban 12)
I run the same project in Windows or WSL Windows, it works as expected

**Environment**
Linux Debian 12 (bookworm) GNome 43.9
dotnet 8 webapp mvc

`
  <ItemGroup>

    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.1" />
    <PackageReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.1" />
    <PackageReference Include="Plotly.NET" Version="4.2.0" />
    <PackageReference Include="Plotly.NET.ImageExport" Version="5.0.1" />
    <PackageReference Include="QuestPDF" Version="2023.12.4" />
    <PackageReference Include="SkiaSharp" Version="2.88.7" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.7" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="2.88.7" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="7.3.0.1" />
    <PackageReference Include="Svg.Skia" Version="1.0.0.10" />
  </ItemGroup>
`

QuestPDF startup settings (program.cs)
`
QuestPDF.Settings.License = LicenseType.Community;

FontManager.RegisterFont(File.OpenRead("./wwwroot/fonts/mbf-icons.ttf")); // use file name
FontManager.RegisterFont(File.OpenRead("./wwwroot/fonts/Nunito-SemiBold.ttf")); // use file name
FontManager.RegisterFont(File.OpenRead("./wwwroot/fonts/Poppins-Medium.ttf")); // use file name
`

Source SVG (rendered using Plotly.Net)
![out_svg](https://github.com/QuestPDF/QuestPDF/assets/8013436/c2ac3355-b3da-48c9-b7cd-030eb5575b82)

**Comment by sproott** [comment]
I can confirm the same issue happens with [ScottPlot 5](https://scottplot.net/).

**Comment by sproott** [comment]
Found [this relevant issue](https://github.com/mono/SkiaSharp/issues/1131). The issue lies in the `SkiaSharp.NativeAssets.Linux.NoDependencies` package. It does not support a font manager and you have to include and import all relevant typefaces yourself. Using `SkiaSharp.NativeAssets.Linux` instead fixed my issue.

**Comment by MarcinZiabek** [comment]
You can also use the `Canvas` element to draw charts directly via SkiaSharp API: https://www.questpdf.com/api-reference/canvas.html

**Comment by jaguarxii** [comment]
Thanks @sproott by changing the library i got letters instead of squares, but the problem persists, the specified font of the SVG is not used when attached to the PDF document, it uses the default font (when using custom fonts like my sample) or similar font-family when using fonts like Arial, it falls back to a "sans-serif" font.

**Comment by MarcinZiabek** [comment]
Thank you for sharing this issue. 

To successfully embed fonts in the PDF document, they must be available during the generation time. I have updated the official documentation to provide guidance in this matter. I hope it helps 😄 

http://localhost:5173/api-reference/image.html#svg-support

**Comment by sproott** [comment]
> http://localhost:5173/api-reference/image.html#svg-support

Note that you put a localhost link instead of the online one.

**Comment by MarcinZiabek** [comment]
My bad! 😄 

Fortunately, the documentation update has already been deployed. Thank you for noticing!

**Comment by jaguarxii** [comment]
> Thank you for sharing this issue.
> 
> To successfully embed fonts in the PDF document, they must be available during the generation time. I have updated the official documentation to provide guidance in this matter. I hope it helps 😄
> 
> https://www.questpdf.com/api-reference/image.html#svg-support

Thanks! 
In my tests, it does not work as documented, the custom-fonts MUST be in the same folder as QuestPDF.dll, it is not required to be installed in the system to embed them in the PDF file, it also allows SVGs use the custom-fonts.

While having the custom-fonts in the same directory it is not compulsory loading them with the `FontManager` and/or setting `UseEnvironmentFonts`.

**Comment by jaguarxii** [comment]
UPDATE: 

Finally I get QuestPDF work with ScottPlot 5, changed from Plotly.Net because I found ScottPlot being more flexible/straightforward at creating charts, also much faster.

```
    //Program.cs
    //Register the font (and its variants) using QuestPDF's FontManager
    FontManager.RegisterFontWithCustomName("Barlow Semi Condensed", File.OpenRead("./wwwroot/fonts/BarlowSemiCondensed-Regular.ttf"));
    FontManager.RegisterFontWithCustomName("Barlow Semi Condensed", File.OpenRead("./wwwroot/fonts/BarlowSemiCondensed-Italic.ttf"));
    FontManager.RegisterFontWithCustomName("Barlow Semi Condensed", File.OpenRead("./wwwroot/fonts/BarlowSemiCondensed-SemiBold.ttf"));
    FontManager.RegisterFontWithCustomName("Barlow Semi Condensed", File.OpenRead("./wwwroot/fonts/BarlowSemiCondensed-SemiBoldItalic.ttf"));
    FontManager.RegisterFontWithCustomName("Barlow Semi Condensed", File.OpenRead("./wwwroot/fonts/BarlowSemiCondensed-Bold.ttf"));
    FontManager.RegisterFontWithCustomName("Barlow Semi Condensed", File.OpenRead("./wwwroot/fonts/BarlowSemiCondensed-BoldItalic.ttf"));

    //Do not use installed fonts
    QuestPDF.Settings.UseEnvironmentFonts = false;
    if (app.Environment.IsDevelopment()){
        QuestPDF.Settings.EnableDebugging = true;
    }
    QuestPDF.Settings.EnableCaching = true;
    QuestPDF.Settings.CheckIfAllTextGlyphsAreAvailable = false;

    //Register the font (and its variants) using ScottPlot's FontManager
    //You can set the same name as QuestPDF
    ScottPlot.Fonts.AddFontFile(name: "PlotFont", path: "./wwwroot/fonts/BarlowSemiCondensed-Regular.ttf");
    ScottPlot.Fonts.AddFontFile(name: "PlotFont", path: "./wwwroot/fonts/BarlowSemiCondensed-Bold.ttf", true);
    ScottPlot.Fonts.AddFontFile(name: "PlotFont", path: "./wwwroot/fonts/BarlowSemiCondensed-BoldItalic.ttf", true, true);
    ScottPlot.Fonts.AddFontFile(name: "PlotFont", path: "./wwwroot/fonts/BarlowSemiCondensed-Italic.ttf", false, true);
    ScottPlot.Fonts.Default = "PlotFont";
```

``` 
    // Report implementation of IDocument
    //Set the default document font
    page.DefaultTextStyle(TextStyle.Default.FontFamily("Barlow Semi Condensed"));

    //define a function that returns the SVG chart, within this function you don't need to set the fontname as it was already set in Program.cs
    c.Item().Svg(getSVGChart(inputData.balanceData)).FitArea();    
```
This is optional in case you want another folder to store the fonts, add an itemgroup section to the .csproj file

```
<ItemGroup>
    <ContentWithTargetPath Include="wwwroot/fonts/BarlowSemiCondensed-Regular.ttf" TargetPath="fonts/BarlowSemiCondensed-Regular.ttf" CopyToOutputDirectory="Always" />
    <ContentWithTargetPath Include="wwwroot/fonts/BarlowSemiCondensed-Italic.ttf" TargetPath="fonts/BarlowSemiCondensed-Italic.ttf" CopyToOutputDirectory="Always" />
    <ContentWithTargetPath Include="wwwroot/fonts/BarlowSemiCondensed-Bold.ttf" TargetPath="fonts/BarlowSemiCondensed-Bold.ttf" CopyToOutputDirectory="Always" />
    <ContentWithTargetPath Include="wwwroot/fonts/BarlowSemiCondensed-BoldItalic.ttf" TargetPath="fonts/BarlowSemiCondensed-BoldItalic.ttf" CopyToOutputDirectory="Always" />
    <ContentWithTargetPath Include="wwwroot/fonts/BarlowSemiCondensed-SemiBold.ttf" TargetPath="fonts/BarlowSemiCondensed-SemiBold.ttf" CopyToOutputDirectory="Always" />
    <ContentWithTargetPath Include="wwwroot/fonts/BarlowSemiCondensed-SemiBoldItalic.ttf" TargetPath="fonts/BarlowSemiCondensed-SemiBoldItalic.ttf" CopyToOutputDirectory="Always" />
  </ItemGroup>
```

**Comment by M0ns1gn0r** [comment]
I struggled a lot with this problem and eventually had to go a slightly different approach to make the fonts work:

```csharp
QuestPDF.Settings.UseEnvironmentFonts = false;
// Note that even after clearing, QuestPDF still uses the fonts from the application directory :O
QuestPDF.Settings.FontDiscoveryPaths.Clear();
QuestPDF.Settings.CheckIfAllTextGlyphsAreAvailable = false;

// ScottPlot has its own font resolver.
ScottPlot.Fonts.FontResolvers.Clear();

// Note, that SVG/Canvas rendering doesn't seem to support "variable" fonts.
var fonts = Path.Combine(AppContext.BaseDirectory, "fonts");
ScottPlot.Fonts.AddFontFile("Noto Sans Display", Path.Combine(fonts, "NotoSansDisplay-Regular.ttf"));
ScottPlot.Fonts.AddFontFile("Noto Sans Display", Path.Combine(fonts, "NotoSansDisplay-Bold.ttf"), true);
ScottPlot.Fonts.AddFontFile("Noto Sans SC", Path.Combine(fonts, "NotoSansSC-Regular.ttf"));
ScottPlot.Fonts.AddFontFile("Noto Sans SC", Path.Combine(fonts, "NotoSansSC-Bold.ttf"), true);
ScottPlot.Fonts.Default = "Noto Sans SC";
```

And yes, the crucial thing is to have the fonts in the application folder.
