### ISSUE TITLE
SectionLink from TextDescriptor does not work

### ISSUE THREAD

**Issue by burkaysucu** [QuestPDF/QuestPDF#779]
Hello,

We have been enjoying QuestPDF for a while now and it is truly awesome. 

Recently, we upgraded from version 2022.12.14 to the latest version 2023.12.4. However, the internal links are broken this time.

We are using `SectionLink`s over `TextDescriptor`s and they are not working. On the other hand, the `SectionLink`s over `IContainer`s as in the examples in documentation works as expected.

When inspecting the issue, we realized something odd. We opened the PDF file using the browser and hovered over the `SectionLink` items. On the lower left, browser shows the link and it starts with an additional `0 | ` as shown in below screenshot:

![image](https://github.com/QuestPDF/QuestPDF/assets/45235622/81d55b82-d2e7-46df-a16c-07e609736739)

Then we tried adding that `0 | ` to the link names for `SectionLink` of a `TextDescriptor` and it worked. However, when it is omitted, it does not work.

Below is the snippet to generate that PDF file:

                page.Content().Column(col =>
                {
                    col.Item().Section("links-chapter");
                    col.Item().Text("1");
                    col.Item().PageBreak();
                    col.Item().SectionLink("links-chapter").Text("Link from IContainer"); // works
                    col.Item().Text(t => {
                        t.SectionLink("Link from TextDescriptor with '0 |'", "0 | links-chapter"); // works
                    });
                    col.Item().Text(t => {
                        t.SectionLink("Link from TextDescriptor without '0 |'", "links-chapter"); // does not work
                    });
                });

We would like to keep using `TextDescriptor`s for linking purposes and not add that odd `0 | ` string. We would be glad if it works as before.

**Comment by burkaysucu** [comment]
Hey @MarcinZiabek,

Pulled the code and added it as reference to debug. Found out that it is working. Then realized you just fixed it in https://github.com/QuestPDF/QuestPDF/commit/86d2be343c27eccf69b8c4119a64131fb44bb670 . You're awesome, thank you so much! Now we are waiting for a new release.

**Comment by MarcinZiabek** [comment]
Indeed, I was about to write a message for you! It was great timing to include this little fix. 😄 

The new version should be live now.

**Comment by burkaysucu** [comment]
Great! Thank you so much for the fastest fix! 😄
