### ISSUE TITLE
Github Tag "invoce" should be "invoice" ?

### ISSUE THREAD

**Issue by skyslide22** [QuestPDF/QuestPDF#782]
The last tag for this project might be wrong, i think it should mean **invoice** instead of **invoce**
![image](https://github.com/QuestPDF/QuestPDF/assets/31780463/c93bfa5d-6e2c-42ac-8069-9f9cdaaa6232)

**Comment by MarcinZiabek** [comment]
Indeed! Thank you for noticing it! 😄
