### ISSUE TITLE
Cannot create a Component that uses SVG extension methods

### ISSUE THREAD

**Issue by jaguarxii** [QuestPDF/QuestPDF#787]
**Describe the bug**
Perhaps is a beginner question, but I cannot create a component that uses SVG methods, it throws an error about the extension method is not accessible.

**To Reproduce**
Created a dotnet fiddle [sample](https://dotnetfiddle.net/eyKunI)

**Expected behavior**
I copied the sample "LoremPicsum" and replace the internet image with an SVG

**Screenshots**

**Environment**
Windows 11 / dotnet 8 / webapp MVC

**Comment by girlpunk** [comment]
As well as installing the `Svg.Skia` package, SVG support also requires defining the `Svg(this IContainer container, SKSvg svg)` extension method, which doesn't appear to be in your example. Defining the function (which can be found in the [SVG documentation](https://www.questpdf.com/api-reference/image.html#svg-support)) somewhere appropriate in your program should allow this to work.

**Comment by jaguarxii** [comment]
I knew I was missing something, thanks!

I updated the sample to include these references
