### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by TheBeardedLlama** [QuestPDF/QuestPDF#79]
Hey, I was just wondering if it's possible to sign a pdf with this library?
Cheers :)

**Comment by MarcinZiabek** [comment]
The library does not provide signing functionality, only PDF/A compatibility. You can still generate your PDF with QuestPDF and then sign it with another library, sounds like a good plan, doesn't it? 😁

**Comment by TheBeardedLlama** [comment]
thank you for the quick reply @MarcinZiabek !
yes, that'd be an option for sure
