### ISSUE TITLE
Multidocument in one PDF file

### ISSUE THREAD

**Issue by troncomputers** [QuestPDF/QuestPDF#800]
Is there a chance to create one PDF file with multiple document/pages? For example I've selected couple of invoices in my system and I want them in one file 🤔

**Comment by youssefbennour** [comment]
@troncomputers 
A simple google search would have led you to the information you're looking for. [See docs](https://www.questpdf.com/concepts/merging-documents.html)
In short, the following code should be what you're looking for:
```
List<IDocument> documents;

// Add your documents to the list defined above.

MergedDocument pdf = Document.Merge(documents)
```

**Comment by CopperHusky6475** [comment]
Nowhere in the docs dose it talk about the MergedDocument class.
