### ISSUE TITLE
Protect PDF file with password

### ISSUE THREAD

**Issue by lgraebin** [QuestPDF/QuestPDF#82]
Is there a way to protect PDF file generated by QuestPDF with password?

**Comment by MarcinZiabek** [comment]
I am afraid that the mentioned functionality (protecting PDF with password) is currently not supported. 

However, you can still generate your PDF with QuestPDF and then protect it with another library, sounds like a good plan, doesn't it? 😁

**Comment by lgraebin** [comment]
Thanks @MarcinZiabek.
