### ISSUE TITLE
[Help] Minimum cell height based on rotated text

### ISSUE THREAD

**Issue by rverberne-carapax** [QuestPDF/QuestPDF#820]
Hello,

The table has rotated text in the header using 'RotateLeft()'. But now the height of the cell is very big.

I could set a `Height()` on the header cell and that would break it in 2 lines. But i would rather have a dynamic height.

Is it possible to let the height of the cell grow, and stop growing when the text fits in all available space? I want the lowest height while still showing all text.

Thanks.

![image](https://github.com/QuestPDF/QuestPDF/assets/161334457/d85f70ed-e455-4ca1-a0f3-8e6f0efc6476)

**Comment by rverberne-carapax** [comment]
I am trying a dynamic component, but a big problem seems to be that if the available space is too small, you get a LayoutException. Instead i would expect the whole component to be moved to the next page. But maybe i misunderstand something.

**Comment by MarcinZiabek** [comment]
I am sorry for the late response 😄  

I suggest using a combination of `HeightMax` (sets an upper bound for how big the cell can be) and `ScaleToFit` (resolves corner cases when text is very long by scaling it down) elements.

**Comment by rverberne-carapax** [comment]
Hi, thanks for your answer,

`MaxHeight` and `ScaleToFit` does something a little different. The text is only broken in multiple lines after `MaxHeight` would be exceeded. Also, mixing font sizes does not look as good.

This is the result of my dynamic component: It breaks the lines and uses minimal height to fit them. Is there anything wrong with this approach?

![image](https://github.com/QuestPDF/QuestPDF/assets/161334457/f1728bbf-15c2-4b31-a213-18f741ac9b73)

**Comment by MarcinZiabek** [comment]
Absolutely not; your implementation is completely okay 😄  It is just a bit complex, and many developers may prefer a simpler approach, even if it does not produce perfect results.

**Comment by rverberne-carapax** [comment]
Ok, thank you. I will close the issue.
