### ISSUE TITLE
Support rounded corners on Border

### ISSUE THREAD

**Issue by abrull** [QuestPDF/QuestPDF#83]
**Is your feature request related to a problem? Please describe.**
I'd like to make a border around an element similar to css border-radius

**Comment by MarcinZiabek** [comment]
Hello 😀

The border-radius functionality is not currently supported out-of-the-box. If more people request this functionality, I can analyse adding it to the library.

However, you can easily achieve the effect by using the Canvas element, like so:

```csharp
.Box()
.Layers(layers =>
{
    layers.PrimaryLayer().Padding(10).Text("Sample text");
    
    layers.Layer().Canvas((canvas, size) =>
    {
        using var paint = new SKPaint
        {
            Color = SKColor.Parse(Colors.Black),
            IsStroke = true,
            StrokeWidth = 1,
            IsAntialias = true
        };
        
        canvas.DrawRoundRect(0, 0, size.Width, size.Height, 20, 20, paint);
    });
});
```

Effect:
![image](https://user-images.githubusercontent.com/9263853/147785460-a7aa985f-2c4f-4b42-8243-7d68c7886e1a.png)

**Comment by abrull** [comment]
Hey! Thanks so much for the tip. I was able to implement our design perfectly.

**Comment by lpunderscore** [comment]
I know this is closed, but this saved me.

1 upvote for out-of-the-box support for radius specification (fill and stroke) / backgound etc..

**Comment by Ruitjes** [comment]
If out-of-the-box support could be added that would be amazing!
