### ISSUE TITLE
Non-PageBreaking cell of table duplicates data in both pages

### ISSUE THREAD

**Issue by danirzv** [QuestPDF/QuestPDF#840]
**Describe the bug**
if a coloumn of a table row be long enough at the ending of the page to make it break into next page different cells act different ways.

- the cells which lead to break page will break into two parts for example text "AAAAAAAAAAA..<breaking from here>..BBBBBBBBB, will be as "AAAAAAAAAAA.." in 1st page, and ..BBBBBBBBB will be in 2nd page which is a good and normal act.
- the other cells in same row which did not need break will get duplicated in both pages **which will cause the problem**

**To Reproduce**

- create a table and add some rows to reach the bottom of page
- in one of cells of that row enter some long content which will be multi-line and some lines get to 2nd page
- add some cells before or after that cell in same row with short content (for example some price field in a receipt)

**Expected behavior**
I expect non-PageBreaking cells content remain in page 1 and don't duplicate them in 2nd page

**Environment**
What version of the library do you use? **2024.3.0**
What operating system do you use? (OS type, x64 vs x86 vs arm64) **Windows x64**

**Comment by danirzv** [comment]
@MarcinZiabek any idea how i could fix this?

**Comment by MarcinZiabek** [comment]
I am actively working on improving this default behavior. Technically, it works as expected and aims to enhance compatibility with specific layout structures. However, I recognize it is not very predictable and developer-friendly. I plan to release an improvement very soon.

Meanwhile, please use the `ShowOnce` element before your content.
