### ISSUE TITLE
Everything stop working correctly after upgrading to latest version

### ISSUE THREAD

**Issue by toanxyz** [QuestPDF/QuestPDF#844]
**Describe the bug**
After upgrading to latest version, everything just stop working.

I'm using Debian 12 (aspnet:8.0-bookworm-slim), I have no clue what is wrong, in local it works fine.
I have installed:
SkiaSharp.NativeAssets.Linux.NoDependencies v2.88.8
HarfBuzzSharp.NativeAssets.Linux 7.3.0.2

![image](https://github.com/QuestPDF/QuestPDF/assets/6207857/20c79f25-117c-4595-84b2-4540e25025b0)

**To Reproduce**
Please provide an example, minimalistic code that shows the problem.
Providing working example or example repository greatly helps us investigate the problem and react faster.

**Expected behavior**

**Screenshots**

**Environment**
What version of the library do you use? 
What operating system do you use? (OS type, x64 vs x86 vs arm64)

**Additional context**

**Comment by michaelthwaite** [comment]
Similar issue here running on AWS Lambda, i.e. Amazon Linux 3.

Everything loads, PDF is rendered, including text boarders but text is missing.

Downgraded to 2023.12.6 & SkiaSharp.NativeAssets.Linux.NoDependencies Version 2.88.7 and it's operational again.

**Comment by toanxyz** [comment]
I wonder if QuestPDF has enough testing before rolling out the 2024 version :( The just breaking without any clues like this make me lose confident on the library.

**Comment by MarcinZiabek** [comment]
I am very sorry for any issues related to the latest version. The 2024.3.X release is one of the most significant redesigns of the library. Although the Community has tested it for nearly two months, some hiccups are expected once it is fully available to all developers.

I am trying to figure out what exactly causes the issue on your end. In the 2024.3.1 release, I increased compatibility with existing codebases relying on QuestPDF, primarily related to the `FontFallback` functionality. Would you please test the new version?

If it still does not work, would you please ensure the following flag is set to true? `Settings.CheckIfAllTextGlyphsAreAvailable`

I am dedicated to fixing any problems. Thank you for collaboration 😄

**Comment by MarcinZiabek** [comment]
@toanxyz Over the last two weeks, several quality updates have been released to the 2024.3 version. Would you please revisit this problem and check if it still persists?

**Comment by michaelthwaite** [comment]
I can confirm that 2024.3.3 now works with AWS Lambda, ARM64 and, without any of those tricky dependancies, which is great!

Thanks for the update.
