### ISSUE TITLE
Black border using SkiaSharp canvas integration

### ISSUE THREAD

**Issue by sproott** [QuestPDF/QuestPDF#850]
**Describe the bug**
The plotting library I use ([Scottplot](https://scottplot.net/)) always clears the canvas using the equivalent of these two calls:

```cs        
canvas.Clear();
canvas.Clear(SKColors.White);
```

This results in an unwanted artifact - a black border on the edge of the canvas in the resulting PDF.

**To Reproduce**
- Add the SkiaSharp integration [described in the docs](https://www.questpdf.com/concepts/skia-sharp-integration.html#integration-layer)
- Render a document containing the following SkiaSharpCanvas element:

```cs
SkiaSharpCanvas((canvas, size) => {
	canvas.Clear();
	canvas.Clear(SKColors.White);
});
```

**Expected behavior**
There should be a white rectangle in the resulting document, no black border, same as when the SVG is displayed in the browser.

**Screenshots**:

![image](https://github.com/QuestPDF/QuestPDF/assets/46423131/9d8297e9-ff91-4fbf-92d3-de8f8db2dfd1)

**Environment**
QuestPDF version:  2024.3.1
OS: Arch Linux x64

**Additional context**
The first `canvas.Clear();` call appears as a black rectangle in the SVG, both in the browser and in the PDF document. Even though the second call should create a white rectangle of the same size, effectively overlapping the whole black rectangle, that is not the case in the PDF document. Maybe it's a limitation of SkiaSharp? If so, is there any possible workaround?

**Comment by MarcinZiabek** [comment]
Hairlines 😄 

This looks like a bug on the ScottPlot end (though it is an amazing library!). I would suggest clearing the space with just:

```csharp
canvas.Clear(SKColors.Transparent);
```

However, this workaround works as expected:

```csharp
.SkiaSharpCanvas((canvas, size) => {
    canvas.ClipRect(new SKRect(1, 1, size.Width - 1, size.Height - 1)); // here
    canvas.Clear();
    canvas.Clear(SKColors.White);
});
```

**Comment by sproott** [comment]
> Hairlines 😄
> 
> This looks like a bug on the ScottPlot end (though it is an amazing library!). I would suggest clearing the space with just:
> 
> ```cs
> canvas.Clear(SKColors.Transparent);
> ```
> 
> However, this workaround works as expected:
> 
> ```cs
> .SkiaSharpCanvas((canvas, size) => {
>     canvas.ClipRect(new SKRect(1, 1, size.Width - 1, size.Height - 1)); // here
>     canvas.Clear();
>     canvas.Clear(SKColors.White);
> });
> ```

Thank you for the quick reply!

Unfortunately, your suggested change results in the following SVG and does not work either:

```svg
<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="536" height="357">
	<clipPath id="cl_8">
		<rect x="1" y="1" width="533.40002" height="354.93335"/>
	</clipPath>
	<g clip-path="url(#cl_8)">
		<rect width="536" height="357"/>
		<rect fill="white" width="536" height="357"/>
	</g>
</svg>
```

Any clues on where the issue lies?

**Comment by sproott** [comment]
It really looks like a ScottPlot problem. I've managed to spot the hairlines viewing the SVG with InkScape's `inkview`, too. Therefore it seems like it's not a QuestPDF bug and I'll try to discuss this further at ScottPlot's GitHub.

**Comment by MarcinZiabek** [comment]
> It really looks like a ScottPlot problem.

I wouldn't say it's ScottPlot problem per se. It is very close to how Skia converts drawing instructions to SVG content. Then, about how is that content rendered in non-native resolutions (where points do not match integer pixels). I needed to try hard to see this issue on my 4k screen. 

But taking into account that ScottPlot officially supports SVG, they can make this small improvement.

**Comment by M0ns1gn0r** [comment]
In the meantime a workaround was added to ScottPlot:

```csharp
var plot = new Plot();
plot.RenderManager.ClearCanvasBeforeEachRender = false;
```
