### ISSUE TITLE
The previewer doesn't show any buttons

### ISSUE THREAD

**Issue by castroal** [QuestPDF/QuestPDF#866]
**Describe the bug**
The previewer doesn't show any buttons (like the GeneratePDF button) anymore.

**To Reproduce**
```
var document = Document.Create(container =>
{
    container.Page(page =>
    {
        // page content
    });
});

document.ShowInPreviewer();
```

**Expected behavior**
The buttons in the previewer should be visible.

**Screenshots**
![image](https://github.com/QuestPDF/QuestPDF/assets/4523352/c5cadd50-0582-49fd-8b5d-51ce2a052890)

**Environment**
.net 8 Console Application
**Previewer version: 2024.3.0**

**Comment by MarcinZiabek** [comment]
Thank you for reaching out 😄 

Those buttons have been intentionally removed. The 2024.3.0 release required a significant overhaul of the generation logic, more information here: https://github.com/QuestPDF/QuestPDF/discussions/622 I needed to cut corners and decided to not include this feature. 

That being said, something exciting is on the horizon. I am working on the new QuestPDF Companion application, which offers significantly more features and enhances the developer experience. I haven't posted much about the progress, but it is the next big thing on the roadmap at this moment: https://github.com/QuestPDF/QuestPDF/discussions/621
