### ISSUE TITLE
Showing an svg image spams the log

### ISSUE THREAD

**Issue by Krm1t** [QuestPDF/QuestPDF#868]
Hey

**Describe the bug**
We've upgraded to version 2024.3.2 to take advantage of the changed svg support but now our log is getting spammed with the message `cannot append child nodes to an SVG shape.`
The message doesn't seem to be logged with the regular ILogger as there is no log level or anything so i'm guessing something like Console.WriteLine().
It looks like i get one log per image and depending on which template we run that amounts to an avg of 50 logs per document.

**To Reproduce**
I've used the following code to load and show the image.
Certain things omitted to keep it short.
If need be i can try and create a test application to reproduce this.
Also i've attached one of the images that this happens with.
```
using var streamReader = new StreamReader(resourceStream);
var svgcontent = streamReader.ReadToEnd();
 table
  .Cell()
  .Row(rowNumber)
  .Column(2)
  .AlignCenter()
  .Height(_rowHeight)
  .AlignMiddle()
  .Svg(svgContent)
  .FitArea();
```

**Expected behavior**
I'm not sure what the expected behavior should be but i can say this, as i'm not the one doing anything to the image i must assume that this happens somewhere in the belly of QuestPDF but as i have no way of fixing the issue then the message really is just useless noise.
So maybe not show it at all or at the very least use an ILogger so i can filter it out.

[checkbox-checked](https://github.com/QuestPDF/QuestPDF/assets/2786521/0aca1635-7e2d-4df0-9426-0ce45041b566)

**Comment by MarcinZiabek** [comment]
Indeed, those messages are produced by the native Skia code.  In contrast to web browsers, the Skia SVG rendering engine is quite strict regarding the specification. 

Would you please share your SVG image? Maybe there is something wrong with your file?

**Comment by Krm1t** [comment]
@MarcinZiabek I actually attached the image. I just hadn't removed the ! in front of it so the text wasn't showing :)

**Comment by MarcinZiabek** [comment]
I have validated your file using the official W3C tool. It seems that it uses invalid unicode characters in ids: https://validator.w3.org/check?uri=https%3A%2F%2Fgithub-production-user-asset-6210df.s3.amazonaws.com%2F2786521%2F326823848-0aca1635-7e2d-4df0-9426-0ce45041b566.svg%3FX-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%3DAKIAVCODYLSA53PQK4ZA%252F20240503%252Fus-east-1%252Fs3%252Faws4_request%26X-Amz-Date%3D20240503T103333Z%26X-Amz-Expires%3D300%26X-Amz-Signature%3Ddd10d3044c983407146e1a25b7e9446c04a6924f5ce6b0468324734fbd69ac0c%26X-Amz-SignedHeaders%3Dhost%26actor_id%3D9263853%26key_id%3D0%26repo_id%3D326826023&charset=%28detect+automatically%29&doctype=SVG+1.1&group=0

<img width="1161" alt="image" src="https://github.com/QuestPDF/QuestPDF/assets/9263853/5541e6b3-e14c-4f7f-98e1-5de907b5318e">

**Comment by Krm1t** [comment]
Thanks for taking the time.

I tried removing the 2 symbols but it didn't help.
Fiddling around with it a bit i found that having `<path d="..."></path>` is not allowed so changing it to `<path d="..." />`

I'll leave this here in case someone happens upon it.

And again thanks @MarcinZiabek
