### ISSUE TITLE
Reintroduce Win-x86 support

### ISSUE THREAD

**Issue by luis-fss** [QuestPDF/QuestPDF#874]
**Is your feature request related to a problem? Please describe.**
Many old devices and free hosting servers have RAM restrictions and only support Win-x86

**Describe the solution you'd like**
I would really like to see Win-x86 support reintroduced. Yes, it is an old architecture, but it is still widely used on low-cost equipment and servers with free hosting options that have RAM usage restrictions.

**Comment by Syan-hs** [comment]
Hi @MarcinZiabek  -Are we working on this ? My company is considering buying your library but I found it doesn't support x86.

**Comment by MarcinZiabek** [comment]
I have already attempted to compile the library with the x86 architecture. It requires a special toolchain and is not straightforward. Therefore, some research may be necessary to make it work. I will do one more try next week.

If anyone decides to share the feedback in this thread, please explain why you need the x86 support and why the x64 is insufficient. It would also be great to learn how you use the library.

Thank you for your patience and collaboration! 😄

**Comment by PALILIPA** [comment]
It will be nice to keep x86 support, some old computers exist !!

Thanks

**Comment by rima1098** [comment]
> I have already attempted to compile the library with the x86 architecture. It requires a special toolchain and is not straightforward. Therefore, some research may be necessary to make it work. I will do one more try next week.
> 
> If anyone decides to share the feedback in this thread, please explain why you need the x86 support and why the x64 is insufficient. It would also be great to learn how you use the library.
> 
> Thank you for your patience and collaboration! 😄

Regarding Feedback: Our software e.g. relies on some external devices which only work with x86. Allthough the architecture is outdated it would be a pain to replace the devices, therefore we still run on x86 and would require it's support for QuestPDF.

**Comment by Syan-hs** [comment]
> > I have already attempted to compile the library with the x86 architecture. It requires a special toolchain and is not straightforward. Therefore, some research may be necessary to make it work. I will do one more try next week.
> > If anyone decides to share the feedback in this thread, please explain why you need the x86 support and why the x64 is insufficient. It would also be great to learn how you use the library.
> > Thank you for your patience and collaboration! 😄
> 
> Regarding Feedback: Our software e.g. relies on some external devices which only work with x86. Allthough the architecture is outdated it would be a pain to replace the devices, therefore we still run on x86 and would require it's support for QuestPDF.

We have same issue, we are using third party libraries which only works with x86.

**Comment by MarcinZiabek** [comment]
The `2024.3.6` release introduces support for the `win-x86` platform. Could you please test if it works for you as expected?

**Comment by luis-fss** [comment]
It worked great on Windows 10 x86.
@MarcinZiabek Thank you very much for the fantastic work.
I love this library!

**Comment by PALILIPA** [comment]
It works !Thanks a lot Le 15 mai 2024 03:18, Luis Fernando de Souza Santos ***@***.***> a écrit :
It worked great on Windows 10 x86.
@MarcinZiabek Thank you very much for the fantastic work.
I love this library!

**Comment by rima1098** [comment]
@MarcinZiabek 
We have some troubles with the x86 support. It does not seem to be a issue of the library itself but maybe you have some ideas why it fails. 
We only have this issue when Debugging in Visual Studio. In Rider everything works.
The error Message is the following:
"A call to the PInvoke function 'QuestPDF!QuestPDF.Skia.SkNativeDependencyCompatibilityChecker+API::check_compatibility_by_calculating_sum' has disturbed the stack balance. The managed PInvoke signature probably does not match the unmanaged target signature. Check whether the calling convention and the parameters of the PInvoke signature match the unmanaged target signature."
Our Configuration is on AnyCPU but the Project specifically Targets Platform x86. For whatever reasons, if i start the .exe directly without debugging in Visual Studio it works fine. Also Debugging works in Rider.
Do you have any idea about this?

**Comment by rima1098** [comment]
> @MarcinZiabek We have some troubles with the x86 support. It does not seem to be a issue of the library itself but maybe you have some ideas why it fails. We only have this issue when Debugging in Visual Studio. In Rider everything works. The error Message is the following: "A call to the PInvoke function 'QuestPDF!QuestPDF.Skia.SkNativeDependencyCompatibilityChecker+API::check_compatibility_by_calculating_sum' has disturbed the stack balance. The managed PInvoke signature probably does not match the unmanaged target signature. Check whether the calling convention and the parameters of the PInvoke signature match the unmanaged target signature." Our Configuration is on AnyCPU but the Project specifically Targets Platform x86. For whatever reasons, if i start the .exe directly without debugging in Visual Studio it works fine. Also Debugging works in Rider. Do you have any idea about this?

Not sure about it but this problems might be caused by the Calling Convention. There are differences between x86 and x64. It might be necessary to specify the CallingConventionAttribute on the DllImport
