### ISSUE TITLE
Query regarding License 

### ISSUE THREAD

**Issue by sgbelim** [QuestPDF/QuestPDF#878]
Hello

My company would like to purchase the license but we require company's contact details which I couldn't find anywhere 

Can the owner of the repo help out please?

**Comment by luis-fss** [comment]
contact@questpdf.com

**Comment by sgbelim** [comment]
Thanks

**Comment by sgbelim** [comment]
We have contacted on above email we haven't had any reply back hence asked here

**Comment by MarcinZiabek** [comment]
@sgbelim I sincerely apologize for the inconvenience. I do my best to respond to all emails promptly, but we all understand the challenges posed by priorities, spam filters and blocked SMTP servers.

I recently replied to an email regarding the company license, and I hope it was yours.

For future reference, I'd like to confirm that QuestPDF is maintained by `Marcin Ziąbek CodeFlint`, a company registered in Poland. You can find all the company details at [this link](https://aplikacja.ceidg.gov.pl/CEIDG/CEIDG.Public.UI/SearchDetails.aspx?Id=c895fabc-a7f0-4116-91f5-97879ea078f0) (official Polish government website).

Please don't hesitate to reach out again if you need further assistance.

**Comment by sgbelim** [comment]
Appreciate and thanks @MarcinZiabek
