### ISSUE TITLE
Is there an asynchronous version of GeneratePdf to write to an output stream (web API)?

### ISSUE THREAD

**Issue by PeaceWithTrump** [QuestPDF/QuestPDF#887]
Using ASP.NET Core 8.0 minimal Web API I am getting an error stating synchronous operation is not supported. I am trying to save memory by not creating extra byte arrays or new memory stream. I am simply trying to direct the output onto web response stream.

Program.cs

```
app.MapGet("/pdf/{id}/print", ([FromRoute] int id, HttpResponse resp) =>
    {
        var outputStream = resp.Body;

        resp.StatusCode = 200;
        resp.Headers.Add(HeaderNames.ContentDisposition, $"attachment; filename=1.pdf");
        resp.Headers.Add(HeaderNames.ContentType, "application/pdf");
...
	ICustomDocument questDocument = new CustomDocument()

        questDocument.GeneratePdf(outputStream); <<<--- ERROR
        outputStream.FlushAsync();
    })

```
When executing the following error gets generated.

> System.InvalidOperationException: **Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.**
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)

It does seem the async version of a method "GeneratePdf" should have been provided. I tried another way by providing a MemoryStream instance to let write a PDF first into it. I am getting another blockage, though.

```
app.MapGet("/pdf/{id}/print", ([FromRoute] int id) =>
    {
        var outputStream = new MemoryStream();
	ICustomDocument questDocument = new CustomDocument()

        questDocument.GeneratePdf(outputStream); <<<--- ERROR

        return new FileStreamResult(outputStream, "application/pdf")
        {
            FileDownloadName = "1.pdf"
        };
    })

```
The error I am getting is:

> System.InvalidOperationException: **Timeouts are not supported on this stream.**
>    at System.IO.Stream.get_ReadTimeout()
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
>    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
>    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
>    at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.<WriteAsJsonAsync>g__WriteAsJsonAsyncSlow|5_0[TValue](HttpResponse response, TValue value, JsonTypeInfo`1 jsonTypeInfo)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by MarcinZiabek** [comment]
Unfortunately, the PDF generation process is pretty much synchronous. Most memory consumption is related to temporary assets, and potential savings are insignificant. Please feel free to use the memory overload that directly returns a byte array.

Of course, I am always open to investigating potential enhancements and reviewing my findings. Especially since QuestPDF is now built on top of pure Skia, and potentially, there are more opportunities for optimization.

**Comment by PeaceWithTrump** [comment]
Ahh, I did not notice a byte array overload. This is good enough. Thank you.
