### ISSUE TITLE
"Table continued" indicator 

### ISSUE THREAD

**Issue by burkaysucu** [QuestPDF/QuestPDF#898]
We need our tables to indicate whether they span multiple pages. This is a very common requirement. Examples found by searching for "table continued" in a search engine:

- https://grad.ncsu.edu/wp-content/uploads/2018/03/Tables-and-Figures-continued.pdf
- https://www.montana.edu/etd/how-to/table-multiple-pages.html
- https://www.mtmercy.edu/_documents/academics/library/advanced-apa-formatting.pdf (second page, first paragraph)

Since the Header container of Table is repeated on every page and we can now get the current page number thanks to @MarcinZiabek  per `ShowIf` ( #706 ), we tried moving the table caption to the Header container. Then, we checked the current page number for the table using ShowIf and succeed to show "Table Continued" on the next pages table is spanning. This approach mostly solved our requirement. However, it shows the vertical borders of the table.

Two possibilities to solve this:

- Cell borders have higher priority than table borders. Then, we can set cell borders to zero to hide the borders for the newly added header.
- A new Caption container for the Table. Caption is a pretty standard element for tables for example in LaTeX or HTML. This would be more user friendly.

**Comment by MarcinZiabek** [comment]
Using the `Decoration`, `SkipOnce` and `ShowOnce` elements allow achieving the requirement:

```csharp
.Padding(20)
.Decoration(decoration =>
{
    decoration
        .Before()
        .DefaultTextStyle(TextStyle.Default.Bold().FontSize(16))
        .Column(column =>
        {
            column.Item().ShowOnce().Text("Content caption");
            column.Item().SkipOnce().Text("Content (continued)");
        });
    
    decoration
        .Content()
        
        // replace with your table
        .PaddingTop(20)
        .ExtendHorizontal()
        .Background(Colors.Grey.Lighten2)
        .Padding(10).Column(column =>
        {
              column.Spacing(5);
              
              foreach (var i in Enumerable.Range(0, 10))
                  column.Item().Text(Placeholders.Paragraph());
        });
});
```

<img width="417" alt="image" src="https://github.com/QuestPDF/QuestPDF/assets/9263853/48a48e11-4e09-4f9b-a2ee-3dcd89e85b27">
