### ISSUE TITLE
SVG anti aliasing problem

### ISSUE THREAD

**Issue by burkaysucu** [QuestPDF/QuestPDF#904]
Hello. We need to draw a repeating pattern as the background of some paragraphs. The pattern is 45-degree-rotated stripes. Below code shows what we tried (paragraphs are scraped for brevity):

          page.Content().Column(col =>
          {
              col.Item().Height(3, Unit.Centimetre).Svg(size =>
              {
                  var tileSize = 15;
                  return $@"
    <svg width=""100%"" height=""100"" style=""background:black;"">
    <defs>
      <pattern id=""stripe-pattern"" width=""{tileSize * 2}"" height=""{tileSize * 2}"" patternUnits=""userSpaceOnUse"" patternTransform=""rotate(-45 50 50)"">
        <rect fill=""yellow"" x=""0"" y=""0"" width=""100%"" height=""{tileSize}"" />
        <rect fill=""black"" x=""0"" y=""{tileSize}"" width=""100%"" height=""{tileSize}"" />
      </pattern>
    </defs>
      <rect x=""0"" y=""0"" width=""100%"" height=""100%"" fill=""url(#stripe-pattern)""></rect>
    </svg>";
              });

              col.Item().PaddingTop(30).Height(3, Unit.Centimetre).SkiaSharpCanvas((canvas, size) =>
              {
                  var canvasWidth = (int)size.Width;
                  var canvasHeight = (int)size.Height;
                  var tileWidth = 15;
                  var tileHeight = 15;

                  var canvasRect = new SKRect(0, 0, canvasWidth, canvasHeight);
                  var tileRect = new SKRect(0, 0, tileWidth, tileHeight);

                  var bitmap = new SKBitmap(canvasWidth, canvasHeight);
                  var newCanvas = new SKCanvas(bitmap);

                  using (SKPaint paint = new SKPaint())
                  {
                      paint.Shader = SKShader.CreateLinearGradient(
                                          new SKPoint(tileRect.Left, tileRect.Top),
                                          new SKPoint(tileRect.Right, tileRect.Bottom),
                                          new SKColor[] { SKColors.Black, SKColors.Yellow },
                                          new float[] { .5f, .5f },
                                          SKShaderTileMode.Repeat);

                      canvas.DrawRect(canvasRect, paint);
                      newCanvas.DrawRect(canvasRect, paint);
                      SaveImage(bitmap, "gradient-test.png");
                  }
              });

          });

      public static void SaveImage(SKBitmap bitmap, string outputPath)
      {
          using var stream = new FileStream(outputPath, FileMode.Create, FileAccess.Write);
          using var image = SKImage.FromBitmap(bitmap);
          using var encodedImage = image.Encode();
          encodedImage.SaveTo(stream);
      }

Below screenshot shows the output:
![image](https://github.com/QuestPDF/QuestPDF/assets/45235622/ecb19dd8-bcc5-40e4-939e-9f100278e5df)

Below is how the given svg is rendered in Firefox:
![image](https://github.com/QuestPDF/QuestPDF/assets/45235622/25daf718-4e94-44cc-acd8-307d0ff28aed)

Below is the gradient-test.png:
![image](https://github.com/QuestPDF/QuestPDF/assets/45235622/789f4bf5-7041-46c8-9edd-7a7a0797d4d1)

As seen in the screenshots, both methods produces good looking outputs out of the PDF environment. However, in the PDF, the first method has an anti-aliasing problem and the second one does not repeat. Could you please lead us to some solution?

**Comment by MarcinZiabek** [comment]
It seems that patterns are rasterized by the Skia SVG engine.

I can offer the following workaround that generates each stripe in a loop:

```csharp
.Svg(size =>
{
    var tileSize = 15;
    
    var stripes = Enumerable
        .Range(0, (int)(size.Width / tileSize / 2) + 1)
        .Select(x => $@"<rect x=""0"" y=""{tileSize * x * 2}"" width=""100%"" height=""{tileSize}"" fill=""black""></rect>");
    
    return $@"<svg width=""100%"" height=""100%"" style=""background:black;"">
        <defs>
            <clipPath id=""clip"">
              <rect x=""0"" y=""0"" width=""100%"" height=""100%"" />
            </clipPath>
          </defs>
        <g clip-path=""url(#clip)"">
            <rect x=""0"" y=""0"" width=""100%"" height=""100%"" fill=""yellow""></rect>

          <g  transform=""rotate(-45) translate(-40, 0)"">
            {string.Join("", stripes)}
          </g></g>
        </svg>";
});
```

**Comment by burkaysucu** [comment]
@MarcinZiabek I don't remember how many problems of ours you solved. You always come up with a solution and we always talk (highly) behind you, thank you so much! :)

**Comment by MarcinZiabek** [comment]
It's my pleasure to help! Thanks to the hybrid license, I can dedicate time to provide at least basic support 😄

**Comment by burkaysucu** [comment]
@MarcinZiabek Hi Marcin. We have been strongly considering that. We will get in touch with you soon.
