### ISSUE TITLE
2024.X.Y release no longer supports linux-arm (32-bit)

### ISSUE THREAD

**Issue by jeremy-c87** [QuestPDF/QuestPDF#910]
**Describe the bug**
My app doesn't start anymore (was working fine on 2023.12.6) : I am currently working in linux-arm. Apparently not supported anymore?

I have a peculiar setup: I am running the app on an synology with runtime .net8. 
The app is developed in Visual Studio 2022 in C#.ASP.
I can't use docker because my Synology is too old, I have tried to change runtime to linux-arm64 but I have another error FileNotFoundException on the main dll...

I have now reverted to 2023.12.6 and it works, I am available to try and find the problem and so we can migrate not the new version.

**EDIT 1:**
More information...
So, from the working project in 2023.12.6. I have updated my NuGet to 2024.3.10. Then delete the additional NuGet referencing SkiaSharp. Recompiling : no error. Then, when I try to start my app here is the messages :

Unhandled exception. System.TypeInitializationException: The type initializer for 'QuestPDF.Settings' threw an exception.
 ---> System.Exception: The QuestPDF library has encountered an issue while loading one of its dependencies.

Your runtime is currently not supported by QuestPDF. Currently supported runtimes are: win-x86, win-x64, linux-x64, linux-arm64, linux-musl-x64, osx-x64, osx-arm64. Your current runtime is detected as 'linux-arm'.

Please consider setting the 'Platform target' property to 'Arm64' in your project settings.
 ---> System.DllNotFoundException: Unable to load shared library 'QuestPdfSkia' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/volume1/@appstore/dotnet8-runtime/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/QuestPdfSkia.so: cannot open shared object file: No such file or directory
/volume1/WebReportingO_Grain/QuestPdfSkia.so: cannot open shared object file: No such file or directory
/volume1/@appstore/dotnet8-runtime/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/libQuestPdfSkia.so: cannot open shared object file: No such file or directory
/volume1/WebReportingO_Grain/libQuestPdfSkia.so: cannot open shared object file: No such file or directory
/volume1/@appstore/dotnet8-runtime/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/QuestPdfSkia: cannot open shared object file: No such file or directory
/volume1/WebReportingO_Grain/QuestPdfSkia: cannot open shared object file: No such file or directory
/volume1/@appstore/dotnet8-runtime/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/libQuestPdfSkia: cannot open shared object file: No such file or directory
/volume1/WebReportingO_Grain/libQuestPdfSkia: cannot open shared object file: No such file or directory

   at QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.API.check_compatibility_by_calculating_sum(Int32 a, Int32 b)
   at QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.CheckIfExceptionIsThrownWhenLoadingNativeDependencies()
   --- End of inner exception stack trace ---
   at QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.<Test>g__ThrowCompatibilityException|1_0(Exception innerException)
   at QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.Test()
   at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.Test()
   at QuestPDF.Settings..cctor()
   --- End of inner exception stack trace ---
   at QuestPDF.Settings.set_License(Nullable`1 value)
   at Program.<Main>$(String[] args) in C:\Projets\ApplicationsCC.NET\WebReportingO_Grain\Program.cs:line 4
Aborted (core dumped)_

So, As mentionned in the error I have tried to change my platform target to Arm64, this force me to switch to runtime Linux-arm64. This compile without any issue. Then I have the following error when I run :

Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'WebReportingO_Grain, Version=9.3.1.0, Culture=neutral, PublicKeyToken=null'.
Aborted (core dumped)

WebReportingO_Grain being the name of my application itself which is quite weird...

**EDIT 2:**
Apparently the .NET8 runtime for Synology may not be compatible with arm64 based on the information I can required from the app itself (/usr/local/bin/dotnet --info) :
  Version:      8.0.1
  Architecture: arm
  Commit:       bf5e279d92
  RID:          linux-arm

So my guess is that I have to stay in version 2023...
Can this be confirmed?

**Comment by MarcinZiabek** [comment]
Linux-arm64 is still supported. Most likely, you are using an older version of the distribution that does not provide a recent enough glibc library. 

To support older Linux distributions, the easiest way is to build QuestPDF native dependencies on equally old distributions, so to support older versions on glibc. The thing is, the build is quite complex and requires many packages, which are simply not available. Ubuntu 18 is all I could achieve after building certain things locally (like Python 3.8, cmake) or using alternative sources (clang). Going back in time is becoming surprisingly and exponentially more difficult.

I may try again, but it is a very time-consuming process—basically, it is trial and error 😢

**Comment by jeremy-c87** [comment]
Currently I am on linux-arm not linux arm64 which is apparently not supported...

**Comment by MarcinZiabek** [comment]
Indeed! Linux-arm is currently not supported. Given the typical server usage of the QuestPDF library, the vast majority of developers are using x64 or arm64 devices. Another challenge is obtaining an arm32 device that still has access to modern build-related tooling. Linux environment is surprisingly more difficult to work with than Windows. 

That being said, I understand that support for arm32 can be important. I am planning to extend quality support for the 2023.12.X version. To reflect this, I have updated the Security Policy: https://github.com/QuestPDF/QuestPDF/blob/main/.github/SECURITY.md

I hope you understand 😄

**Comment by jeremy-c87** [comment]
OK, thanks for the help. I do understand the problematic of maintaining several different platform.

Thanks for help.
