### ISSUE TITLE
Empty string removes height 

### ISSUE THREAD

**Issue by 1kvin** [QuestPDF/QuestPDF#920]
**Describe the bug**
Empty string with BorderBottom displays incorrectly.

**To Reproduce**
```csharp
 row.RelativeItem().Column(col =>
        {
            col.Item().BorderBottom(0.5f).Text(content ?? string.Empty);
            col.Item().AlignCenter().Text(note).Italic().FontSize(6f);
        });
```

**Expected behavior**
Height of BorderBottom is the same for any string

**Screenshots**

with content:
![image](https://github.com/QuestPDF/QuestPDF/assets/46425980/21380eb8-6435-451f-a743-1159ffad7d24)

empty string:
![image](https://github.com/QuestPDF/QuestPDF/assets/46425980/b389ab19-0ed1-4619-ad49-7ec4a3adb7bd)

**Environment**
2024.3.10
Windows

**Comment by 1kvin** [comment]
I also tryed 2024.6.0 :(

**Comment by 1kvin** [comment]
I found out that the empty columns of the table collapse. This is strange behavior.

**Comment by 1kvin** [comment]
```csharp
table.Cell(row++, column).HeaderCell().Text("HEADER");
table.Cell(row++, column).BodyCell().EmptyText();
table.Cell(row++, column).BodyCell().EmptyText();
table.Cell(row++, column).BodyCell().EmptyText();
table.Cell(row++, column).BodyCell().EmptyText();
table.Cell(row++, column).BodyCell().EmptyText();
```

![image](https://github.com/QuestPDF/QuestPDF/assets/46425980/9012aeb8-36cc-417c-b252-fe4bae4029c7)

**Comment by MarcinZiabek** [comment]
I wouldn't consider it a bug, but rather an interpretation of how to measure empty text. We have two options:
1) Empty text should not use any space (zero width and zero height).
2) Empty text should take the width and height of a typical character.

The library currently follows the first option, which also seems to be consistent with HTML. But is it the most preferred or predictable?

I am really looking forward to hearing your perspectives on this matter. Could you please take a moment to share your thoughts?

**Comment by 1kvin** [comment]
I solve it by replace string.empty to Non-breaking space(https://en.wikipedia.org/wiki/Non-breaking_space), but I need to deal with the situation when the user sends me just a space. I think any string (empty or not) should be handled the same. It might be worth adding an option to set the default behavior.

**Comment by 1kvin** [comment]
Please pay attention to the example with the table. I expected 5 columns and 1 header, but in fact there was a header and 3 columns. This can also be fixed by replacing string.empty to Non-breaking space

**Comment by MarcinZiabek** [comment]
> Please pay attention to the example with the table. I expected 5 columns and 1 header, but in fact there was a header and 3 columns. This can also be fixed by replacing string.empty to Non-breaking space

Could you please show entire code for that example? For that specific table?

**Comment by 1kvin** [comment]
This has been fixed in the new version! Thanks for the work!
