### ISSUE TITLE
white spaces and empty colums in table are being neglected

### ISSUE THREAD

**Issue by futurestarSuman** [QuestPDF/QuestPDF#927]
**Describe the bug**
I used white space to maintain small gaps  and empty columns to maintain gaps between table cell and table footer in questpdf 2023.12.2. A week ago i upgraded questpdf to 2024.3.6 it is not working.

**To Reproduce**
```csharp
for (var i = 0; i < 12 - model.Detail.Count; i++)
{
    table.Cell().Element(CellStyle1).Text("");
    table.Cell().Element(CellStyle1).Text(" ");
    table.Cell().Element(CellStyle1).Text(" ");

    IContainer CellStyle1(IContainer cont)
    {
        return cont.DefaultTextStyle(x => x.Thin()).BorderLeft(1).BorderRight(1)
            .BorderColor(Colors.Grey.Darken1).AlignCenter().AlignMiddle();
    }
}
```

**Expected behavior**
Pdf should have gap between table content and table footer
**Screenshots**
![Screenshot 2024-06-14 003308](https://github.com/QuestPDF/QuestPDF/assets/121482667/0e40362f-b7ba-480a-8f4d-66ce9a9eb0ab)
![Screenshot 2024-06-14 003451](https://github.com/QuestPDF/QuestPDF/assets/121482667/d852b025-7679-4847-a37d-74936e818722)

**Environment**
I am using QuestPdf 2024.3.6
Windows 11 x86_64

**Comment by MarcinZiabek** [comment]
Indeed, the text drawing algorithm has been dramatically redesigned in the `2024.3.X` version. While it more accurately follows Unicode standards (right-to-left text, bi-directionality, breaking lines), there are unfortunately some minor breaking changes.

I suggest using the `Padding` element and related overloads to control the empty space. 

```csharp
table.Cell().PaddingHorizontal(2).Text("Sample text");
```

**Comment by futurestarSuman** [comment]
thanks for response I have already deployed padding yesterday and it is working
