### ISSUE TITLE
Auto Item breaks other element constraints

### ISSUE THREAD

**Issue by Kazagan** [QuestPDF/QuestPDF#941]
**Describe the bug**
issue where `.AutoItem()` when used within a row fails to constrain text within the row. 

**To Reproduce**
Use AutoItem on text within a row

**Expected behavior**
For the text to still be constrained within the out column

**Environment**
Windows, 2024.6.0
Upgraded to 2024.6.4, and error still occurs, although no longer allows me to open document and see visual, instead giving debug information. 

![Screenshot 2024-06-28 at 1 52 11 PM](https://github.com/QuestPDF/QuestPDF/assets/46536599/fc845479-1013-4bba-b354-820bca0a5f69)

**Comment by Kazagan** [comment]
Extra colors shown, are used to highlight the area that the text should be constrained to. The blue color is the area I expect the text to be within.

Attached is the desired outcome, this changed the two black boxes to being Auto instead, and the text to relative. Unsure if this will render completely as desired, but seems to work for what I'm trying to do for now. Bug still exists, just clarifying that I did find a way to accomplish what I was trying to do
![Screenshot 2024-06-28 at 1 57 01 PM](https://github.com/QuestPDF/QuestPDF/assets/46536599/7a08df93-222d-4852-ac72-f7dc1b7b5b21)

**Comment by MarcinZiabek** [comment]
The `Row.AutoItem` does not attempt to optimize the layout visually. Instead, it provides as much space to its child as necessary. The layout will break if the child requires more horizontal space than is available. A good approach is to combine the `Row.AutoItem` with `MaxWidth`.

Without your code, it is hard to provide more help, but most likely, you are looking for something like this:

```csharp
.Paddding(8)
.Row(row => 
{
    row.Spacing(8);

    row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
    row.RelativeItem().Text(Placeholders.Paragraph());
    row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
});
```

**Comment by Kazagan** [comment]
That's exactly what I had, It was a row within a row though, so the above picture would have another row next to it with similar content, and the text on the inner row would break out side the outer row.

 ```
 .Row( row =>
{
    row.Paddding(8)
    row.RelativeItem().Row(row => 
    {
        row.Spacing(8);

        row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
        row.RelativeItem().Text(Placeholders.Paragraph());
        row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
     }); 
    row.RelativeItem().Row(row => 
    {
        row.Spacing(8);

        row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
        row.RelativeItem().Text(Placeholders.Paragraph());
        row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
     });  
});
```

something like this.

**Comment by MarcinZiabek** [comment]
I have tested the following code:

```csharp
.Column(column =>
{
    column.Item() // put the content inside a column to constrain vertical space
         .Row( row =>
         {
             row.Spacing(8); // changed padding to spacing
             
             row.RelativeItem().Row(row => 
             {
                 row.Spacing(8);

                 row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
                 row.RelativeItem().Text(Placeholders.Paragraph());
                 row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
             }); 
             row.RelativeItem().Row(row => 
             {
                 row.Spacing(8);

                 row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
                 row.RelativeItem().Text(Placeholders.Paragraph());
                 row.AutoItem().AlignCenter().AlignMiddle().Width(8).Height(8).Background(Colors.Black);
             });  
         });
});
```

It produces the following output:

<img width="563" alt="image" src="https://github.com/QuestPDF/QuestPDF/assets/9263853/93f53847-5570-420f-8a82-2c90a78165fd">

**Comment by Kazagan** [comment]
Yep, sorry, try that again, with
relative
auto
relative
that causes it to overflow

**Comment by MarcinZiabek** [comment]
Thank you for the clarification. This behavior is entirely expected. When the layout issue occurs, the debugging visualization tool attempts to loosen layout constraints (by providing infinite horizontal, vertical or both spaces). Therefore, the Text may appear to overflow to fit on the page.

My suggestion is to use the `Row.AutoItem` API with additional space limiting constraints, e.g., `MaxWidth`, that will ensure minimal required space for other `Row.RelativeItem` elements.
