### ISSUE TITLE
Over-line text

### ISSUE THREAD

**Issue by burkaysucu** [QuestPDF/QuestPDF#951]
Hello,

Could you add support for over-line text? We need it for some mathematical notations.

**Comment by MarcinZiabek** [comment]
It is already possible 😄 

Example usage:

```csharp
.Text(text =>
{
    text.DefaultTextStyle(x => x.FontSize(20));
    
    text.Span("test");
    text.Span("overline").Overline();
    text.Span("bold").Overline().DecorationThickness(2);
});
```

That produces:

<img width="459" alt="image" src="https://github.com/user-attachments/assets/ffc050fe-5829-4334-ba27-267fca45239a">

**Comment by burkaysucu** [comment]
Looks like we overlooked it :D. Thank you! Btw, it is not mentioned in the API reference page.
