### ISSUE TITLE
multiple Table.Header is not working anymore

### ISSUE THREAD

**Issue by danirzv** [QuestPDF/QuestPDF#965]
**Describe the bug**
when calling multiple times `Table.Header` method it throws exception
```
The 'Table.Header' layer has already been defined. Please call this method only once
```
**To Reproduce**
Create a document with a table within and then something like this:
```
.Table(table =>
            {
               foreach (var headerRow in element.Headers)
                {
                    table.Header(header =>
                    {
                     // Some content
                     }
                 }
            });
```
**Expected behavior**
let me add multiple rows of header in top of tables is all pages
(this were working on older versions and I were using it, this was a functionality breaking change)

**Environment**
What version of the library do you use?  
2024.7.1

What operating system do you use?
Win x64

**Comment by danirzv** [comment]
Update: This Problem happened since c7a81b2

**Comment by MarcinZiabek** [comment]
Thank you for sharing this observation 😄 

I consider the current behavior as correct. Would you please describe your use case? Generally speaking, you should declare the table header/footer only once. Otherwise, the library's behavior could be indeterministic, making certain code to be ignored and causing unnecessary confusion.

**Comment by danirzv** [comment]
In my use case table has two rows of header fixed on top, one has 100% col span and describing content of table, the 2nd one has each column description, actually i think its pretty normal as even html table or headers of excel document do same behavior

**Comment by MarcinZiabek** [comment]
You can define multiple rows in the header/footer section as in this example: https://www.questpdf.com/api-reference/table.html#table-header-footer

Could you please give it a try?

**Comment by danirzv** [comment]
Your example contains a cell with rowspan 2, which i dont have such thing in my case.
Actually i exposed API for my service to generate pdf and it were working, but after updating package people keep reporting this issue

**Comment by MarcinZiabek** [comment]
The provided example shows how to build complex table headers, including multi-level rows and cells spanning multiple cells. It is sufficient to create even more complex headers.

Please note that in your example, if I am correct, only the last header would be visible, which is clearly not desirable.

**Comment by danirzv** [comment]
No its not right, all different header rows were visible in older versions.
And your example REQUIRED a cell with `rowspan` which in my case i dont have one

**Comment by MercinaM** [comment]
The example in the documentation doesn't require a cell with `rowspan`, it just illustrates that as something you can do.

Here is the same exact code with the first column removed (and therefore no cells with `rowspan`):

```CSharp
var pageSizes = new List<(string name, double width, double height)>()
{
    ("Letter (ANSI A)", 8.5f, 11),
    ("Legal", 8.5f, 14),
    ("Ledger (ANSI B)", 11, 17),
    ("Tabloid (ANSI B)", 17, 11),
    ("ANSI C", 22, 17),
    ("ANSI D", 34, 22),
    ("ANSI E", 44, 34)
};

const int inchesToPoints = 72;

container
    .Padding(10)
    .Shrink()
    .Border(1)
    .Table(table =>
    {
        IContainer DefaultCellStyle(IContainer container, string backgroundColor)
        {
            return container
                .Border(1)
                .BorderColor(Colors.Grey.Lighten1)
                .Background(backgroundColor)
                .PaddingVertical(5)
                .PaddingHorizontal(10)
                .AlignCenter()
                .AlignMiddle();
        }

        table.ColumnsDefinition(columns =>
        {
            //columns.RelativeColumn();

            columns.ConstantColumn(75);
            columns.ConstantColumn(75);

            columns.ConstantColumn(75);
            columns.ConstantColumn(75);
        });

        table.Header(header =>
        {
            // please be sure to call the 'header' handler!

            //header.Cell().RowSpan(2).Element(CellStyle).ExtendHorizontal().AlignLeft().Text("Document type");

            header.Cell().ColumnSpan(2).Element(CellStyle).Text("Inches");
            header.Cell().ColumnSpan(2).Element(CellStyle).Text("Points");

            header.Cell().Element(CellStyle).Text("Width");
            header.Cell().Element(CellStyle).Text("Height");

            header.Cell().Element(CellStyle).Text("Width");
            header.Cell().Element(CellStyle).Text("Height");

            // you can extend existing styles by creating additional methods
            IContainer CellStyle(IContainer container) => DefaultCellStyle(container, Colors.Grey.Lighten3);
        });

        foreach (var page in pageSizes)
        {
            //table.Cell().Element(CellStyle).ExtendHorizontal().AlignLeft().Text(page.name);

            // inches
            table.Cell().Element(CellStyle).Text(page.width);
            table.Cell().Element(CellStyle).Text(page.height);

            // points
            table.Cell().Element(CellStyle).Text(page.width * inchesToPoints);
            table.Cell().Element(CellStyle).Text(page.height * inchesToPoints);

            IContainer CellStyle(IContainer container) => DefaultCellStyle(container, Colors.White).ShowOnce();
        }
    });
```

And the resulting table:

![image](https://github.com/user-attachments/assets/027b394a-8902-4820-b818-a433674628d8)

In your example (I assume, since you've provided very little code), all you'd have to change is move the loop inside the `.Header()' method:

```CSharp
.Table(table =>
{
    table.Header(header =>
    {
        foreach (var headerRow in element.Headers)
        {
            // Some content
        }
    }
});
```

**Comment by danirzv** [comment]
@MercinaM I can't find where you've defined to break row after `Points` cell and `Width` became in 2nd row

**Comment by MercinaM** [comment]
> @MercinaM I can't find where you've defined to break row after `Points` cell and `Width` became in 2nd row

By default, QuestPDF's Table API doesn't have manual row breaks. Instead, `.Cell()` will automatically go in the next line once all of the columns are used up in the current line.

The above example has 4 total columns defined in `ColumnsDefinition`. As soon as you use up all 4 columns, the next `.Cell()` call will automatically go in the next row.

Alternatively, you can manually specify each cell's position by using `.Cell().Row(rowIndex).Column(columnIndex)`.

**Comment by danirzv** [comment]
Thank you for your kind describing 🙏
