### ISSUE TITLE
DocumentLayoutException on upgrading from 2024.3.10 with rotated element

### ISSUE THREAD

**Issue by haraman21** [QuestPDF/QuestPDF#974]
**Describe the bug**
Hi
I created a document using version 2024.3.10 that works fine as in screenshot below. But all later versions (2024.6.x, 2024.7.x) generate DocumentLayoutException with following trace:

    QuestPDF.Drawing.Exceptions.DocumentLayoutException: The provided document content contains conflicting size constraints.
    For example, some elements may require more space than is available. 

    The layout issue is likely present in the following part of the document: 
    -> Document
    -> Page
    -> Page content
    -> In method:   ComposeSideBar
       Called from: Compose
       Source path: D:\Projects\Sample\Sample\SampleDocument.cs
       Line number: 49

    -> In method:   c => Block(c)
       Called from: ComposeSideBar
       Source path: D:\Projects\Sample\Sample\SampleDocument.cs
       Line number: 78

    To learn more, please analyse the document measurement of the problematic location: 

    🔴 Extend
    ==========
    Available Space: (Width: 50.000, Height: 842.000)
    Space Plan: Wrap
    Wrap Reason: Forwarded from child
    ----------
    Extend Vertical: True
    Extend Horizontal: True

       🔴 SimpleRotate
       ================
       Available Space: (Width: 50.000, Height: 842.000)
       Space Plan: Wrap
       Wrap Reason: Forwarded from child
       ----------------
       Turn Count: -1
       Normalized Turn Count: 3

          🔴 Alignment
          =============
          Available Space: (Width: 842.000, Height: 50.000)
          Space Plan: Wrap
          Wrap Reason: Forwarded from child
          -------------
          Vertical: Middle
          Horizontal: Center

             🚨 TextBlock 🚨
             ================
             Available Space: (Width: 842.000, Height: 50.000)
             Space Plan: Wrap
             Wrap Reason: The available space is not sufficient to render even a single line of text.
             ----------------
             Alignment: Center
             Content Direction: LeftToRight
             Line Clamp: -
             Line Clamp Ellipsis: -
             Paragraph Spacing: 0
             Paragraph First Line Indentation: 0
             Text: DRAFT-1579

**To Reproduce**
Document structure is like:

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Content()
                .Row(row =>
                {
                    row.ConstantItem(50)
                        .Background(Colors.Grey.Lighten2)
                        .ExtendVertical()
                        .Element(ComposeSideBar);
                    row.RelativeItem()
                        .ExtendVertical()
                        .Column(col =>
                        {
                            col.Item()
                                .Element(ComposeHeader);
                            col.Item()
                                .Element(ComposeContent);
                            col.Item()
                                .ExtendVertical()
                                .AlignBottom()
                                .Element(ComposeFooter);
                        });
                });
        });
    }

    void ComposeSideBar(IContainer container)
    {
        container.Column(sidebar =>
        {
            sidebar.Item().Column(column =>
            {
                column.Item()
                    .Element(c => Block(c))
                    //==============================
                    .RotateLeft()
                    //==============================
                    .AlignMiddle()
                    .AlignCenter()
                    .Text("DRAFT-1579")
                    .LetterSpacing(0.8f)
                    .FontSize(42)
                    .ExtraBold()
                    .FontColor(Colors.White);
            });
        });
        static IContainer Block(IContainer container)
        {
            return container
                .Extend();
        }
    }

    void ComposeHeader(IContainer container)
    {
        ...
    }

    void ComposeContent(IContainer container)
    {
        ...
    }

    void ComposeFooter(IContainer container)
    {
        ...
    }

**Expected behavior**
Consistent layout between versions

**Screenshots**
![image](https://github.com/user-attachments/assets/ca9bd71c-2b5b-4c74-b878-f67900c7dbe4)

**Environment**
What version of the library do you use?
net8.0, QuestPDF 2024.3.10, 2024.6.x, 2024.7.x

What operating system do you use? (OS type, x64 vs x86 vs arm64)
Windows 10 Pro x64

**Additional Context**
The basic idea is to create a full height side bar with short text. Page size is A4 portrait. It seems document layout updates from 2024.6.x and later restrict rotated content also. Is it a bug? Or else is there any other way to achieve this layout in later versions?

**Comment by MarcinZiabek** [comment]
Hi 😄 

The `2024.6.X` release fixes text handling and calculations related to the line-height property. Your text is slightly too high after that fix. I would suggest that you reduce the font size as a solution.

**Comment by haraman21** [comment]
As it was working fine in earlier version, I looked only for layout issues.
Instead of decreasing the font size I just tried to reduce `LineHeight()` and it worked.
Thanks for pointing in the right direction.
