### ISSUE TITLE
Color.FromRGB(0,0,0) has alpha 0

### ISSUE THREAD

**Issue by BeneHenke** [QuestPDF/QuestPDF#978]
When using the Color.FromRGB function the parameters 0,0,0 are not displayed because its alpha value is 0. I am not sure if this is intended or if I did something wrong.

Color.FromRGB(0,0,0)
![image](https://github.com/user-attachments/assets/5894fce2-de0f-4ae6-a0b7-d30ef0e3f264)
Black when using Colors.Black
![image](https://github.com/user-attachments/assets/f28c8e8c-5f86-40bc-857d-46ef0d43ac73)

**Environment**
What version of the library do you use? 
2024.7.3

**Comment by MarcinZiabek** [comment]
Thank you for finding this issue! 😄 

I completely agree with you. This behavior is different than expected and should be considered as bug. I have just fixed it in https://github.com/QuestPDF/QuestPDF/commit/5de776ef7ddf2264fe53df63a0e7fe79e376296f. It will be published as part of the next minor release.
