### ISSUE TITLE
Companion App is probably stuck

### ISSUE THREAD

**Issue by rima1005** [QuestPDF/QuestPDF#998]
**Describe the bug**
The Companion App does not show any window when started (with or without admin privileges). It is visible in the Task Manager as questpdf_companion though. When calling `ShowInCompanion()` the following error occurs:

Unhandled exception. System.Exception: Cannot connect to the QuestPDF Companion tool. Please ensure that the tool is running and the port is correct. Learn more: https://www.questpdf.com/companion/usage.html

**To Reproduce**
Install latest Companion App and try to run it.

**Expected behavior**
Companion App starts with default screen as in previous version 2024.10.0

**Environment**
QuestPDF 2024.10.0-rc1
Companion App 2024.10.1
Windows 11 Pro, 64bit

**Comment by sbsrouteur** [comment]
Same here.
When started from a debugger I get the following  error message :
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setMovable on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      WindowManager.setMovable (package:window_manager/src/window_manager.dart:461)
<asynchronous suspension>
#2      main (package:questpdf_companion/main.dart:13)
<asynchronous suspension>
```

Previous version was starting fine. I unstalled all, wiped the program folder and reinstalled. no change.

**Comment by MarcinZiabek** [comment]
Thank you for noticing this issue 😄  Could you please try the `2024.10.2` release?

**Comment by sbsrouteur** [comment]
Tried 2024.10.2 release. Companion starts. But app does not.

I have tried all 3 rc of the questpdf nuget. They all fail in the show companion with some json parsing exception :
![image](https://github.com/user-attachments/assets/fb9fdb8d-0cbe-4134-843e-d88ae3520dfd)

**Comment by MarcinZiabek** [comment]
@sbsrouteur Could you please share the JSON content that is sent from the Companion App?

**Comment by sbsrouteur** [comment]
something like this?
![image](https://github.com/user-attachments/assets/5f4fb6b9-ecf1-4c50-9763-a800f21413ce)

this does not look like proper json, unless it gets wrapped in json later on.

**Comment by sbsrouteur** [comment]
ok I got it, the previewer was still running. I killed it, and it's much better now. sorry about this.

The companion started on the port, but did not complain it could not bind.

**Comment by MarcinZiabek** [comment]
Maybe it does make sense to:
1) Change the default port slightly, e.g. from `12500` to `12600`.
2) Show some exception dialog when the communication server cannot be started.

What do you think?

**Comment by sbsrouteur** [comment]
Changing the port is not really a requirement, since preview mode is not supported anymore so it will not be an issue for long.
Some exception dialog to inform of communication error would be nice :)

Handling the previous format that was not json to explain it is not the proper would be nice as well. (even though the fault was on my side on this one)

**Comment by testalino** [comment]
I wasn't able open to open the companion app as well with the latest RC (from the windows start menu).

**Comment by MarcinZiabek** [comment]
The QuestPDF Companion source code is yet to be open-sourced in the upcoming feature. Till then, I would like to ensure its quality and stability 😄 

Could you please test the `2024.10.3` release? It should fix the issue of the application crashing when the target editor is not available.

**Comment by rima1005** [comment]
Hi, With 2024.10.3 everything seems to work fine for me. Did not have to change any ports.
